### ISSUE TITLE
Consider using geolocation to automatically populate location

### ISSUE THREAD

**Issue by benjaffe** [microcovid/microcovid#1009]
We could provide a button "Find my location" which uses the geolocation API to get lat/lon, and then a reverse geocoding lookup via a Google API to try to ascertain state and county. What are people's thoughts around me possibly adding this?

Also, do we have an API key for Google associated with this project?

**Comment by blanchardjeremy** [comment]
I support this!

I don't think we have a Google API key.

We'd need to consider how this change would intersect with #451 .

**Comment by blanchardjeremy** [comment]
Also, I think this is a dupe of #177

**Comment by benjaffe** [comment]
Ah yes, it is! Thank you @blanchardjeremy !
