### ISSUE TITLE
Add titles to calculator changelog

### ISSUE THREAD

**Issue by blanchardjeremy** [microCOVID/microCOVID#1011]
Very small improvement, but it would be nice if each item in the [calculator changelog](https://microcovid.org/paper/changelog) had a title, for easier skimming: 
![image](https://user-images.githubusercontent.com/32290/130330562-212cb800-7ffd-4fc9-b60f-094357f4ca52.png)

It would be implemented in a similar way that I did on the [Risk Tracker changlog](https://microcovid.org/tracker/changelog)

**Comment by siddharth1704** [comment]
ok what titles do i need  to add ? can you tell me that

**Comment by siddharth1704** [comment]
ok i got it can you assign me on this issue

**Comment by blanchardjeremy** [comment]
@siddharth1704  hi there. Thanks for offering. I actually just opened a PR for this already. #1014 

You're welcome to offer any suggestions or additional code contributions there. :)
