### ISSUE TITLE
Add python formatter

### ISSUE THREAD

**Issue by blanchardjeremy** [microCOVID/microCOVID#1030]
We only have one (main) python file, but we don't have a workspace-wide config file for it, so it keeps

Steps:

1. Pick a linter
2. Add a config file for it
3. Add the lint run to `yarn lint` and `yarn fix`

Bonus: 
- Make sure that VSCode automatically picks up the linter we're using

**Comment by oxytocinlove** [comment]
AD in #1032 we actually want a formatter not a linter. Plan is to add `black`
