### ISSUE TITLE
Risk Tracker: bug in discounting environment influence on close proximity interactions

### ISSUE THREAD

**Issue by durka** [microCOVID/microCOVID#1033]
On the website, if you select 1 foot distance you get the following warning

> We are ignoring environment choice in this calculation. We are not confident that good ventilation or being outdoors substantially reduces the risk when people are this close to each other.

In the spreadsheet this appears to be handled by this fragment of the `Activity Log!F` formula

```
IF(AND(AD12=ACTIVITY_TITLE_CUDDLING,
             AA12=ACTIVITY_TITLE_OUTDOOR),
         ACTIVITY_TITLE_INDOOR,
         AA12)
```

But this special case doesn't apply to the other environments, such as planes, trains, "indoors with HEPA" or "a space with one or more sides open". This results in outdoor cuddling activities being rated 4x **more** dangerous than partially indoors, all other parameters the same.

**Comment by blanchardjeremy** [comment]
Official release coming in the next few days. If you want to test it, you can here: https://deploy-preview-1017--microcov.netlify.app/tracker/changelog
