### ISSUE TITLE
Risk Tracker v2.3 seems to be buggy

### ISSUE THREAD

**Issue by vladfi1** [microCOVID/microCOVID#1037]
When I copy-paste the cells into B9, afterwards C9 and C10 have error messages `Function MULTIPLY parameter 2 expects number values. But 'Unknown' is a text and cannot be coerced to a number.`. My guess is that the `VLOOKUP` is somehow failing and returning "Unknown".

**Comment by blanchardjeremy** [comment]
Thanks for the bug report. 

It would be helpful if you could make a copy of your spreadsheet and share it with Blanchard.jeremy@gmail.com so I can poke around and see what's up.

Also, when did you first create your spreadsheet? (I'm wondering how many manual updates it gone through vs when it was originally copied.)

Thanks!

**Comment by vladfi1** [comment]
Just shared it with you. I'm not sure exactly when I first copied it, but it appears to be from mid-May.

**Comment by blanchardjeremy** [comment]
Okay, this is now handled in the forthcoming release of v2.4. You can see the details in PR #1017 

Screenshot of the error state:
![image](https://user-images.githubusercontent.com/32290/131231902-ddd521a0-ace4-403e-a07c-a91a19a2f1c3.png)

Draft changelog instructions here: https://deploy-preview-1017--microcov.netlify.app/tracker/changelog
