### ISSUE TITLE
Remove label description for environment

### ISSUE THREAD

**Issue by jy2wong** [microCOVID/microCOVID#1084]
Environment: and the dropdown items themselves should suffice, and user testing suggests the indoor/outdoor questions may increase confusion.

**Comment by Al-0** [comment]
I will work on this!

**Comment by mariehuynh** [comment]
To clarify, is this asking for "Is it indoor or outdoor? Is the space ventilated, or is the air filtered?" to be removed?

**Comment by apiology** [comment]
That's my reading of it.

**Comment by mariehuynh** [comment]
Would you rather have that field simply disabled or removed completely from all languages?

**Comment by mariehuynh** [comment]
Ah, I just noticed README-TRANSLATIONS.md. Would you rather me leave the field there but blank in case of future changes?

**Comment by apiology** [comment]
To clarify, I believe this is asking for the somewhat redundant description to be removed, not the actual dropdown itself.  

As far as the nuts and bolts, I'd say propose what you think makes sense, maybe describe your reasoning, and I can dig in at the PR review process - not sure I've read README-TRANSLATIONS.md myself :)
