### ISSUE TITLE
Input verification for hours/minutes

### ISSUE THREAD

**Issue by blanchardjeremy** [microCOVID/microCOVID#1107]
The new hours/minutes input is really great! 

And I noticed I can put in improper input to the minutes field:

![image](https://user-images.githubusercontent.com/32290/132390964-e4f09596-fd07-446d-96cb-5eb97d75c2d2.png)

The expected behavior I'd like to see is:

1. I input 90 minutes into the minute field (and leave hour field blank)
2. As soon as the field loses focus, it changes to: 1 hour and 30 minutes.

**Comment by oxytocinlove** [comment]
Why? I considered this but I actually prefer it this way - maybe for some reason the user has "118 minutes" in mind as the length of the activity. Users generally don't like it when their inputs change out from under them

**Comment by blanchardjeremy** [comment]
Huh. Okay. I can get behind that logic. I didn't realize it was something you'd chosen intentionally. 

The only slightly "odd" thing is that if you enter it as "2 hours 90 minutes" and then copy paste the link and return to the page, it will still show up as "3 hours 30 minutes" ... Maybe that's fine. I can see a case that the user doesn't want their input changed while they are type (as you're saying). I can also see a case that they might feel confused that what they put into the form changes when they send the link to someone else or re-visit that link themselves.

I don't feel strongly enough to advocate strongly for it. So if you think it's good, let's just close this issue. :)

**Comment by oxytocinlove** [comment]
Sounds good 👍
