### ISSUE TITLE
How are "shared budget reductions" calculated on the spreadsheet?

### ISSUE THREAD

**Issue by sargunv** [microCOVID/microCOVID#1125]
Here's how I modeled a 1h grocery activity on the website: https://www.microcovid.org/?distance=sixFt&duration=60&interaction=oneTime&personCount=5&riskProfile=average&scenarioName=60minShopping&setting=indoor&subLocation=US_53033&theirMask=basic&topLocation=US_53&voice=silent&yourMask=n95&yourVaccineDoses=2&yourVaccineType=pfizer

Here it is in the "shared budget reductions", showing 6x the risk: ![image](https://user-images.githubusercontent.com/1320357/133385558-abdeff42-52ad-415b-bf52-e0a8429cc454.png)

Is the calculation different between the two?

**Comment by sargunv** [comment]
Actually I believe I've found the issue: the "shared budget reductions" appear to not take into account vaccination status. Here's the same screenshot as above, but I've changed my vaccination status to "no vaccine". The budget reduction did not change.

The 0.17x multiplier for the Pfizer vaccine also matches the 6x difference between models.

**Comment by sargunv** [comment]
Fix: update the formula in D109
```diff
< =GROCERY_ONE_HOUR_BASIC/MASK_MY_BASIC*VLOOKUP(F109, ACTIVITY_RISK_TABLE_MASK, 2, FALSE)*E109
> =GROCERY_ONE_HOUR_BASIC/MASK_MY_BASIC*VLOOKUP(F109, ACTIVITY_RISK_TABLE_MASK, 2, FALSE)*VLOOKUP(C104, VACCINE_TABLE, 4, FALSE)*E109
```

**Comment by blanchardjeremy** [comment]
Oh my gosh I totally thought I had fixed that ages ago. Thank you!!!
