### ISSUE TITLE
Allow manually adjusting risk levels for area

### ISSUE THREAD

**Issue by PurpleKa** [microCOVID/microCOVID#1152]
The calculator doesn't seem to have a way to fix or adjust if if imported data for calculating prevalence of COVID in a given area is broken. For example, if there is no data available on percentages of positive tests, it ends up with a significantly undercalculated prevalence level with no indication that it was calculated without some of the essential data. The delay factor also frequently seems to be broken, with the calculator stating that cases are flat or decreasing when they are actually increasing in a given area.

It would also be useful to be able to adjust prevalence numbers for a specific subset of the population. For example, one of our local high schools has a 2-week average case rate of over 1,500 per 100K, compared to a rate in the general population county-wide of around 500 per 100K. That's a really big difference. High school students are also vaccinated at less than half the rate of the general population. So the prevalence number should be significantly higher when calculating the risk of activities in the school than in the general population.

Is there a way to manually enter calculations to correct the case rate, covid prevalence, vaccination rate, etc. to estimate prevalence for a given population if the import is broken or the people you're interacting with have a known infection rate very different from the "average person" in that area?

**Comment by jy2wong** [comment]
![9DE0A1E8-0F3E-47DD-9C45-A6D0F3393CDB](https://user-images.githubusercontent.com/4390573/135157672-264c6663-252e-404c-81fc-99355e09b382.jpeg)

Sounds like “override location-based data” might be what you are looking for.
