### ISSUE TITLE
Unit conversion error in first line of Introduction page

### ISSUE THREAD

**Issue by cobalt17** [microCOVID/microCOVID#1175]
Hi,

The Introduction page starts: "You’re already familiar with some rules of thumb for avoiding COVID-19 infection: wear a mask, stay 6 feet (1 meter) apart, and only socialize outdoors. ".  6 feet is not 1 metre.  6 feet 6 inches is approximately 2 metres.  1.5 metres is 4 foot 11 inches, near enough to 5 feet.  In the calculator you show 3 feet / 1 metre which is close enough.

Can you update the first line to be a little more accurate and inspire a bit more trust in your research?

Thanks

**Comment by beshaya** [comment]
Good catch, thanks.
