### ISSUE TITLE
B.1.1.529 / Omicron

### ISSUE THREAD

**Issue by bluehat** [microCOVID/microCOVID#1226]
I didn't see an open thread for the variant yet so here one is. Apologies if this is not how you want to track a developing situation and how it might impact the models. Please let me know and I'll try to do stuff that way.

# Why we might care #
The new variant looks to already have dramatically increased transmission rates. It may also have some degree of immune evasion, though this is yet to be determined.

## Rapid Strain Dominance ##
One clear fact is that this strain has [has dramatically displaced Delta](https://www.nicd.ac.za/wp-content/uploads/2021/11/Update-of-SA-sequencing-data-from-GISAID-26-Nov_Final.pdf) in regions of South Africa. Rates vary seem to be over 70% of new sequenced infections for November, though they are clear that the number of sequenced samples is quite low. 

So, there is probably some reason why this strain is so successful, and that means we probably need to research it. It wouldn't be unreasonable for this to become the new dominant strain in the next few weeks.

[Nature estimates the R in impacted areas of South Africa to be above 2.](https://www.nature.com/articles/d41586-021-03614-z)

# Potential Causes #

## Transmissibility ##
Estimates vary wildly. A bunch of epidemiologists on Twitter are claiming 500% transmissibility over the original strain, compared to Delta's 70%. I have attempted to request these models and will update this if I get them. 

There are a number of weird outbreaks that indicate increased transmissibility.
-  At [a holiday party in Norway](https://www.reuters.com/world/europe/omicron-outbreak-norway-christmas-party-is-biggest-outside-s-africa-authorities-2021-12-03/), half of attendees are confirmed positive. 30 of them were infected after the infection sources left the party.

There are a number of weird outbreaks which should not count as proof of increased transmissibility, only of terrible policy
- On the unfortunate [Netherlands KLM Flight](https://www.bbc.com/news/world-europe-59451103) the passengers were left inside an airplane with no mask enforcement for 5 hours. It is unclear that this situation would have ended much better with previous variants.
- [Another flight to the Netherlands](https://www.francetvinfo.fr/sante/maladie/coronavirus/variant-omicron-le-vol-arrive-a-amsterdam-d-afrique-du-sud-est-une-bombe-a-retardement-s-alarme-un-passager_4861431.html) where people were packed in a waiting room

## Immune Evasion ##
A lot of people are tremendously excited about the number of mutations on this variant and how this might theoretically impact immunity evasion. I have no found any evidence of real-world data to make decisions on at this time.

The public health department of South Africa [expects this to be an issue.](https://sacoronavirus.co.za/2021/11/29/presentation-what-we-do-dont-know-about-the-omicron-variant-salim-s-abdool-karim-frs/)

### Natural Immunity ###
[This preprint](https://www.medrxiv.org/content/10.1101/2021.11.11.21266068v2) thinks natural immunity might work less well against this variance, especially from an initial Delta infection.

#### Vague or Small Sample ####
[A preprint from Signallab](https://sigallab.net/) indicates "extensive immune escape" in cell experiments. Since the document is distributed in a 7z, and since I was delayed in getting an official copy by site uptime, I am going to also attach the paper in a follow-up comment. 
[Another preprint](https://www.medrxiv.org/content/10.1101/2021.12.08.21267491v1.full.pdf) is less than encouraging but has extremely small sample sizes.

#### Large Studies ####
We finally have a population study for vaccine evasion
| Study Conducted by | Status | Sample Size | Population Studied | Vaccine Tested | Original Dose | Boosted | Data timeframe (dd/mm)  | 
| --- | --- | --- | --- | --- | --- | --- | --- | 
| [UK Health Security Agency](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1040076/Technical_Briefing_31.pdf) | Government Report | 581 | Symptomatic Patients | Mostly Pfizer with Pfizer boost | 30% - 40% | 70% - 80% | 27/11 - 6/12 |

### Mechanism ###
[Another preprint](https://osf.io/f7txy/) discusses how it is possible that the virus sampled in other genetic material, which might give it better immune evasion.

## History ##
Though the variant has been sourced from other places, most of the data and science comes from South Africa.

South Africa has had an uptick. Estimates of this are confusing and vary wildly. Worldometers has a [compartively modest uptick over the past two weeks](https://www.worldometers.info/coronavirus/country/south-africa/) going from about 300 infections a day to 3000 infections a day.

Whereas, unless I am reading this wrong or have the wrong source for the local department of health, the [impact in Gautang alone has included numbers that say there were well over 10K new infections on one of these days](https://sacoronavirus.co.za/category/daily-cases/).

A reminder: whatever the cause of this is, it is likely not seasonal. It is the beginning of summer in the Southern Hemisphere.

**Comment by beshaya** [comment]
Thanks for opening this ticket. I agree that the preliminary data on Omicron is concerning but, as you stated, data is still fairly scarce. Your help in tracking research as it comes out is very much appreciated.

**Comment by bluehat** [comment]
Given that we are seeing an R above 2 in some areas, how far Omicron has already spread, and the number of people who check the calculator often, it might make sense to add a disclaimer that these models are not updated for Omicron and that caution is advised as the situation develops. 

By the end of next week, people in many major cities will be operating in a different and unknown risk regime, and I think we should be clear about that even if we can't fully update the models immediately.

**Comment by MichelleGlauser** [comment]
So glad this issue already exists, and I agree with the last comment—people at least need to know to beware that Omicron is not yet covered for their holiday planning.

**Comment by bluehat** [comment]
We have a preprint indicating "extensive immune escape" for vaccinated individuals in a cell experiment. I think it is critical that we approve this pull request to update the header. We need to warn people that this model is likely out of date so they can adjust their holiday plans. Due to previous uptime issues with the signallab site, I am uploading a copy of the paper here as a backup. 

[Preprint of a Sigallab paper that concluded there is "extensive immune escape" for vaccinated individuals](https://github.com/microCOVID/microCOVID/files/7687934/MEDRXIV-2021-267417v1-Sigal.pdf) Official copy (normally) available at https://sigallab.net/

**Comment by beshaya** [comment]
Merged.

**Comment by bluehat** [comment]
We have a plausible first guess for vaccine evasion. People are firming up Christmas and New Year's plans, and so I think integrating these early findings into the model makes sense.

The UK Health Agency survey study has relatively few AZ samples, but guesses that it has the same immunity as Pfizer: 30% - 40% immunity for unboosted and 70%-80% for boosted.

I think we should update all full-dose vaccines to 35%. We do need a more nuanced way to input boosters long-term. However, short term, we can add an additional dosage number field labeled "any booster" that brings immunity to 75%. 

Because this is a pretty big change in the model, I'm posting this here for comment before coding up a pull request.

**Comment by beshaya** [comment]
Thanks for finding this. Could you include research links? We'll need to
update the whitepaper at the same time as the model.

**Comment by brainwane** [comment]
https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/2021-12-16-COVID19-Report-49.pdf as reported on [in the FT](https://archive.md/0QjvI).

**Comment by beshaya** [comment]
Thanks.

Am I reading this correctly - the chart on page 7 lists *negative* Vaccine
effectiveness for 2 doses of AZ and 1 or 2 doses of Pfizer?

**Comment by zerotrickpony** [comment]
In case it helps, [Technical Brief 32](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1042046/Technical_Briefing_32.pdf) is now out from the UK, pub date December 17th.

Starting on page 20 there's a summary of household and non-household attack rates for Omicron vs Delta is presented, based on 777 Omicron cases and UK contact tracing data. Confidence intervals are in there. The paper cautions against conclusions due to the small sample size so far.

The preliminary conclusion is ~2.9x odds ratio of household transmission for Omicron vs Delta, with similar ratios for non-household transmission. The paper says this number is "adjusted for ... vaccination status" but it didn't provide any other details of the adjustment that I could find.
