### ISSUE TITLE
The date last updated field shows "invalid date"

### ISSUE THREAD

**Issue by blanchardjeremy** [microCOVID/microCOVID#1246]
The date last updated field shows "invalid date"

![image](https://user-images.githubusercontent.com/32290/146021527-50c603b9-fd65-4153-ace3-2aff04a2e1ec.png)

https://www.microcovid.org/?distance=sixFt&duration=120&interaction=oneTime&personCount=10&riskProfile=hasCovid&scenarioName=custom&setting=indoor&subLocation=US_06001&theirMask=basic&topLocation=US_06&voice=normal&yourMask=basic

**Comment by ejgonzalez17** [comment]
Hi !, I will like to work in this Issue .

**Comment by beshaya** [comment]
Fixed by #1249, I think?
