### ISSUE TITLE
URL parameter “yourVaccineDoses” is removed when equal to 3

### ISSUE THREAD

**Issue by RobertSundling** [microCOVID/microCOVID#1291]
With the calculator now allowing third doses, this line needs to be updated so that URLs containing `yourVaccineDoses=3`  work:

https://github.com/microCOVID/microCOVID/blob/a9b9ee55cf9ad77da35b0e298e226ca1c8cea1b8/src/data/calculate.ts#L159

The `2` needs to be changed to a `3`. (Currently, the number of doses is reset to 0 if it’s equal to 3 in the URL.)

**Comment by beshaya** [comment]
Thanks for the catch. Could you open a pull request and tag me as a reviewer?

**Comment by RobertSundling** [comment]
@beshaya - Done. Pull request 1293.
