### ISSUE TITLE
Risk Tracker: Activity Log: microCovid Values and emoticons (Key) Not Calculated on rows 17-20

### ISSUE THREAD

**Issue by Zian** [microCOVID/microCOVID#1301]
# Expected Result
I expected to see visible #s in cells A17-A20 and cells B17-B20 after entering activities in rows 6-20. I also thought that emoticons should be visible in N17-N20.

# Actual Result
Cells A17-A20 and cells B17-B20 are blank. There are no emoticons in N17-N20.

# Steps to Reproduce After Having a Configured Sheet
1. Go to the Activity Log sheet.
2. Enter the following activity 11 times under "A":

	- Last Date: 11/16/2021
	- Activity Description: Vons
	- \# other people: 5
	- Person Risk Profile: Avg local resident
	- Where do they live? Leave it blank
	- Asked: symptom free now? Leave it blank
	- Asked: will notify you if symptoms? Leave it blank
	- One-time hangout vs. ongoing relationship? One time
	- How long? 0 hours and 30 minutes
	- Environment / Venilation [sic]: Indoor
	- Your mask: Surgical mask
	- Their mask: Cotton mask, thick and snug (multi-layer cotton mask with tight, secure fit)
	- Distance: 6+ ft most of the time
	- Volume: Silent

3. Confirm that the next blank row is row 17.
4. Enter the same activity as step 2 but use today's date as the "Last Date".
5. Repeat step 4 3 more times so that the next blank row is row 21.

# Configuring the Workbook
1. Go to https://www.microcovid.org/tracker/quickstart
2. Click "click here to make a copy of the Risk Tracker".
3. Add a new vaccine entry with the values from the main microCOVID calculator for boosters as follows:

	1. Go to the left-most INTERNAL_ACTIVITY sheet.
	2. Click on cell I3.
	3. Type "mRNA 3x"
	4. Enter "1" in J31, "0.8" in K31, and "0.25" in L31.
	5. Wait for the green progress bar in the upper-right hand corner to finish bouncing around.

4. Configure the Locations sheet:

	1. Select "San Diego" from cell D6's drop-down menu.
	2. Wait for the green progress bar to finish bouncing around.
	3. Select "California" from C7.
	4. Wait for the green progress bar to finish bouncing around.
	5. Try clicking on D7. If a list of counties appear, select "Los Angeles". Otherwise, go to step 4.
	6. Repeat steps 3-5 to add 2 more counties in California and one county in a different state.
	7. Wait for the green progress bar to finish bouncing around.

5. Configure the Pod Overview sheet as follows:

	- 3 people (A, B, and C)
	- Person A was immunized on 3/1/2021 and 4/1/2021 with "mRNA 3x".
	- Person B&C received the same immunization on May 1 and June 1 in 2021.
	- Set C104 to "mRNA 3x"
	- Enter "0" in D109

6. Wait for the green progress bar in the upper-right hand corner to finish bouncing around.
7. Verify that C128 says "159".
8. Remove the existing entries in the Activity Log sheet.
9. Change the names of the first 3 people in the Activity Log sheet to A, B, and C. Don't touch Dave. 

# Computing Environment
- Windows 10 Version 21H1 (EN-US)
- Firefox 95.02
- Browser is fully maximized on my primary monitor.
- The primary monitor is a Dell P2418D running at 2560x1440, 60Hz.
- The other active monitor is located to the right. It is an Asus VS229H running at 1080x1920 in a "Portrait (flipped)" orientation.

# Reacted Screenshot of the Primary Monitor
![Redacted Screenshot](https://user-images.githubusercontent.com/1581929/148666313-32a5bf1b-51d0-42cd-b607-ee4d326186e2.png)

**Comment by beshaya** [comment]
Thanks for the detailed bug report! I've gone ahead and fixed it on the live version (2.4.1).

You can fix it on your sheet by dragging the cells A16 and B16 through row 20.
