### ISSUE TITLE
Placeholder "calculator.explanationcard.details_activity_risk" showing up in calculation details

### ISSUE THREAD

**Issue by orborde** [microCOVID/microCOVID#1302]
**Describe the bug**

![image](https://user-images.githubusercontent.com/804638/148677488-9a874940-2441-46d7-8f4a-6f7ea613c48b.png)

It looks like `calculator.explanationcard.details_activity_risk` is a placeholder or something that is not supposed to appear there.

**Link to microCOVID scenario**
https://www.microcovid.org/?distance=normal&duration=60&interaction=oneTime&personCount=4&riskProfile=average&scenarioName=indoorUnmasked2&setting=indoor&theirMask=basic&theirVaccine=unvaccinated&topLocation=US_53&voice=normal&yourMask=p100&yourVaccineDoses=3&yourVaccineType=pfizer

**To Reproduce**
I think the above is likely to be sufficient, but I'll put in more effort on a repro if you can't get it to repro.

**Expected behavior**
a meaningful description instead of placeholder text

**Is this a regression?**
> Was this feature working properly before? If so, when was the last time it worked the way you expected?

I dimly remember it working correctly months ago? But it has definitely been broken for at least 2 weeks.

**Comment by ruadh** [comment]
Looks like several lines removed from en.json with in various commits, most recently aebed7a2acf1a3599e4f65b30a3ef364388a7ff0.  (The original text removed there was wonky, so it looks like they meant to correct it, but deleted it instead.)

Three other values were missing in that same area:
(I did not check any other regions)
- calculator.explanationcard.chance
- calculator.explanationcard.details_activity_risk
- calculator.explanationcard.details_activity_risk_explanation
- calculator.explanationcard.details_frequency

I submitted a pull request with a fix:
https://github.com/microCOVID/microCOVID/pull/1374

**Comment by apiology** [comment]
Appears to have been fixed by #1374:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/3681194/209951702-97dbd180-2807-4327-ac74-f52ccf69f9c3.png">
