### ISSUE TITLE
Weblate translation workflow looks stuck

### ISSUE THREAD

**Issue by 1000i100** [microCOVID/microCOVID#1320]
**Describe the bug**
2 parts : 
- Last string about omicron are not available in weblate to translate them
- The last weblate merge-request is blocked since last september.

**Expected behavior**
- Sync microCOVID github source to weblate to send there up to date string to translate
- Smooth merge request to add translations.

**Is this a regression?**
it look like one because many merge request before september was merged.

**Additional context / screenshots**
I would like to finish French translation. (I'm French native)

**Comment by jy2wong** [comment]
https://github.com/microCOVID/microCOVID/pull/1154 Squashed and merged. I'll try to keep a closer eye on the weblate PRs, sorry about that.
