### ISSUE TITLE
Add warning to UI when prevalence data is more than ~1 week out of date

### ISSUE THREAD

**Issue by justinhaaheim** [microCOVID/microCOVID#1330]
When our recent prevalence updates started failing (see discussion on #1326) the data for microcovid.org and the spreadsheet got to be 10 days out of date. Let's create some sort of UI alert to let people know the data is stale and that we're working on fixing it.

**Comment by apiology** [comment]
I was bitten again with the current stall - see https://github.com/microCOVID/microCOVID/issues/1436

I'd be willing to take a crack at this as a first-time contributor.  Let me know what you think or if you have any guidance.
