### ISSUE TITLE
Create dev alert for prevalence update fatals & errors

### ISSUE THREAD

**Issue by justinhaaheim** [microCOVID/microCOVID#1331]
It looks like we don't have any dev alerting for when prevalence updates are failing. When that happened this month (January 2022) we heard about it from a few reports by microcovid team members who happened to notice. Let's put in place some alerting that goes to slack if this happens again.

Along with this we can add some alerting for errors as well -- that is, errors like "this country is being discarded due to an exception during the prevalence update" that don't result in a fatal, but are still important to know about and address.

**Comment by EricReuss** [comment]
I just noticed that prevalence rates don't seem to have been updated this week (showing last update as 02/06); came here to suggest just this sort of thing.

**Comment by apiology** [comment]
Whoops, I missed this existing issue when I filed https://github.com/microCOVID/microCOVID/issues/1658.  Sorry for the duplicate!
