### ISSUE TITLE
Prevalence updates failing since 2/8/22

### ISSUE THREAD

**Issue by justinhaaheim** [microCOVID/microCOVID#1353]
Here's the log:
```
ValueError: JHU data has cases but no population for Country(fullname='Antarctica', name='Antarctica', population=0, test_positivity_rate=None, cumulative_cases=Counter(), tests_in_past_week=None, vaccines_by_type=None, vaccines_total=Vaccination(partial_vaccinations=0, completed_vaccinations=0), iso3='ATA', states={}) with line data: JHUDailyReport(FIPS=None, Admin2=None, Province_State=None, Country_Region='Antarctica', Lat=-71.9499, Long_=23.346999999999998, Combined_Key='Antarctica', Confirmed=11, Deaths=0, Recovered=0, Active=0)
```

This is another good candidate for catching the error but continuing with the update.

**Comment by SeventhCycle** [comment]
I noticed on the preview URL here:
https://deploy-preview-1354--microcov.netlify.app/

That it's still using February 6th as its most recent date. Is this an issue with the build script here? Or is there an additional issue here that is preventing the information from being updated?

**Comment by zestyping** [comment]
Is microcovid.org still maintained?  It's been two weeks.

covidmeter.org is still updating correctly, running the same script as microcovid but with these exclusions patched into `ignore_jhu_place`:

```
    ignore_jhu_place = update_prevalence.ignore_jhu_place

    def patched_ignore_jhu_place(line):
        if 'Olympics' in line.Country_Region:
            return True
        if 'Antarctica' in line.Country_Region:
            return True
        return ignore_jhu_place(line)
```

I recommend cloning https://github.com/zestyping/covidmeter and running `get_prevalence_js get_prevalence_js ee4b619affe6458e8dd2838d260d7a01` if you want more recent updates.
