### ISSUE TITLE
Split into three mask types

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#137]
Split into three mask types:
* No mask
* Bandana, buff, or single-layer cotton
* Mask with filter insert, or N95 or better

aiui Bandana/buff is quite good for source control, not as good for wearer protection.

**Comment by catherio** [comment]
Also add advanced masks from spreadsheet to calculator cc @beshaya 

(and explain all the above in the main text)

**Comment by beshaya** [comment]
I'm taking this and will add outflow valves as well.

**Comment by catherio** [comment]
For *this* issue, we just want

My mask protects me:
No mask - None
Bandana, buff, or single-layer cotton - None
Surgical mask, mask with filter insert, or N95 or better - 2x

Your mask protects me:
No mask - None
Bandana, buff, or single-layer cotton - 4x
Surgical mask, mask with filter insert, or N95 or better - 4x

**Comment by catherio** [comment]
You could also do #159 
and #136

**Comment by catherio** [comment]
Mask with outflow valve should not make any difference in this PR. It is as good as a basic mask.

**Comment by beshaya** [comment]
I thought outflow valves are considered bad. Is the law against them misguided?

**Comment by catherio** [comment]
Do you have any evidence about that?

All I have is this from the Fischer study
![image](https://user-images.githubusercontent.com/245037/91670731-07527700-ead5-11ea-8f1d-7164015604e5.png)

(the study everyone's using to freak out about bandanas, which, I also don't think is justified)

**Comment by catherio** [comment]
Let's save valves for https://github.com/microcovid/microcovid/issues/159 which is labeled "epistemic deep dive"!

**Comment by beshaya** [comment]
Fine deferring valves. 

That chart shows valved N95 significantly worse than fitted n95 or surgical for "their mask."

**Comment by catherio** [comment]
more about the specific trifurcation suggested here:
![image](https://user-images.githubusercontent.com/245037/91670775-5bf5f200-ead5-11ea-93bf-053692318641.png)

**Comment by blanchardjeremy** [comment]
Question: did this change also make it into the spreadsheet?
