### ISSUE TITLE
Add example to top of calculator

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#138]
"For example, we think the risk of going to the grocery store in <location> wearing a mask is N microCOVID."

![image](https://user-images.githubusercontent.com/245037/91646857-bffeb480-ea08-11ea-90b1-cac8cc1d03bc.png)

**Comment by jy2wong** [comment]
I think this is sorta achieved with the list of suggestions:

> Examples: how risky is a trip to my grocery store? What's the safest way to see a friend? How much would it help to wear a better mask at my workplace?
