### ISSUE TITLE
Improve default Risk Profile for built-in scenarios

### ISSUE THREAD

**Issue by ezyang** [microcovid/microcovid#139]
Steps to reproduce:
1. Select "New Jersey"
2. Select "Middlesex"
3. Select "Physically intimate with a person"
4. Verify that type of interaction defaulted to "Partner / spouse"

Expected result: Low risk activity
Actual result: Very high risk activity

What's the problem? Well, this scenario defaults to "An average person in your area". But this seems a bit incongruous with "Partner / spouse"; the right default scenario probably should be something else.

I don't know if this is annoying to fix; it's a minor problem and not too difficult to manually figure out what is going on and fix, but it was a bit surprising when I was playing around with the tool!

**Comment by catherio** [comment]
> this seems a bit incongruous with "Partner / spouse"

Can you say more? Why should we not assume that the average user's partner is an average person?

**Comment by ezyang** [comment]
Perhaps this is me seeing "Partner / spouse" and mentally parsing this as "spouse"; in which case, no, I don't think I should assume my spouse is an "average person" for risk analysis! To be fair though, partner can mean a lot of things. Maybe it would be clearer to remove spouse from the dialog here.

**Comment by beshaya** [comment]
You can start with the baked-in example and then update the person risk factor based on your spouse's behavior.

We don't have a way to know anything about your spouse! They might be being very safe, but they could be an essential worker.

**Comment by ezyang** [comment]
Alright, consider me convinced :)
