### ISSUE TITLE
Secure connection failed when trying to load site 

### ISSUE THREAD

**Issue by axk4545** [microCOVID/microCOVID#1416]
When I try to load the production instance of microcovid.org it gives me a secure connection failed error.

I have tried this in Mozilla Firefox, Internet Explorer and Google Chrome. I tried it with all my add-ons disabled as well as with my normal add-ons. I also tried it in a blank profile with default settings.

**Comment by zerotrickpony** [comment]
Hmm I'm not able to reproduce this with Chrome or Opera or Firefox. Could you attach your TLS and cert details so we can see the details of the error? In Chrome you would go:

1. Visit https://www.microcovid.org/
2. Click the red icon in the URL bar where it says "! Not Secure"
3. Click where it says "Certificate is not valid"
4. Copy-paste the text in the box, which should include the expiration time and root

Hopefully that will make it more clear what's happening? You may have a DNS setting which is redirecting your TLS, that can happen on naughty hotel wifi, airplane hotspots, etc.

**Comment by axk4545** [comment]
I statically set the DNS server on my machine to Google Public DNS(8.8.8.8) in case that was it and I still get the same error.
![image](https://user-images.githubusercontent.com/3486252/162636679-f00c9754-755c-49fe-879e-e950e6caedd7.png)

**Comment by zerotrickpony** [comment]
Intriguing! I've not seen this before, the internet says SSL_ERROR_RX_RECORD_TOO_LONG is a firefox-specific error, what does it do when you try Chrome?

Also, can you check your proxy settings and see if you have a proxy or VPN configured? And if so, can you disable it in favor of a direct connection, and see if you get a different error?

**Comment by axk4545** [comment]
This is what I get in a completely fresh install of Chrome with default settings:
![image](https://user-images.githubusercontent.com/3486252/162638614-49ff556e-60ec-4005-8927-262671675475.png)

I also checked and I don't have a proxy enabled.

**Comment by axk4545** [comment]
I just tried it on my phone using LTE and it works some it must be something with my home network.

**Comment by LucyMcGowan** [comment]
I have been getting this same error on my network for several months (also works for me on LTE)

**Comment by axk4545** [comment]
I have a feature on my router that blocks suspicious sites. I disabled it
and the site works again. It's an Asus router and I think that feature is
provided by TrendMicro. It must not like LetsEncrypt.

**Comment by apiology** [comment]
Sounds like this one is resolved to the extent we can control it.
