### ISSUE TITLE
Ontario/Canada Recently Showing Zero Weekly Cases

### ISSUE THREAD

**Issue by nh905** [microCOVID/microCOVID#1419]
When I checked on April 9th, the microCOVID score for Canada/Ontario was 0.1 - the Details showed zero weekly cases as of April 8th.  The data was refreshed as of April 10th but is still showing zero weekly cases.  The last time I checked on April 2, the numbers were reasonable.   I spot-checked some health units in Ontario - they look reasonable.  The other provinces/territories are also showing reasonable microCOVID data.

I checked [cases_timeseries_prov.csv](https://github.com/ccodwg/Covid19Canada/blob/master/timeseries_prov/cases_timeseries_prov.csv) - the Ontario and other provincial case data looks good.  There is a note on the COVID-19 Canada Open Data Working Group site that they are making changes but those only go into effect on April 15th.

**Comment by nh905** [comment]
As of April 15th, I am seeing microcovid.org data for Ontario.  However. 39,625 weekly cases and a 31.9% positivity rate seems high.  [https://www.publichealthontario.ca/en/data-and-analysis/infectious-disease/covid-19-data-surveillance/covid-19-data-tool](https://www.publichealthontario.ca/en/data-and-analysis/infectious-disease/covid-19-data-surveillance/covid-19-data-tool) is reporting 40699 cases over the last 14 days while [cases_timeseries_prov.csv](https://github.com/ccodwg/Covid19Canada/blob/master/timeseries_prov/cases_timeseries_prov.csv) is showing about 24000 weekly cases.  The weekly positivity rate is about 19.9% according to the Public Health Infobase.

I spot checked some of the Ontario health units.  Their weekly cases numbers look reasonable but they all showed a positivity of 31.9% which given the spread in weekly cases/100K does not seem right.

**Comment by nh905** [comment]
As of this morning, the data for Canada, the provinces, and the Ontario Health Units is still showing an April 15 date.  This is when the Canada Open Data Working Group made changes to their reporting.

**Comment by Meowse** [comment]
Many other regions also stopped updating on April 15th.

**Comment by nh905** [comment]
As of this morning, Canada/Ontario (including health units) is current as of April 30 and the case counts/positivity look reasonable.
