### ISSUE TITLE
Taiwan data hasn't been updated in 9 ays

### ISSUE THREAD

**Issue by hueykwik** [microCOVID/microCOVID#1426]
**Describe the bug**
Taiwan's COVID data hasn't been updated since 4/15. 

**Link to microCOVID scenario**
[If applicable, please copy-paste the URL to the scenario that you modeled on the calculator, so we can easily reproduce it.
](https://www.microcovid.org/?distance=sixFt&duration=60&interaction=oneTime&personCount=10&riskBudget=30000&riskProfile=average&scenarioName=restaurantIndoors&setting=partiallyEnclosed&theirMask=none&topLocation=Taiwan_&voice=normal&yourMask=none&yourVaccineDoses=2&yourVaccineType=moderna)

**To Reproduce**
1. Go to Step 1
2. Select Taiwan
3. See last updated 4/15/2022

**Expected behavior**
See last updated 4/24/2022 or at least something more recent than 4/15

**Is this a regression?**
Probably

**Additional context / screenshots**
<img width="373" alt="image" src="https://user-images.githubusercontent.com/707311/164954558-2487230f-147b-4e2b-a5af-7e68c0dbad15.png">

**Comment by neutrinonerd3333** [comment]
I've also noticed this for my region (California). It looks like automatic prevalence updates stopped on 4/16 (search PRs with `is:pr label:auto-prevalence-update`), so every region should be affected by this.

**Comment by apiology** [comment]
Presumably fixed by https://github.com/microCOVID/microCOVID/pull/1450.  Please file separate issues if you see any continuing issues.
