### ISSUE TITLE
Data hasn't updated in last week

### ISSUE THREAD

**Issue by sameerjain0123** [microCOVID/microCOVID#1436]
**Describe the bug**
"Data last updated" for San Francisco shows 4/30/2022. My recollection is that data used to update much more frequently, and a lag of a week significantly undercounts risk during a surge like the current one.

**Link to microCOVID scenario**
If applicable, please copy-paste the URL to the scenario that you modeled on the calculator, so we can easily reproduce it.

https://www.microcovid.org/?distance=close&duration=60&interaction=oneTime&personCount=1&riskProfile=livingWithPartner&scenarioName=custom&setting=indoor&subLocation=US_06075&theirMask=thin&theirVaccine=vaccinated&topLocation=US_06&voice=silent&yourMask=n95&yourVaccineDoses=3&yourVaccineType=pfizer

**To Reproduce**
1. Go to microcovid.org
2. Select any country or US State (I tried California / San Francisco, New York, and Hawaii)
3. See error: "Data last updated" is 4/30/2022, even though it is currently 5/7/2022

**Expected behavior**
"Data last updated" should update daily

**Is this a regression?**
Was this feature working properly before? If so, when was the last time it worked the way you expected?

I believe so. I think it worked properly as recently as a week or two ago.

**Additional context / screenshots**
Add any other context about the problem here, including any screenshots.

Refreshing the page, changing / restarting the scenario, toggling variables in the scenario, and trying incognito mode do not resolve the issue.

Screenshot:
![image](https://user-images.githubusercontent.com/90077883/167270823-32e88fbf-2ba5-406b-9108-d6669fe5dc8c.png)

**Comment by neutrinonerd3333** [comment]
I think this is true for all regions (see #1426 and #1427)… but in any case, I don't think there's been any info as to why data updates have stopped recently.

**Comment by symphonymarie** [comment]
In LA at least, the county now only reports bi-weekly unfortunately.

**Comment by neutrinonerd3333** [comment]
Where I am (Santa Clara County, CA), it seems that data is still updated daily, or at least on weekdays. At a glance it seems like the same is true for LA? In any case, I would hope that the data update interval for every region isn't limited by a single region…

**Comment by apiology** [comment]
Running `update_prevalence.py` manually shows that it blows up trying to validate data from Canada - `https://api.opencovid.ca/other?stat=hr`

That URL is 404ing:

```sh
broz@bigbookpro:~/src/microCOVID$ wget https://api.opencovid.ca/other?stat=hr
--2022-05-14 09:50:32--  https://api.opencovid.ca/other?stat=hr
Resolving api.opencovid.ca (api.opencovid.ca)... 54.204.238.15, 54.221.251.148, 54.209.91.188, ...
Connecting to api.opencovid.ca (api.opencovid.ca)|54.204.238.15|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-14 09:50:32 ERROR 404: Not Found.

broz@bigbookpro:~/src/microCOVID$ 
```

It looks like the source is gone:

![image](https://user-images.githubusercontent.com/3681194/168428672-b060c1f0-ea8d-47c1-a7b6-76d4a5e6616a.png)

but now replaced with this?

https://github.com/ccodwg/CovidTimelineCanada

**Comment by apiology** [comment]
CC:ing @jy2wong, who if I'm reading git correctly, wrote the Canada API-parsing code here.

**Comment by apiology** [comment]
For a (completely unofficial!) partial update for places other than Canada, the [netlify preview](https://deploy-preview-1444--microcov.netlify.app/) that was built from https://github.com/microCOVID/microCOVID/pull/1444 might prove helpful.

**Comment by sjadler2004** [comment]
Hi folks, I also observed that the data is not updating for a number of major metros (SF, NYC, Seattle) even though the Johns Hopkins CSSE data continue to be updated in their repo. Is there a sense of when this may be fixed or what the issue may be? Thank you very very much for all your hard work on this tool!

**Comment by tceditor** [comment]
Data has also not updated in PA since April 30.

**Comment by apiology** [comment]
(Unofficial) news: The data parsing problem with Canada continues to block automatic updates.  A manual update that doesn't include county-level data for Canada was done two days ago: https://github.com/microCOVID/microCOVID/pull/1447

I have a proposal out with #1450 to make this workaround more automatic.  I'm also digging in to see what level of effort processing the new Canada county-level data format will take.

**Comment by apiology** [comment]
Automatic updates are running again now that #1450 is merged.  To get the county-level data back for Canada, I'm working on #1452.

**Comment by sameerjain0123** [comment]
Awesome, thanks!
