### ISSUE TITLE
Communicate uncertainty better

### ISSUE THREAD

**Issue by Radvendii** [microcovid/microcovid#144]
The disclaimer has "In this tool we state our best estimate based on available evidence, even when that evidence is not conclusive. ... There is still a lot of uncertainty about COVID. Do not rely on this tool for medical advice."

But IMO discussing the uncertainty just in a disclaimer seems easy to brush over. Also, the results are reported to one significant figure, which communicates (even if subliminally) that that is the degree of precision we have. Now, one issue is we can't just give error bars, because not only are we uncertain about the risk, we're uncertain about the level of uncertainty. Much of the data comes from other diseases or untested theoretical models, so I'm not sure how to communicate that effectively.

Two things that might help though:
- Discussing the sources of uncertainty somewhere where it'll actually be like to be read.
- Only reporting the result as an order of magnitude, or range. (this is already done next to the one-significant-figure result)

**Comment by tsyan** [comment]
I've directed this reader to https://www.microcovid.org/paper/all#uncertainty-estimation

**Comment by beshaya** [comment]
@Radvendii - not sure if I understand the ask here - it seems like you're saying "we need to make sure users understand uncertainty, but we can't expect them to read anything." Is that accurate?

**Comment by Radvendii** [comment]
Haha. Yes, essentially. Thanks for pointing that out.

Having read through the uncertainty methodology that I missed on the first read (thanks anna), I'm less concerned. But I still think people are boundless in their capacity to ignore nuance. I guess one option is simply to put the 3x or 10x conservative estimate as the result? 

As a presentation of a scientific model, that doesn't make much sense, but as a way of communicating with lay people about risk, that seems totally reasonable to me. To be clear, I'm not suggesting lying. What the number is and how it's calculated should be clearly explained, it's just a question of what the at-a-glance information someone gets from the website is.

Also, I don't know what the right answer is, it's just a suggestion.

**Comment by catherio** [comment]
Thanks for your thoughts. I don't suggest making additional changes right now. If we *very greatly overstate* the risk, then we could induce people to skip other things that are also absolutely public-health-bearing (elective surgeries, alcoholics anonymous meetings, social support around depression / mental health difficulties, lack of exercise due to staying at home, worsened heart health due to anxiety). I am happy erring slightly conservatively, but I don't want to add another order of magnitude out of thin air.
