### ISSUE TITLE
NJ data update

### ISSUE THREAD

**Issue by Adriene9** [microCOVID/microCOVID#1446]
**Describe the bug**
Seems like NJ data has not been updated since April. 30

Thank you for this useful risk calculator. 

**Additional context / screenshots**
Attached
![Screenshot_20220517-210845_Samsung Internet](https://user-images.githubusercontent.com/105770064/168963950-c4a20568-4ef4-4d58-8ab9-ddd3efe9235e.jpg)

**Comment by apiology** [comment]
I provided an unofficial workaround in https://github.com/microCOVID/microCOVID/issues/1436 you might find helpful.

**Comment by apiology** [comment]
Fixed by #1450 

You may continue to see various issues unrelated to #1450 - see:
* https://github.com/microCOVID/microCOVID/discussions/1626
