### ISSUE TITLE
Advanced method explanation incomplete

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#146]
In the whitepaper, under the advanced method, you give the formula: **Person Risk (Advanced) = Socializing + Errands + Work**

The text underneath has no mention of how "work" factors in. It doesn't appear to be in the Q&A either.

**Comment by auzigog** [comment]
As I read it again, it also seems like the article is just incomplete. It seems like it's leading into an explanation of how to use the spreadsheet. Or at least a link to do so.

**Comment by catherio** [comment]
Seems related to #39
