### ISSUE TITLE
Epistemic deep dive to get a number for "Not distancing" (cuddling, side-by-side on couch)

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#155]
We use "partner" for saliva exchange because we just don't have much other data, but people also just want to know about being very physically proximate (rather than conversational distance).

This will need to be an epistemic deep dive. I'm really not sure what we should suggest. This feels daunting to me right now, but it does seem highly requested.

**Comment by beshaya** [comment]
This is covered by [Chu et al](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31142-9/fulltext):

>Among the studies assessing physical distancing measures to prevent viral transmission, the intervention varied (eg, direct physical contact [0 m], 1 m, or 2 m).

I had a discussion with @oremanj  about this - the original release mapped those values to 3ft, 6ft, 10ft, but that's not what the paper says. There's also no particular reason to think that 10 ft is half as risky as 6 ft, especially indoors - Chu has no data at 3m and fit an exponential curve to 3 data points, which is sketchy af.

**Comment by jy2wong** [comment]
Kissing and close distances exist now.
