### ISSUE TITLE
Think about our version string or changelog strategy

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#162]
User feedback:
![image](https://user-images.githubusercontent.com/245037/91670887-809e9980-ead6-11ea-8786-131d13e94769.png)

Spreadsheet now has a change log.
What should we do for the website?

**Comment by blanchardjeremy** [comment]
@catherio what about adding a version string to the spreadsheet? Or I suppose the changelog serves as kind of version number. Where the date is the version.

**Comment by blanchardjeremy** [comment]
This exists now: https://www.microcovid.org/tracker
