### ISSUE TITLE
Exhalation filters are now available for 3M P100s

### ISSUE THREAD

**Issue by cvcalhoun** [microCOVID/microCOVID#1636]
The site (https://www.microcovid.org/blog/masks) currently says that it is necessary to tape a piece of surgical mask over the exhalation valve of a P100 to make it protect others. However, 3M now has a filter that can go over the exhalation valve of its P100s. That both avoids issues with having the tape come loose and makes the mask look more official (where masks are required) than an amateur tape job. Can the page be updated to reflect this? Here is a link to the exhalation valves. https://www.3m.com/3M/en_US/p/d/v101254496/

**Is your feature request related to a situation you're trying to understand with microCOVID? Please describe.**
A clear and concise description of the situation you're trying to understand by using microCOVID.

**Describe the solution you'd like**

**Additional context**

**Relevant Research or Citations**
If you have any data or studies that back this feature, please link them here. (If applicable)

**Comment by apiology** [comment]
Thanks, @cvcalhoun!

This would be a great first task for someone - some very basic GitHub and Markdown skills would be needed, but you shouldn't need to know TypeScript or Python.  Someone would need to clone this repo and edit this file, then open a pull request:

https://github.com/microCOVID/microCOVID/blob/b312c7fc5e6bfbc7f8c3cffe8f530d11a18e149e/src/posts/blog/6-masks/masks.ts

Style-wise, I think the only important thing to call out is that we'd want to at least acknowledge the change was made.  Perhaps there was an another edit in another blog post you could crib from on that?

**Comment by tquigg96** [comment]
I can work on this. What needs to be modified?

**Comment by apiology** [comment]
Thanks, @tquigg96!  Take a look at my comment above and let me know what questions you have.

**Comment by mariehuynh** [comment]
Does this still need to be taken care of?

**Comment by apiology** [comment]
@mariehuynh: Yep!

**Comment by bermannoah** [comment]
@apiology here's an attempt at a solution -- https://github.com/microCOVID/microCOVID/pull/1700 -- let me know if there's anything else I need to do?
