### ISSUE TITLE
Group notifications for daily prevalence run failures

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1658]
It would be good to get prevalence run failures to result in notifications that contributors can opt into somehow.

GitHub actions will send email notifications to the person who last turned the check in question on - which right now is me.

There's a ton of ways this could be solved.  Some parts available:
* I've got a subscription to https://deadmanssnitch.com/ we could potentially use.  Probably not great to have that tied to a random individual, but beats the status quo.  It supports email notifications (I can set up individuals).
* We've used Sentry in the past.  Perhaps that could be rigged up to handle various situations.
* We have a Slack instance I can onboard contributors onto.  Maybe that can be a target using integrations with the tools above, or integrate that with the Python script or with GitHub actions directly.

**Comment by shawnbiesan2** [comment]
For what it's worth I did reach out to sentry about their "Sentry for Open Source" to get details, but unclear if it will be any better than the free tier. Maybe that matters less if the warning-level logging is reduced. 

Not sure what timeline they tend to respond in so maybe DeadMansSnitch or a direct slack integration or something else might be better in the nearer term?

**Comment by apiology** [comment]
Thanks for digging in on that!  

I'd say there's no particular need to go down the Sentry route just for Sentry's sake, but if it gets us useful things or is the easiest way to accomplish key things like group notifications, great!  I've not used it personally, but I get the sense it does similar things as Airbrake, letting us track frequency of errors over time, with convenient integrations into tools like Slack. 

I'd also say there's no need for a potential rate limit to be a deal-killer, either - we could trim down the error logging [by search and replace](https://github.com/microCOVID/microCOVID/issues/1659#issuecomment-1335051177) before doing anything particularly fancy like the full idea in #1659.

BTW, sent you a Slack invite via email.  Let me know if other access is helpful as we go.

**Comment by shawnbiesan2** [comment]
Thank you! Just joined.

Yeah I don't personally have too much experience in what tools are out there. Any tool that solve the problem works for me.

**Comment by jaraco** [comment]
I’d like to help out. Can you add me to Slack? Email is my username at my username dot com. Thanks.

**Comment by apiology** [comment]
@jaraco: That's great!  Just sent the invite.  Be sure to check out the #sentry-firehose channel, which @shawnbiesan2 has set up to receive exceptions raised in the prevalence script; ping me on Slack and I can get you Sentry access if that is going to be useful - it does seem to have a [cron monitoring feature in beta](https://docs.sentry.io/product/crons/).

Feel free to reach out to me there or [grab some time on Zoom](https://calendly.com/apiology/microcovid).

**Comment by apiology** [comment]
Automated prevalence updates have been discontinued.
