### ISSUE TITLE
GitHub Actions prevalence-merge.yml fails periodically

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1677]
The 'Merge prevalence updates' GitHub action occasionally misses its cue and fails to merge the actual prevalence update PR.  It seems to have happened in the past:

* https://github.com/microCOVID/microCOVID/pull/1058
* https://github.com/microCOVID/microCOVID/pull/1265

But has happened more recently, more frequently I think. I've fixed up two of them, but here's an example of one that was never merged:

* https://github.com/microCOVID/microCOVID/pull/1660

I think this may potentially be related to adding a new mandatory check from https://about.codecov.io/

## Background

We have a few GitHub actions and other checks which are involved in daily prevalence updates:

* 'Prevalence'
  * https://github.com/microCOVID/microCOVID/blob/main/.github/workflows/prevalence.yml - Runs at 14:00 UTC and runs "yarn prevalence"
  * https://github.com/microCOVID/microCOVID/blob/main/package.json#L50 - 'yarn prevalence' runs 'scripts/prevalence_helper.sh
  * https://github.com/microCOVID/microCOVID/blob/main/scripts/prevalence_helper.sh
    * runs update_prevalence.py
    * Creates feature branch
    * Opens GitHub PR
* 'CI'
  * https://github.com/microCOVID/microCOVID/blob/main/.github/workflows/ci.yml - runs on every branch
  * After running tests, runs the uploader for codecov.io
* codecov.io
  * This is an external service that investigates code coverage output files and ensures any code changed on a PR has been tested.
* Netlify
  * Creates a version of the site for the feature branch that you can use for testing.
* 'Merge prevalence updates'
  * https://github.com/microCOVID/microCOVID/blob/main/.github/workflows/prevalence-merge.yml - runs on various PR event types ("labeled, unlabeled, opened, edited, reopened, synchronize") for prevalence updates and hits the virtual merge button on it.

As an aside, I noticed that adding a new label to the stuck prevalence PRs causes prevalence-merge.yml to notice it and merge it.

**Comment by apiology** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/3681194/205907387-4c69d47e-eb28-49bc-bc5d-c6fb092ef669.png">

GitHub (now?) has an auto-merge button.  Wonder if we could skip the 'Merge prevalence updates' thing entirely by teaching prevalence_helper.sh to press it...

**Comment by deraffe** [comment]
It looks to me as if https://github.com/microCOVID/microCOVID/blob/01cf9613adc5cc4a13cc163fef7ebcdcfccc7d7c/scripts/prevalence_helper.sh#L118 would already automerge the PR, if the `AUTOMERGE` variable is set to `1`. This would obsolete the separate automerge action.

**Comment by apiology** [comment]
@blanchardjeremy: I wonder why https://github.com/microCOVID/microCOVID/pull/1067 both added this code and also turned it off by default.

@deraffe: Barring an answer on that, seems worth trying.  Maybe whatever reason is overcome by events.

**Comment by apiology** [comment]
Another failure: https://github.com/microCOVID/microCOVID/pull/1717
