### ISSUE TITLE
Create fail-safe mode for calculator 

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1703]
The validity of microCOVID's model, the viability of its data pipeline, and the resulting accuracy of its prevalence numbers are an expiring asset.  This is a dangerous situation as contributions to the project come and go.

That said, the relative effect of MODing have been less affected by time.  It's still useful to figure out the effect on risk of attending with a good mask, or seeing moving it outside.

I wonder if we could have the site detect when either the model or the prevalence numbers haven't been updated in X amount of time and push users into a mode that offers just that relative risk calculation.  

Perhaps in this mode we could baseline the risk on some common scenario?  I'm not quite sure how to best express this part without even the loose precision that the microCOVID unit was invented to express.

Part of this mode could also be useful when a user's location does not offer useful prevalence numbers...

**Comment by jaraco** [comment]
This effort was superseded by the manual mode implemented in #1826.
