### ISSUE TITLE
Better UX when prevalence data is stale

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1707]
We should more strongly encourage folks to enter their own prevalence data when automated prevalence data is stale (either overall or just for their location).

Note that I added a warning dialog to suggest folks do this when prevalence is stale - but I wasn't able to easily disable the automatic prevalence entry in this circumstance, meaning the inaccurate microCOVID number still appears by default.  Ideally the user would need to enter their local prevalence numbers before continuing:

![image](https://user-images.githubusercontent.com/3681194/208924509-aa00b8f3-0614-4a83-8329-b9a34f4410f5.png)

This would partially address #1703

**Comment by shawnbiesan2** [comment]
Just so I better understand the ask, when I select a country like Nigeria where this message is displayed 

I would expect
- "Override location-based data" to be checked by default (showing the prevalence data fields)
- Prevalence fields to be defaulted to some value(s) that indicate they should be filled in by the user (0, null, whatever). I believe 0s currently block "Describe the scenario"

Also by prevalence fields I assume we mean "Reported cases in past week", "Percent increase in cases from last week to this week", and "Percent of tests that come back positive".

I would expect even though the prevalence is outdated the "Total Population" and "Percent population fully vaccinated" to still be trusted.

**Comment by apiology** [comment]
> Just so I better understand the ask, when I select [...]

I think that would be a reasonable solution, yeah.  I'm sure there are others.

> Also by prevalence fields I assume we mean "Reported cases in past week", "Percent increase in cases from last week to this week", and "Percent of tests that come back positive".

Yep!  The three are used together to calculate local prevalence.

> I would expect even though the prevalence is outdated the "Total Population" and "Percent population fully vaccinated" to still be trusted.

That's right.
