### ISSUE TITLE
Validation procedure for code/model changes

### ISSUE THREAD

**Issue by apiology** [microCOVID/microCOVID#1708]
From https://github.com/microCOVID/microCOVID/discussions/1626:

> A validation procedure will also be very helpful, to characterize the impact of changes made by folks like me who didn’t write the original code and model. I don’t know exactly what this looks like yet, but something pragmatic we can build on is better than nothing.

Perhaps a few key location+scenarios for microCOVIDs could be evaluated before and after and shown to the developer?

**Comment by zack112358** [comment]
Can't assign it to myself, but I *am* working on this one starting Monday.

**Comment by zack112358** [comment]
fixed in #1772
