### ISSUE TITLE
Resource Sources: Broken Image

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#175]
![image](https://user-images.githubusercontent.com/32290/91682188-9081a200-eb05-11ea-96f4-c141832e6ca4.png)

Broken image.

https://github.com/microcovid/microcovid/blob/45fe2c65828af3e1438e7768bb7076677fe86b42/src/paper/14-research-sources.ts#L94

**Comment by catherio** [comment]
hm @beshaya  seems we have had a regression on this one!

**Comment by beshaya** [comment]
Hm, shows up just fine on a local build.

**Comment by blanchardjeremy** [comment]
All the other images on the page are URLs to an image. 

This one is a data URI

![image](https://user-images.githubusercontent.com/32290/92782434-d1758400-f359-11ea-88b5-822a71eacf4a.png)

Not sure why it's different, but that seems like part of the issue.

**Comment by blanchardjeremy** [comment]
Just checked it in Safari and it works fine. Hmmm...

Is anyone else having this problem in Chrome? I have it even on a blank chrome profile.

**Comment by blanchardjeremy** [comment]
I looked into this more and this is the error I see in the console.

```
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAA...ggg==' because it violates the following Content Security Policy directive: "img-src *".
```

I see this for any images that are included by data URI. I know it's not happening for everyone using Chrome. I wonder if it is happening to some folks, though.

@beshaya  - Any idea how we might change the content security policy?

**Comment by blanchardjeremy** [comment]
We just got another report of this bug on android. So it's not just me.

![image](https://user-images.githubusercontent.com/32290/97829198-2361c880-1c7e-11eb-9195-133ce814355d.png)
![image](https://user-images.githubusercontent.com/32290/97829202-26f54f80-1c7e-11eb-90dc-473584f69631.png)


If you look closely, you can see that the menu "3 bars" icon in the top right is not rendering. Which is the same behavior I get on my machine. 

I think this can be resolved with a content security policy.
