### ISSUE TITLE
Invisible population box can invisibly inherit a saved value instead of 100,000

### ISSUE THREAD

**Issue by octern** [microCOVID/microCOVID#1823]
**Describe the bug**
A user sent me this link, which generates excessively low prevalence numbers. 

https://www.microcovid.org/?distance=close&duration=45&interaction=oneTime&personCount=3&riskProfile=average&scenarioName=custom&setting=indoor&theirMask=none&topLocation=US_06&useManualEntry=0&voice=normal&yourMask=n95Sealed&yourVaccineDoses=3&yourVaccineType=pfizer

I believe the problem is that when useManualEntry is explicitly set to zero it overrides our population default of 100,000 and instead uses the value from the last location lookup. In this case it's California, meaning that it's invisibly using a denominator of 39m instead of 100k. 

This is the URL that the calculator automatically generates based on saved values if she types in microcovid.org (it's not just a saved URL in her browser), so this problem might affect many users. 

**Link to microCOVID scenario**
If applicable, please copy-paste the URL to the scenario that you modeled on the calculator, so we can easily reproduce it.

https://www.microcovid.org/?distance=close&duration=45&interaction=oneTime&personCount=3&riskProfile=average&scenarioName=custom&setting=indoor&theirMask=none&topLocation=US_06&useManualEntry=0&voice=normal&yourMask=n95Sealed&yourVaccineDoses=3&yourVaccineType=pfizer

**To Reproduce**
The URL above reproduces the problem. I don't know how to replicate useManualEntry being set explicitly to zero -- when I play with an old version of the site and turn it off the manual override checkbox the parameter is just removed from the URL. But clearly it turns on for some people. 

**Expected behavior**
Entering 70 for cases/100k should generate a reported prevalence of .07%. Instead it generates one hundreds of times lower than that. 

**Additional context / screenshots**
Add any other context about the problem here, including any screenshots.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1575692/225201478-82022f35-9e8d-4dd7-a37c-a0727d7fedf1.png">

**Comment by jaraco** [comment]
#1822 is implicated and we'll roll that back.
