### ISSUE TITLE
Spreadsheet activity log: Discrepancy between total risk calculation and individual activities

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#187]
![image](https://user-images.githubusercontent.com/32290/91771691-41388180-eb98-11ea-80e1-0917f1ec791e.png)

It seems like the total should be 1100, yeah? 

I'm not sure what the extra rounding is for in column A. But it provides an odd user experience to see two activities that total 1100 and then see 1300 in the top row as my total. Seems like they should be consistent. (Or am I missing something?)

**Comment by catherio** [comment]
oooh, I bet this is because of rounding to one sig fig.

**Comment by blanchardjeremy** [comment]
Yep. Column B (hidden) has the exact numbers (un-rounded). And that's where the total draws from.

**Comment by blanchardjeremy** [comment]
Resolved. Removed sig fig rounding for the time being.
