### ISSUE TITLE
Users are very confused about how cuddling with their spouse could be high risk

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#190]
![image](https://user-images.githubusercontent.com/245037/91776618-95e0fa00-eba2-11ea-8945-439536c4936a.png)

Not sure what to do about this. Your risk from someone depends on that person's behaviors in the past 10 days, not on your relationship status with them. But people have been told seeing people in their own household is extremely safe. I don't really know how we want to clarify this or what the users' mental model is.

see also #173

**Comment by catherio** [comment]
and in general I think people are not using "partner" to represent "hoookup with stranger". I think we do need to provide a better "hookup with stranger" option.

**Comment by beshaya** [comment]
We could split the scenario into "Intimate with a random person in your city" and "Intimate with a partner with whom you live and socialize exclusively" to set it on the other end of the spectrum.

We seem to not be the only ones struggling here - covidcanidoit lists kissing a live-in partner as a moderate risk https://covidcanidoit.com/US/ca/activity/kissing-live-in-partner and watching a movie with a live-in partner as a high risk https://covidcanidoit.com/US/ca/activity/see-a-movie-with-live-in-partner.

**Comment by beshaya** [comment]
I think I'd fix this as follows:

Interaction type -> Frequency:
* One time - something you do once. 6% per hour
* Housemate / repeating - something you do regularly. 30% flat rate.
- Partner / Spouse - Remove from this list! It doesn't describe a frequency

Distance:
* 10 ft
* 6 ft
* 3 ft
* touching mouths - We don't know *why* spouses have higher transmission rates, but *all* possible transmission modes (large droplets, aerosols, fomites) are maximized if you make out. Use the partner transmission rate regardless of duration.
