### ISSUE TITLE
 No ability to share custom scenarios?

### ISSUE THREAD

**Issue by Gregz3** [microcovid/microcovid#193]
This is an excellent tool, but it would be very useful to have the ability to share a specific scenario with others.

There should be a button for creating an encoded URL with the proper metadata, or even better, the URL should change automatically after a successful calculation.

The user should have the ability to create a custom scenario, and then generate a URL that contains all of the information needed to regenerate that scenario. It might look something like this:

https://www.microcovid.org/calculator/Ui2ASa29

**Comment by catherio** [comment]
very cool idea, I like thsi

**Comment by doctordobes** [comment]
Got another request ,this time from a One Medical provider (Desmond Watts) to be able to share results. Agree that a shareable link would be a useful way to accomplish this.
