### ISSUE TITLE
Add 1% adherent person type

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#196]
Our person offerings are:

Average, Frontline, non-frontline, isolated (various flavors) and arbitrary social interractions. 

This basically means there are people it's totally safe to interract with (closed pods), but interractions with them would remove that status and people who it's never safe to interract with indoors (everyone else).

I also think we should remove or retool the "N housemates who socialize" because they are within a few % of average.

**Comment by mattbell** [comment]
This specific scenario came up at Kal and we added it to our spreadsheet.
