### ISSUE TITLE
[Calculator] Some locations are listed as having negative reported cases

### ISSUE THREAD

**Issue by duncangeere** [microcovid/microcovid#197]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/11523915/91879312-44a73800-ec80-11ea-83a5-12ca7c8630bf.png">

This breaks the calculator, preventing it from calculating any risk.

**Comment by blanchardjeremy** [comment]
@oremanj - This doesn't seem hugely urgent. But maybe next time you're in the python file you can add a couple of lines to resolve this and force negative results back to zero.

**Comment by jy2wong** [comment]
```
        if (self.cases_last_week < 0):                                          
            raise ValueError(f'Cases for {self.name} is {self.cases_last_week}')
```

fixed by having update_prevalence.py error out if reported cases would be negative
