### ISSUE TITLE
Link directly to scenarios (for sharing)

### ISSUE THREAD

**Issue by gwynm** [microcovid/microcovid#203]
I'd love to be able to link directly to a custom scenario. 

My use case here is explaining my reasoning for participating (or not participating) in activity X - I can just link directly to the calculator by messaging back with eg "Sure, this is inside my risk tolerance: https://microcovid.org/c/df7463c9-1707-495f-8709-9881b6e01bdc".

In fact, just putting all the scenario params in the URL would work here and would mean it could continue to be 100% client-side.

**Comment by catherio** [comment]
thanks, it's on our roadmap! (#193)
