### ISSUE TITLE
Compare total risk to risk budget

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#204]
![image](https://user-images.githubusercontent.com/5877421/92034581-4c1f1d80-ed22-11ea-8497-40f2d0ecbecd.png)

Users are confused by small numbers. Help them compare to the weekly risk budget, but *don't* use "afford" terminology.

**Comment by blanchardjeremy** [comment]
Question on this: maybe I'm misunderstanding the intent, but it seems like the calculation is off: 

![image](https://user-images.githubusercontent.com/32290/92261831-00d64d80-ee8f-11ea-9c7d-b9018a3b452a.png)


By my math 

`30/(10000/52) = 15.6%` 

Curious why the screenshot shows 20%

**Comment by beshaya** [comment]
We only show 1 sigfig across the site.
