### ISSUE TITLE
[Spreadsheet] Erroneous exclusion of ongoing relationships

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#208]
In the spreadsheet, if I enter an activity and mark it as partner or housemate, my intuition says what belongs in the date field is the last time I saw them, which is usually today. But the SUMIFS formula excludes everything from the last two days. I suggest replacing the formula in [`"Activity Log"!D1`](https://docs.google.com/spreadsheets/d/1DYIJgjG3H5rwt52NT2TX_m429snmIU-jGw1a8ZODwGQ/edit#gid=922024072&range=D1) with this: 

    =SUMIFS($B3:$B, $I3:$I, "One-time", $D3:$D, "<="&(TODAY()-2), $D3:$D, ">"&(TODAY()-9)) + SUMIFS($B3:$B, $I3:$I, "<>One-time", $D3:$D, ">"&(TODAY()-9))

P.S. I love this project. If you give me (linesarefuzzy@gmail.com) comment access to the spreadsheet, I'll probably make more suggestions!

**Comment by linesarefuzzy** [comment]
In the spreadsheet, if I enter an activity and mark it as partner or housemate, my intuition says what belongs in the date field is the last time I saw them, which is usually today. But the SUMIFS formula excludes everything from the last two days. I suggest replacing the formula in [`"Activity Log"!D1`](https://docs.google.com/spreadsheets/d/1DYIJgjG3H5rwt52NT2TX_m429snmIU-jGw1a8ZODwGQ/edit#gid=922024072&range=D1) with this: 

    =SUMIFS($B3:$B, $I3:$I, "One-time", $D3:$D, "<="&(TODAY()-2), $D3:$D, ">"&(TODAY()-9)) + SUMIFS($B3:$B, $I3:$I, "<>One-time", $D3:$D, ">"&(TODAY()-9))

P.S. I love this project. If you give me (linesarefuzzy@gmail.com) comment access to the spreadsheet, I'll probably make more suggestions!

**Comment by beshaya** [comment]
You need to re-enter them once per week every week you are together! We make no assumptions about whether or not you and your partner stay together :'(

Alternatively, if your housemate/partner is accounting as well, then you probably want to add a sheet for them and link the two so that you get 30% or 48% of their instantaneous points.

**Comment by catherio** [comment]
Also just want to say yay thanks for your enthusiasm :) Our preference is to keep making suggestions here in the issues tracker so we can keep fine-grained track of the status of any changes, but please do keep them coming!

**Comment by linesarefuzzy** [comment]
> You need to re-enter them once per week every week you are together! We make no assumptions about whether or not you and your partner stay together :'(

Yes, I agree that if the date is more than 9 days ago they should be excluded. My point is that if I enter the date as *today,* they are also excluded! My corrected formula simply removes the 2-day *lower bound* on interactions when they are marked as ongoing.

**Comment by beshaya** [comment]
Ah yeah... I think this might be an error in translation from the internal spreadsheet to the public one - interactions 2-9 days ago is your risk to others while 0-7 days is risk to self.

**Comment by blanchardjeremy** [comment]
My proposed solution to this: If someone doesn't enter a date, automatically count that against their score (in both the 0-7 day total and the 2-9 total). That way I can easily say "I do this every week"

@catherio, @beshaya  - thoughts?

**Comment by beshaya** [comment]
This seems better than the status quo to me!

**Comment by linesarefuzzy** [comment]
Hi, just want to bump this and note that I offered a solution in my original post: changing the formula in `Activity Log!C1` to this (now updated for shifted columns): 

    =SUMIFS($A3:$A, $H3:$H, "One-time", $C3:$C, "<="&(TODAY()-2), $C3:$C, ">"&(TODAY()-9)) + SUMIFS($A3:$A, $H3:$H, "<>One-time", $C3:$C, ">"&(TODAY()-9))

Sad to see that two months later, it still hasn't been adopted, which doesn't give me much encouragement to keep contributing. 😟

**Comment by beshaya** [comment]
Ah, sorry, I think I misunderstood - you want an ongoing interaction entered as "today" to show up in your "risk to others." I see why you'd want this, since starting up with the sheet you'd expect new entries to affect the score. On the other hand, if you just moved in with a person, it would be incorrect to modify your risk to others score until 2 days later.

@blanchardjeremy - I think you doing something with this, any updates?

**Comment by linesarefuzzy** [comment]
After working with it a bit more, I think I might agree that it's simpler to just use a blank date for an ongoing relationship. Here's a formula for that: 

    =SUMIFS($A3:$A, $C3:$C, "") + SUMIFS($A3:$A, $C3:$C, "<="&(TODAY()-2), $C3:$C, ">"&(TODAY()-14))

I also changed the "Date" column header to say "Date (blank for ongoing)". 

Somewhat relatedly, I think the "symptom-free now" column is confusing, and should probably say "symptom-free after 2 days" or something like that. But it should actually probably be a factor that varies by # of days since contact.

**Comment by beshaya** [comment]
Yeah, I think Jeremy added that on the master sheet.

"symptom-free now" is for the day you hang out. "will report symptoms" is
for after. You can't budget based on future observations! If they develop
symptoms after you hang out, you need to adjust your priors and assume they
were contagious when you had contact.

The even more accurate version is - when your contact's points "expire" 10
days after they accrued them, they expire for you as well (so if your
contact got 60 microcovids 9 days before they hung out with you and they
are still not showing symptoms 2 days later, your points from that
interaction drop to 0.

This is, of course, a simplification that assumes asymptomatic individuals
are not very contagious.

**Comment by blanchardjeremy** [comment]
@linesarefuzzy Thanks for reaching out. Apologies for not getting back to you sooner! We're definitely interested in your contributions. We've been hard at work with v2 of the UI and just now coming up for air to consider other aspects of the project, including the spreadsheet.

Thanks for reminding me that the "blank date = always count it" feature isn't in the public spreadsheet. It is in the version I've made for my house. (I'm integrating the changes I've made for our house one-by-one to the public spreadsheet).

I just integrated your suggested formula adjustment added to the activity log sheet. Thanks! ✅

**Comment by linesarefuzzy** [comment]
> Yeah, I think Jeremy added that on the master sheet. "symptom-free now" is for the day you hang out. "will report symptoms" is for after. 

The public spreadsheet doesn't have a "will report symptoms" checkbox. What does it do?

**Comment by blanchardjeremy** [comment]
@linesarefuzzy Ibasho made a personal choice to add it. It reduced the "Risk to others" score by 50% (doesn't reduce your risk at all). They didn't feel like they had enough data to publish it as an option on the public spreadsheet. The thinking behind it is "even if you did get exposed to someone, as long as they notify you that they got symptoms, you could isolate from your housemates/podmates/friends as soon as they tell you, and that would reduce the chance that. you give it to those people."
