### ISSUE TITLE
[Blog] Add thank you to essential workers in Intermediate Risk

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#21]
I experience some dissonance reading that healthcare workers are 3x regional, or 8000µCoV in our area, while Sarah's workweek costs 9µCoV.

Since the calculator doesn't support rated PPE, it's not even possible for others to calculate out what their frontline workers risks are.

Perhaps this needs some messaging around "Basic/Intermediate are for people you can't or don't want to have detailed risk discussions with"

**Comment by jy2wong** [comment]
I think this is obsolete?
