### ISSUE TITLE
[Spreadsheet] Activity risk > 100%

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#210]
![image](https://user-images.githubusercontent.com/1829213/92039176-a203bd80-ed42-11ea-8498-73dee9c7a85b.png)

How about capping the activity risk at the "Partner" level?

**Comment by catherio** [comment]
Ah, yes, good catch - that's what we do on our house internal spreadsheet! Or the "housemate" level if not cuddling. We do something similar to this in the calculator.
