### ISSUE TITLE
Possible error in risk budget per week %

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#220]
![image](https://user-images.githubusercontent.com/32290/92262656-54956680-ee90-11ea-8c9f-b9ec986bc57e.png)

Possible error regarding #204 

Question on this: maybe I'm misunderstanding the intent, but it seems like the calculation is off:

By my math

`30/(10000/50) = 15%`

Curious why the screenshot shows 20%

Is this intentional or a bug?

**Comment by beshaya** [comment]
Our results are all rounded to one significant figure to reflect our confidence levels.

**Comment by catherio** [comment]
Mm, I think adding a tilde would be clearer: https://github.com/microcovid/microcovid/pull/222

**Comment by blanchardjeremy** [comment]
@catherio I don't see a tilde anywhere in #222 but maybe I'm missing it.

**Comment by blanchardjeremy** [comment]
Looks like #222 is now fixed.
