### ISSUE TITLE
Modeling a household confused me

### ISSUE THREAD

**Issue by Nadrieril** [microcovid/microcovid#223]
Assume I live in a household of 5 people, and we all decide to keep our risk at 200 uCovid per week. Using your algorithm, from my housemates alone I get an exposure of 4 * 200 * 30% = 240, which already eats all of my weekly budget! By the same calculation, I reevaluate the risk of each individual housemate to at least 240, which in turn gives me even more exposure. This calculation clearly diverges :(
So the model fails here. If I try to calculate my risk based on actual interactions, I do get a much lower number, but I would be neglecting the risk from shared spaces.
Do you know of a better model for this?

**Comment by Nadrieril** [comment]
Ah wait I understand my mistake. The way I'm doing it would diverge even for two people because I'm counting the risk of me infecting myself via them. And in fact as you mention in the Q&A I can neglect entirely the effect of one of my roommates infecting another when evaluating the risk to myself.
The right way to approach this is to say: if we each get x risk per week _from outside the household_, then I get exposed to a total of x + 4 * x * 30% per week. If my limit is 200, this means we're each allowed x=90, which seems quite reasonable.
Might this calculation deserve an entry in the Q&A? I might not be the only one to get confused

**Comment by blanchardjeremy** [comment]
I think that's right. I asked @catherio to help me make sense of this.  I ended up adding it to the spreadsheet like so:

![image](https://user-images.githubusercontent.com/32290/92296962-24c97b80-eeef-11ea-8107-6e45def4c2d5.png)

**Comment by Nadrieril** [comment]
Nice, that's exactly what I needed! That solves the issue for me thank you.
Also thanks for making this awesome tool, it has helped me a lot feel less confused and make better decisions

**Comment by autumnsault** [comment]
I'd actually propose re-opening this.

I've been using the spreadsheet since before it was released, and faithfully updating to the new version. I found it quite challenging entering household risk in the latest version. I worry that if someone were new to the spreadsheet they might actually just skip the household risk component and end up taking far more risk than they realize they're taking.

The web form is not particularly helpful here either. If I enter my 8 podmates, web form tells me it's ~500 microcovids per week just from my 1% household.

My suggestion is that there be an example of some sort for modeling household risk inside of the spreadsheet.

**Comment by blanchardjeremy** [comment]
@autumnsault Thanks for reaching out on this. I'm our point person for the spreadseheet. We're in the early stages of looking at possibly moving the spreadsheet over to a "pod/house based" approach. We're looking for test users to help us review the documentation. Would you be interested in helping with that? If so, please let me know!

**Comment by me-and** [comment]
@blanchardjeremy Having now discovered this project, I'm certainly happy to volunteer to help with that!

**Comment by blanchardjeremy** [comment]
@me-and Wonderful. Could you fill out this volunteer form: https://docs.google.com/forms/d/e/1FAIpQLSeF1r6pHvWyIrZ_quJNzChGOOdjdunVAjrcbqj_xbEUbnMTsA/viewform

Thanks!

**Comment by autumnsault** [comment]
Yes! I'll fill out the form. Thanks!

**Comment by blanchardjeremy** [comment]
@me-and and @autumnsault thanks for filling out the form. Sometime in the next week or so I'll get back to you about testing and feedback next steps!!

**Comment by blanchardjeremy** [comment]
Also, for reference, #322 and #323 are the issues that are in play that will resolve this original issue.
