### ISSUE TITLE
Create a blurb for Facebook

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#226]
![image](https://user-images.githubusercontent.com/245037/92322093-0c875880-efe4-11ea-94cb-fbd8f61d8e84.png)

(Public post, so not cropping out the commenters' names/faces)

**Comment by beshaya** [comment]
https://neilpatel.com/blog/open-graph-meta-tags/#:~:text=og%3Adescription,won't%20affect%20your%20SEO.

**Comment by blanchardjeremy** [comment]
@beshaya are you saying with that link that it's not needed because it won't effect SEO or were you just dropping that link there for reference for future implementation?

**Comment by beshaya** [comment]
That's for reference for myself.
