### ISSUE TITLE
County data not updating

### ISSUE THREAD

**Issue by aimeewetknee** [microcovid/microcovid#227]
I tried a couple of different browsers in case the information was just cached. But no matter how many times I reload the page, I still see "Data last updated August 28, 2020." Our county has been spiking as many others' have and it would be great not to have to calculate the county info by hand. Is this supposed to update automatically? Or am I just doing it wrong?

**Comment by oremanj** [comment]
We have to do it manually and we got behind. :-) It will normally update about once a week. I've posted a PR to update the data now, which someone will hopefully be able to review soon.

**Comment by aimeewetknee** [comment]
Thank you so much for all of your hard work!

**Comment by aimeewetknee** [comment]
Thank you so much for all of your hard work!

**Comment by aimeewetknee** [comment]
Thank you so much for all of your hard work!
