### ISSUE TITLE
Make relative risk visible when modifying inputs

### ISSUE THREAD

**Issue by zacksulsky** [microcovid/microcovid#229]
When modifying inputs in the calculator, it would be useful to see the relative risk of each option in the dropdown during editing. This will save time and help make the logic behind the calculator more intuitive to users over time as they make more calculations.

At a minimum, it would be useful to sort options form lowest risk to highest risk and specifying this. Ex:

Surgical mask or mask with PM2.5 filter insert (lowest risk)
Cotton mask, bandanna, or buff
No mask (highest risk)

At best, it would be useful to see something like the following This would especially be helpful for cases where the relative risk may not be obvious. Ex:

Surgical mask or mask with PM2.5 filter insert (currently selected)
Cotton mask, bandanna, or buff (same risk)
No mask (5x riskier)

Long term, it may be worth considering replacing the dropdowns with sliders or another component that helps visualize relative positions on the risk spectrum.

**Comment by mattbell** [comment]
I think there are versions of this that could be really easy to implement.

Simplest version: Text is fixed.  There's a default option that's always the "baseline" number, and the others are all relative to that.  Eg:

Indoors (default risk)
Outdoors (0.5x risk)

More complicated version: Text is altered based on current selection.  Eg:

Indoors (selected)
Outdoors (0.5x risk)

would switch to 

Indoors (20x risk)
Outdoors (selected)

---

In either case we'd want to keep the parenthetical add-ons relatively short to reduce visual clutter.
