### ISSUE TITLE
Centrally manage prevalance data with importrange

### ISSUE THREAD

**Issue by kimberlyd17** [microcovid/microcovid#231]
For the 3 COVID prevalence numbers that are noted as "FILL IN HERE (and update this frequently)", they could be kept updated for the Bay Area (or multiple areas) across all users of copies of the sheet with only 1 person regularly making updates. The way to do this would be:
- Create a reference tab of the master spreadsheet that will have up to date information
- In the tab that currently exists, change from hard-coded numbers to =IMPORTRANGE("https://docs.google.com/spreadsheets/d/1DYIJgjG3H5rwt52NT2TX_m429snmIU-jGw1a8ZODwGQ/edit#gid=601829656","SHEETNAME!A1")  (update values of SHEETNAME and A1 appropriately)
- Optionally, also add a cell indicating the last updated date, so that users could see the latest data and how fresh it was within the sheet, without having to retrieve it themselves.

To be clear, the affected section is:
Sheet: [File > Make a copy] microCOVID spreadsheet
Tab: PERSON_RISK_FACTS
Cells: F4, F7, F10

**Comment by echurilov** [comment]
I made [a version](https://docs.google.com/spreadsheets/d/1p_x-EH3uAeLHdKUs05uWIMIUFigZ5ROjt2U0rhKPhms/edit?usp=sharing) of the microCOVID spreadsheet that uses the IMPORTDATA function to update itself with NYT case data for all Bay Area counties.

**Comment by blanchardjeremy** [comment]
Closing in favor of #274
