### ISSUE TITLE
Spreadsheet: Add visual (emoji) key to spreadsheet to compare types of activities at a glance

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#232]
![image](https://user-images.githubusercontent.com/32290/92434751-80953e00-f155-11ea-9576-7e6b20c0857a.png)

I modified the spreadsheet to automatically generate an emoji-based key to help remind me if it was indoors/outdoors, masked/not, the distance, and the time. 

I find it easier to parse at a glance. Because anytime I'm reading your key or even re-reading custom scenarios that I made, I have to scroll to the right to remember the "settings"

Here's the formula: 
```
=IFS(
J3="One-time", (IFS(
  N3="Indoor", "🏠", N3="Outdoor", "🌲")&
  IF(P3="No mask", "💨", "😷")&
  IFS(
    Q3="> 6ft most of the time", "↔️", 
    Q3="Not distancing", "☕", 
    Q3="Cuddling", "❣️", 
    Q3="> 10ft most of the time","🏈"
  )&
  " ("&IF(K3, K3&"h", )&IF(L3, L3&"m", )&")"
),
J3="Housemate/repeated","👋👋👋",
J3="Partner", "💋💋💋",
ISBLANK(J3), ""
)
```

(If anyone has a better emoji suggestion other than 🏈  for "10+ feet distance", please let me know)

Note: I intentionally only represented the other person's mask since it has a bigger effect on the score.

You could also consider doing something like this to add more visual cues to the app.

**Comment by beshaya** [comment]
This is amazing and adorable!

**Comment by blanchardjeremy** [comment]
Latest variation: 
![image](https://user-images.githubusercontent.com/32290/95544458-fdfbda80-09af-11eb-9422-cfa7ccb51b5b.png)
