### ISSUE TITLE
Resource intake: Look at this airplane/flying numbers

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#234]
https://edition.cnn.com/travel/article/odds-catching-covid-19-flight-wellness-scn/index.html (talks about Barnett et al https://www.medrxiv.org/content/10.1101/2020.07.02.20143826v3)

Edit: Barnett at all is just an estimation using roughly the same methodology as us. It contains no new primary source data about airplanes.

**Comment by catherio** [comment]
https://vitaminz.substack.com/p/how-i-calculated-the-health-cost-ae3

**Comment by catherio** [comment]
![image](https://user-images.githubusercontent.com/245037/93273721-65d25300-f76d-11ea-894a-88677e2072c9.png)


our plane numbers are too high probably

**Comment by catherio** [comment]
https://t.co/KMPRQd7WGa?amp=1

**Comment by catherio** [comment]
Also: https://mobile.twitter.com/amymaxmen/status/1320811661717131264

**Comment by catherio** [comment]
https://www.ustranscom.mil/cmd/panewsreader.cfm?ID=C0EC1D60-CB57-C6ED-90DEDA305CE7459D&yr=2020

**Comment by catherio** [comment]
https://npli.sph.harvard.edu/crisis-research/aviation-public-health-initiative-aphi/

**Comment by blanchardjeremy** [comment]
From Sarah:

> @here some folks at One Medical posted this very interesting looking, comprehensive (long) document about plane travel from US Transportation Command - thought this might be useful for our model https://www.ustranscom.mil/cmd/docs/TRANSCOM%20Report%20Final.pdf

**Comment by beshaya** [comment]
From this last one:

The top level result is fairly misleading:
> Results from the Boeing 777-200 and 767-300 airframes showed a minimum reduction of 99.7% of 1 µm
simulated virus aerosol from the index source to passengers seated directly next to the source. An
average 99.99% reduction was measured for the 40+ breathing zones tested in each section of both
airframes. 

This is basically saying that sitting next to a person is .03% as bad as directly breathing their exhaled air. The more useful result for us is the comparison with a house:
![image](https://user-images.githubusercontent.com/5877421/99017959-df888200-250d-11eb-8572-72eeb998b2c7.png)
Which shows that the improved ventilation on an airplane results in ~10x fewer inhaled particles than in a house.

The team tested two airframes in several zones:
> The process provided a real-time method for mapping tracer particle concentration for passenger
breathing zones in four sections of the 777-200 and three sections for the smaller 767-300. Over 300
aerosol releases were performed in eight days. Testing for each airframe included terminal loading and
unloading simulations, simulated inflight conditions in a hangar (with more seats and replicates then are
possible during inflight testing), and then two days of inflight testing at altitude (~35000 ft). 

* Team used florescent particles with sensors in all the seats surrounding the breathing simulator
![image](https://user-images.githubusercontent.com/5877421/99016545-3a20de80-250c-11eb-866a-e7a0ee50eb9f.png)


Useful side notes:
> Santarpia, et al. (2020), using Sartorius gel filtration collectors found maximum evidence of viral
shedding for a normal (non-nasal cannula ventilated) patient was 8.339 genomic copies of virus per liter
of air. 

> The range in literature estimates varies from 300 to several thousand infectious virus to cause
an infection (Basu, 2020; Schröder, 2020). 

Standard adult respiration:
> 0.5 L per breath and respiration rate of 15 breaths per minute.
