### ISSUE TITLE
Specify that saved scenarios preserve historical data and add Update button

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#237]
It seems when I select a saved scenario, it repopulates the fields with the data from the time the scenario was saved. This is good, but I think there should be a notice that makes that clear, and also a button to update the data to see what the same scenario would score today.

**Comment by jy2wong** [comment]
I think this is fixed now; if prevalence info (location-based data on the calculator) hasn't been overridden, it will get replaced with the latest prevalence data (both for local storage scenarios and URL scenarios)
