### ISSUE TITLE
[website] Put the calculator on the home page

### ISSUE THREAD

**Issue by orborde** [microcovid/microcovid#239]
Right now, the https://microcovid.org homepage contains a bunch of text describing the project, and a tiny link to the calculator buried in that text in the middle of the page (and another link in the menu at the top).

**The most important feature of this website is the calculator.** It should be as prominent as possible - ideally it should be the first thing a user sees when they visit https://microcovid.org . Failing that, an obnoxiously huge, visible, brightly colored "CALCULATE" button near the top of the page.

**Comment by blanchardjeremy** [comment]
That makes a lot of sense to me.

**Comment by beshaya** [comment]
++

**Comment by blanchardjeremy** [comment]
@beshaya Thanks!
