### ISSUE TITLE
Add n95/p100 masks as selectable options in Mask dropdowns

### ISSUE THREAD

**Issue by adrianrcoyne** [microcovid/microcovid#243]

**Comment by mattbell** [comment]
I'd prioritize this, especially now that regular people can get NIOSH-approved N95s again.  We should add a note about propper fitting and wearing.  N95 + facial hair = surgical mask. :-)

**Comment by Telofy** [comment]
I’m now using a [P100 mask with face shield](https://www.aliexpress.com/item/32852116955.html?spm=a2g0s.9042311.0.0.19c54c4dO20n3i) in public transport, so I’d be delighted to be able to select it in the dropdown to get more precise results. :-)

**Comment by blanchardjeremy** [comment]
We're in the middle of a major masks update. More should be coming on this front soon. :)

**Comment by jy2wong** [comment]
Done with the Feb 2021 mask update!
