### ISSUE TITLE
UI: Add drop down menu under whitepaper

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#248]
Minor suggestion: It'd be nice to navigate to the different whitepaper sections from a dropdown on the main menu. When I'm trying to get between sections, I have to keep returning to the main white paper page.

Alternatively, you could place the submenu on the whitepaper pages only as a sidebar (or floating sidebar).

**Comment by beshaya** [comment]
This has been on our to-do list for a while, just haven't had a chance to get around to it :/

Neat cheat: you can go to /paper/all to see the entire whitepaper on one page.

**Comment by blanchardjeremy** [comment]
@beshaya yeah definitely not a high priority. If I knew react I'd go whip up a pull request. But alas, it's been many years since I've done any web development.

**Comment by beshaya** [comment]
I'd say give it a shot! React is really easy; I started learning it in July :)

I'd be happy to help point you in the right direction if you wanted to contribute.
