### ISSUE TITLE
Clarify "basic mask" on the calculator page.

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#251]
The footnote on the Activity Risk page says:

> We mean surgical masks, well-fitted cloth masks with a filter, or similar high-quality masks. Bandanas, poorly-fitting masks, or DIY masks will give less protection than this. 

Does the trichotomy update mean that the white paper needs updating? 

I've been assuming "basic mask" (on the website and the spreadsheet) means "any two-layer cloth mask" ... But here you're saying that means it has a filter.

Seems like here you're saying "basic mask" Includes a cotton mask with a filter. What about a cotton mask without a filter?

**Comment by jy2wong** [comment]
Obsolete with mask update in #666
