### ISSUE TITLE
Spreadsheet: Use copy-only link

### ISSUE THREAD

**Issue by ToastyKen** [microcovid/microcovid#260]
You can use

https://docs.google.com/spreadsheets/d/1DYIJgjG3H5rwt52NT2TX_m429snmIU-jGw1a8ZODwGQ/copy

as the link for the spreadsheet (note /copy suffix), and it will force everyone to make a copy right away.

If you make that change, though, you'd probably want to update the instructions on the spreadsheet.

**Comment by blanchardjeremy** [comment]
Another pro-level trick I learned recently that allows previewing AND copying:

https://docs.google.com/spreadsheets/d/1DYIJgjG3H5rwt52NT2TX_m429snmIU-jGw1a8ZODwGQ/template/preview

Although one slight downside is the different sheet links at the bottom are a little harder to notice.
