### ISSUE TITLE
Spreadsheet: Add "custom people" risk modeler tab

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#261]
I'm intending to add a way to model person risk in the spreadsheet.

I wanted to open an issue for it so I can get feedback on it as I go.

Here's a (non-functional) mockup of what I'm envisioning:

![image](https://user-images.githubusercontent.com/32290/93359842-e50c6900-f7f7-11ea-8e07-8037900f290b.png)

**Comment by beshaya** [comment]
How does this differ from having a tab for each person with their activities for a typical week?

Work - N people, 40 hours, masks, distance
Home - housemates, general risk categories for housemates
Social Contacts - people they see regularly undistanced. Likely marked as housemate/partner
Other activities - shopping, probably. Touring apartments, if they're me >.>

Replace the sumif(within 7 days) with just a sum.

**Comment by blanchardjeremy** [comment]
![image](https://user-images.githubusercontent.com/32290/93773740-47d57a00-fbd5-11ea-8a3d-ee20e87659c4.png)

I now have a working version of this that is pretty user friendly. Let me know if you'd like to take a look and implement it into the main spreadsheet. Happy to help make that happen if there is interest.

**Comment by blakej11** [comment]
I'm not on the microcovid team, but I'm very interested in this - my current model of my own risk suggests that partner risk is by far the dominant contributor to my risk level, and I suspect that's the case for my partners as well, but we aren't in a closed pod.

**Comment by blanchardjeremy** [comment]
Documenting here: @catherio gave this a thumbs up.
