### ISSUE TITLE
Polling place scenario

### ISSUE THREAD

**Issue by oremanj** [microcovid/microcovid#263]
Rather time-sensitive, and a bit dangerous to not provide: if people try to roll their own and do so pessimistically, we'll be disproportionately encouraging smart, numerate people not to vote. Whoops.

I think a plausible scenario here would be:
* 2 average people, 6 feet away
* Indoor, 10 minutes
* They're wearing a basic mask
* You're wearing a surgical mask
* Not talking

Which makes an Activity Risk of 0.1%, or 0.8 microCOVIDs in SF currently. Low risk for a 0.1% person, very low for a 1% person.

**Comment by mattbell** [comment]
<3

**Comment by blanchardjeremy** [comment]
Two thumbs up: 👍👍
