### ISSUE TITLE
Spreadsheet: Make location prevalence feature more user-friendly

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#269]
![image](https://user-images.githubusercontent.com/32290/93776681-a819eb00-fbd8-11ea-8f2d-8b5efb2145ed.png)

Here's my approach to making locations a lot more user friendly. 

The PERSON_RISK_FACTS tab then pulls in the prevalence data from the first row it finds with a checkbox under "default location".

![image](https://user-images.githubusercontent.com/32290/93777722-fa0f4080-fbd9-11ea-92ca-54d5d3b6adac.png)

Of course, making this change requires changes to any sheet that has a "location" dropdown available as well.

Let me know if you'd like to integrate this into the main spreadsheet. Happy to help.

**Comment by beshaya** [comment]
I *really* like this.

**Comment by blanchardjeremy** [comment]
Implemented. Wahoo!
