### ISSUE TITLE
UI: Menu icon missing on Chrome

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#270]
![image](https://user-images.githubusercontent.com/32290/93836342-489ef800-fc37-11ea-9fbe-d29a2262dad6.png)

Recreating: Latest version of Chrome. Narrow the window to it's smallest width (mobile view).

Tried in Chrome (on a couple of different profiles and incognito) and it doesn't show. Does work in Safari (the background window in the screenshot above).

Is anyone else experiencing this?

**Comment by dominic** [comment]
Resolved in https://github.com/microcovid/microcovid/pull/454
