### ISSUE TITLE
Spreadsheet idea: version control for spreadsheet - move formulas to Google apps script

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#271]
Hey team!

Just had a thought. Not sure if it's worth pursuing but in thought I'd put it out there. 

As an avid user (and "improver") of the spreadsheet, I've been thinking about version control a lot. And the extra work it is foranyone to.try to keep your spreadsheet up to date if the official spreadsheet is updated. I'm thinking about how some updates in the future may change very important variables or formula in the spreadsheet. 

Idea: What if we moved a lot of (or all?) the main formulas in the spreadsheet over to Google app script files.  

Benefits I see: 

* we could then add that file to GitHub and make it a little easier for spreadsheet users to easily copy paste the latest script file in. 
* A lot more power. We could do stuff like auto important the latest prevelance data (if we wanted to).
* Minor: much easier to read the code
* Minor: some things are just easier to do in a proper function.)

Downsides: 

* updating a Google apps script isn't exactly familiar territory for most users. 
* We would start approaching a borderline territory where the code complexity of the spreadsheet is similar to the complexity of the website. Although I think they would still be two different use cases (at least until the website has activity logging, household tracking, and person modeling.)
* It's less user-friendly for a user to glance at a cell and try to understand what's going on. 

Curious if this is of interest. If it is, I'm happy to spearhead it. 

Oh and a related idea (that perhaps deserves its own issue?): What's our version control system overall for the spreadsheet? Maybe we could create a changelog with written instructions for how to update to each version of the spreadsheet? Or something along those lines.

**Comment by blanchardjeremy** [comment]
The other possible solution I see is to actually export the spreadsheet to excel each time we want to commit it. Then we can use an approach like this: https://www.xltrail.com/blog/how-to-manage-and-release-excel-files-on-github-part1

I don't exactly see how it would work for an end user that wants it to ultimately be in Google sheets, though. Because even if they started with our version controlled spreadsheet and upload it to google docs, how would they merge in uodates

And this has the obvious downside of "who the hell wants to deal with excel."

**Comment by blanchardjeremy** [comment]
Also, looks like there's a command line interface for Google apps scripts, which I didn't know. https://github.com/google/clasp

**Comment by blanchardjeremy** [comment]
Oh and then an even more involved way of going about this that would be maximally user friendly would be: publish all the code as an add on. That way there's no stuff for them to update locally.

Again, I'd be willing to purusue any of these approaches of the group is interested. (I'm quite attached to developing out spreadsheet for group houses right now.)

**Comment by linesarefuzzy** [comment]
> Oh and then an even more involved way of going about this that would be maximally user friendly would be: publish all the code as an add on. That way there's no stuff for them to update locally.
> 
> Again, I'd be willing to purusue any of these approaches of the group is interested. (I'm quite invested in developing out spreadsheet for group houses right now.)

This would be amazing. I'm also interested in helping with this and also trying to create a spreadsheet for group houses. But—is the MicroCOVID team working on/planning to incorporate activity logging & person risk features into the online calculator? That might actually not be a lot more work than publishing a Sheets add-on. Maybe we should direct our efforts into that instead?

**Comment by blanchardjeremy** [comment]
@linesarefuzzy Good question. #245 speaks to the question of whether it's going to be added to the website (although that's a "local storage" solution. A communal house solution would need to include server-side code and user authentication, which would be fairly large addition. 

But yeah, you're right that by the time we get to a full google sheets add-on (vs just a google apps script) we are basically to the point where the code is at a similar level of complexity as just doing it directly on the webpage. The only benefit is that the storage solution and authentication and sharing are all already built for us.

**Comment by linesarefuzzy** [comment]
@blanchardjeremy Good point. I wonder how the work of setting up a google drive integration and storing data there would compare to a sheets add-on or a built-in authentication and data storage system. I only have experience with the built-in option, which seems like a lot. 

On the other hand, maybe authentication and sharing wouldn't have to be built in. What about this: an anonymous database with a single table of random ids paired with JSON-encoded activity data. No personally identifiable info. You get a personal link to your data, and you can share it with anyone. The JSON data is updated as you enter more data so the link stays up to date. Anyone with the link can view and edit (not ideal, but way cheaper). Thoughts?

**Comment by blanchardjeremy** [comment]
@linesarefuzzy interesting idea! could you move that comment over to #245 so we can keep this one about the spreadsheet possibilities?

**Comment by blanchardjeremy** [comment]
@linesarefuzzy Interesting thought. Could you move that comment over to #245 and we can discuss there?

**Comment by blanchardjeremy** [comment]
As much as I'd love to go this route, I think this is pretty unattainable as a solution. Google makes it VERY challenging for a user to authorize a script to run.

**Comment by blanchardjeremy** [comment]
Closing this for now. I'm open to re-opening it if someone has ideas about how to make this end-user friendly.
