### ISSUE TITLE
Adjust activity risk by # of days since exposure

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#273]
> We observe that not very many transmissions occur fewer than 2 days after infection or more than 9 days after infection. (Not a negligible fraction from a public health standpoint, but few enough to not dominate our personal judgments about our risk.) ([Research Sources](https://www.microcovid.org/paper/14-research-sources#basic-method-infectious-period))

Excluding **all** activities outside the 2-9 days range with this dubious argument goes directly against the standard public advice to quarantine for 14 days after exposure. Yes, _most_ transmissions happen in the 2-9 day range, but surely these calculations can be more sophisticated than a simple on/off binary. The [study referenced to justify the 2-9 day range](https://science.sciencemag.org/content/368/6491/eabb6936) also develops a mathematical formula for infectiousness as a function of days since exposure:

![image](https://user-images.githubusercontent.com/1829213/94089677-c43ca880-fde1-11ea-81af-cd3fcade00b9.png)

The estimated values of all these parameters are also given in that study. How about converting this function to a spreadsheet formula and using it to adjust the impact of activities as time passes? That would be awesome!

**Comment by blanchardjeremy** [comment]
Good question!

I know at one point the team was considering how to factor in generation time: 
![image](https://user-images.githubusercontent.com/32290/94090292-1a055680-fdca-11ea-90a8-8240a4c0dea4.png)

I'd be curious to hear the team's thinking (@catherio, @oremanj) on the choice not to include generation time probabilities. Was it just for ease of use for the spreadsheet beta? Or something else?

**Comment by catherio** [comment]
Purely ease of use, as a central / primary design goal for the system. We want users to be able to compute in their heads things like "how much will adding a mask help?" or "When will I be clear to visit such-and-such person?"

**Comment by catherio** [comment]
"14 days after exposure" -> this is a good point. as with our ENTIRE system, the 2-9 day cutoff only works for SMALL microcovid numbers. If you have a KNOWN exposure to a CLOSE contact, you need to do something more serious. Is there a way we can better flag that in the explanation?

**Comment by blanchardjeremy** [comment]
The main consideration I'm thinking of here is that reduces one of our safety margins. I don't think that's necessarily a bad thing. But it's worth considering.

And as you said, @catherio, it also makes the whole model harder to make sense of. So it becomes a little less useful at helping us develop our intuitive model.

**Comment by linesarefuzzy** [comment]
> Good question!
> 
> I know at one point the team was considering how to factor in generation time:
> ![image](https://user-images.githubusercontent.com/32290/94090292-1a055680-fdca-11ea-90a8-8240a4c0dea4.png)
> 
> I'd be curious to hear the team's thinking (@catherio, @oremanj) on the choice not to include generation time probabilities. Was it just for ease of use for the spreadsheet beta? Or something else?

Are these values hard coded or is it a formula? Is there a version of the spreadsheet that includes them?

**Comment by blanchardjeremy** [comment]
@linesarefuzzy They are hardcoded. I have no idea who at Ibasho added them or what their origin is. @beshaya maybe you know?

Here they are in copy-pasteable format if you want to play with them.

Day | Probability
-- | --
1 | 0.61%
2 | 3.85%
3 | 9.28%
4 | 15.11%
5 | 18.95%
6 | 19.02%
7 | 15.36%
8 | 9.94%
9 | 5.08%
10 | 2.02%
11 | 0.61%
12 | 0.14%
13 | 0.02%
14 | 0.00%
total | 100.00%

**Comment by blanchardjeremy** [comment]
@linesarefuzzy based on @catherio's response above, I don't think we're at a point where we're considering integrating your idea into the model. I'm going to make a note to include a note to the effect of what @catherio said about (about it only working to do 2-9 days in smaller risk scenarios) in the upcoming spreadsheet documentation revision.

**Comment by linesarefuzzy** [comment]
If that table is accurate, your 2-9 day window excludes 3.4% of transmissions. That strikes me as pretty dangerous, and out of alignment with your stated intention to err on the safe side. 

> We want users to be able to compute in their heads things like "how much will adding a mask help?" or "When will that large point expenditure drop off my total?"

At the risk of sounding snarky, isn't the whole point of a calculator that you don't have to compute things in your head? Regardless, I don't understand how making the model more sophisticated in this way would make those kinds of head calculations harder. The answer to "How much will adding a mask help?" would be the same: multiply the result by the mask factor. The answer to "When will that drop off my total?" would just change from 10 days to 14. Or, "It'll gradually reduce over time. It'll be mostly gone after 10 days, and totally gone after 14." I would feel much better with that answer.

**Comment by beshaya** [comment]
Honestly, @linesarefuzzy, I think you are right and the spreadsheet * should * have things roll off. This would better capture high risk events.

Side note, the way most of us use it, doing this would likely result in net more risky behaviors, though, since we'd be discounting points by half starting at 7 days, and the 3% after 9 days only makes a difference if you were within 3% of your tolerance.

That table is also not quite the right one to use though, since it's tracking likelihood of developing symptoms rather than likelihood of being contagious... It'd take a bit of effort to try to pull that together.

> excludes 3.4% of transmissions. That strikes me as pretty dangerous,
Reminder that our error bounds are +200%/-70%. In the case where people use their budget at a flat rate, 3.4% error is really negligible.

> Regardless, I don't understand how making the model more sophisticated in this way would make those kinds of head calculations harder.
If you wanted to do this correctly, your risk from an interaction would peak around 4 days after the event and then roll off for the next 10. It's a lot easier to say "ok, I knew I had had X microCOVIDs two days ago and my next expiration date is in 3 days, so I still have X". If your points change every day regardless of whether you do something, you'd need to check daily before telling someone else your risk. I guess one solution to this we could apply the max rate until the peak and then start rolling off, so that you can say your microCOVIDs are less than or equal to X without checking.

**Comment by blanchardjeremy** [comment]
@linesarefuzzy we integrated this, but only when it comes to calculating your risk to others. See #646 

Closing for now. Let me know if you'd like to re-open it with specific other places you'd like to see it apply.
