### ISSUE TITLE
Spreadsheet: Auto import regional prevalence data

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#274]
I'm not sure if this is worth doing. But it's an idea I wanted to jot down. We could come up with a way to have the spreadsheet automatically include the latest prevalence data.

One solution I imagine (Following the trick @echurilov suggested in #266):

* Centrally publish all the prevalence that the calculator is using to a public .csv
* Use `IMPORTDATA` to import the data
* Allow people to set the locations they actually care about (rather than giving them the entire list in the dropdown!!! which is probably too much). (Following something like #269)

Then we'd update the public .csv every couple of weeks, and everyone who has already cloned the spreadsheet will have the latest data.

The benefit is that it makes it more user friendly. And it creates a more safe experience of the tool for people who are less advanced because people automatically get fresh data (instead of letting data go stale). If someone isn't skilled with using the spreadsheet, or just forgets to update it, they could be working with old data and not even know it.

The downside is that it might be a HUGE import of data that would cause the spreadsheet to lag.

**Comment by echurilov** [comment]
IMPORTDATA on google sheets unfortunately has a maximum size - I originally tried importing the full NYT dataset which has all US counties, and it was well over size. To stay under this cap, I limited my version to just the Bay Area counties, as they were the most personally relevant. To pull off a variant of my trick, you could publish many CSVs for different regions, have the user select theirs, and complete the IMPORTDATA formula based on that.

**Comment by catherio** [comment]
Referenced in https://github.com/microcovid/microcovid/issues/245. Increasing priority on this!

**Comment by blanchardjeremy** [comment]
Just finished implementing this into the spreadsheet! Auto-importing magic is available to all!

And if you want to migrate to this change, you can use the brand new spreadsheet changelog: https://docs.google.com/document/d/1iwTFoCS8lOIWWm-ZzcMZ_mPHgA8tHVVA3yhKY23gDu8/edit#
