### ISSUE TITLE
Historical Prevalence Data

### ISSUE THREAD

**Issue by rizwank** [microcovid/microcovid#289]
Thank you for this! It's changed our lives.

We're keeping historical prevalence data and would love to backfill our lookup chart; can you provide a historical view (just a CSV/TXT download) of Adjusted Prevalence once we've selected a state/county?

**Comment by beshaya** [comment]
I don't think we have bandwidth to support this. You might be able to get it out of the git log, or directly from our sources (covidactnow / JH CSSE)

**Comment by rizwank** [comment]
>directly from our sources (covidactnow / JH CSSE)
Ah thanks. I'm not aware of the formula to get there; but I imagine it's in the whitepaper? 

EDIT:
Found the data source : 
https://github.com/microcovid/microcovid/blob/main/update_prevalence.py
if anyone else is looking
