### ISSUE TITLE
Improved flow and legibility for calculator

### ISSUE THREAD

**Issue by mattbell** [microcovid/microcovid#294]
This is a cluster of changes designed to simplify, disambiguate, and improve legibility of the calculator.

Some of these changes could be implemented in isolation, but they're all designed to work toward the above goals

Here's a UI mockup: https://figma.com/file/OequnB2LlYsi4PX9BUfocE/Calculator-mock-up?node-id=1%3A2

**Title:**

Above the shaded part of the form, add a large title "Calculate the approximate COVID risk of any activity”

Motivation: Right now if you go straight to microcovid.org you don't know you're looking at a calculator for activities, so I wanted to make that clear.
[Catherio approved above]

**Simplifying location:**  

For step 1:   Most users want to have their location auto-filled based on IP, or manually enter location quickly and then move on.  A few users (maybe 1%) will want to enter custom location data.

To make the first use case easier:
- Put purple rounded rect “step 1” at the top above “location and prevalence” paragraph.
- New text: “Step 1: Enter your location.” instead of "Step 1 - Choose a location."
- Remove all text about the specific number of cases below and replace it with:

> Reported prevalence: 0.04%
> Adjusted prevalence: 0.29%
> ">" Learn more

"Learn More" brings up the original text the way it is now.  [Catherio is generally supportive of this]
Selecting "enter manually" on the location drop down menu also brings up the original text the way it is now.

De-emphasize case data (eg by using a gray font) unless you select the option to enter it manually.  Text fields still currently highlight when you click on them, and we want to distinguish them from the text fields on the right that you can enter

**Simplifying steps 2 and 3:**

Many users will want to browse the list of activities to find one they’re curious about, then possibly modify the parameters to suit their specific situation.  A significant number will want to enter new activities from scratch.  Users will need to understand how the parameters work.  
 
Some proposals:
 
Put large “Step 2: Describe the activity” colored rounded rect at the top.  This will be an amalgam of steps 2 and 3 and will take the right 2/3 of the space on desktop.  I actually don't think the person risk / activity risk distinction is useful for casual users, and it will allow us to ask risk questions in the order that most makes sense for disambiguation.  
 
Small text below "Step 2" should say “Pick a pre-selected one from this list, which assumes the other people are random residents of your city unless stated otherwise.”
 
Below that: “Customize the parameters or create your own activity:”
 
With the exposure risk and person risk questions, I want to disambiguate how people should think about number of interactions, time, and distance as I think this is a big source of confusion.   I think we should rephrase the questions in this order:

> “Are you trying to model your risk of living with a household member or intimate partner?”

If “yes”, then it asks you to select dropdown options for “household member or intimate partner?“, then “# of people”, and then “Person(s) risk profile”

Given that under this situation we’re now often telling people that their housemates or intimate partners are very likely to give them COVID, I think we owe it to them to provide some solutions as they’re not about to kick their partner to the curb.

I think under these circumstances we should provide information on how they could reduce their risk (eg if their partner’s an essential worker, they could get N95 masks and wear them all day to lower risk, or for extreme situations, you or they could wear masks indoors in the house.  If their partner is not an essential worker but is taking a lot of voluntary risks, you can use this result to talk them into taking fewer risks.)  This needs more thought but I think it’s really important to get right. TODO: I will whip up a brief paragraph of guidance for them.  

Proposed text:
Reducing risk with housemates and intimate partners can be tough.  Here are some ways you can approach the discussion:
- If the person is an essential worker, they could get a NIOSH-certified N95 mask (or a KN-95 if N95s are not available) and wear it at work to lower risk.
- If their social activities make them a risk, ask them to socialize outdoors, at a distance, and/or while wearing masks.
- In extreme situations, you or they could wear masks inside the house when near one another, or choose to isolate yourselves in different parts of the house.  This practice was common among doctors during the peak of the pandemic, and isolating yourself from anyone displaying symptoms is still strongly recommended.
- Have a conversation with the person about how their choices affect not just their risk, but yours as well.  

For regular activities, the text could be:
Here are some ways of reducing risk.  These may or may not apply to your activity: 
- For many activities, it's possible to go at non-peak hours (eg first thing in the morning for grocery shopping) so that there are fewer other people around.
- If it's a social activity, move it outdoors and encourage people to wear masks and stay further away from each other.  
- Get the best mask you can.  NIOSH-certified N95 masks can now be purchased online, and offer far more protection than cloth masks.  KN-95s are a cheaper alternative and can be used if budget is an issue or if N95s are not available.  

Epistemics issue: If you have 4 housemates, and select the “has 4 close contacts who socialize and don’t work”  I think you end up double counting.  We need to provide people with guidance on how to score this properly.   I'd propose a quick line saying "If you are modeling exposure to members of your house, only count their contacts outside the house" below the "person(s) risk profile dropdown  [Catherio approves of this idea]

If the answer to “Are you trying to model your risk of living with household members or intimate partners?” is “no” then we can frame the questions around a single activity.  One challenge to handle is that some activities are stationary (eg eating in a restaurant) while some are mobile (eg shopping at a grocery) and I think we need to rephrase the questions to clarify how people should respond to both.  Here’s what I’d propose as an order to ask the questions: 

[Column 2 on web]
> “How many people get near you? (within 10ft or less)    
> “How long is each of these people typically near you?” [this ordering solves the problem of whether you should model being at a grocery store as 50 people who spend 30 minutes in the same building as you vs you stand near 20 different people for 3 minutes each while shopping]
> “How close are they most of the time?”

[Column 3 on web]
> “What’s their risk profile?”
> “Is it indoor or outdoor?”
> “What mask are you wearing?” (if you’re eating or drinking, say “no mask”)
> “What mask are they wearing?” (if you’re eating or drinking, say “no mask”)
> “Are people usually talking?”

I believe this order and phrasing of questioning helps disambiguate a lot of the questions that many users have had about how to answer the questions.

**Comment by paulmhan** [comment]
Hi can I be assigned to this? I would love to help you on this!

**Comment by catherio** [comment]
"Title:" -> 👍

**Comment by catherio** [comment]
"which assumes the other people are random residents of your city." needs to be "unless stated otherwise" because one of them is co-isolating partner

**Comment by catherio** [comment]
“Right now if you go straight to microcovid” -> sentence fragment?

**Comment by catherio** [comment]
“Put purple rounded rect “step 1” at the top above “location and prevalence” paragraph.” => I don’t understand what you mean

**Comment by catherio** [comment]
"Learn more" -> 👍 to this in general

**Comment by catherio** [comment]
"Are you trying to model your risk of living with a household member or intimate partner?" would prefer this as "Are you trying to model your risk of living with a household member or intimate partner? or someone else?" -> "Housemate or intimate partner" // "Someone else"

**Comment by catherio** [comment]
"we should provide information on how they could reduce their risk" -> strong in favor 👍

**Comment by blanchardjeremy** [comment]
Happy to help pitch in on some of these changes once you've got the basic framework set up.

**Comment by catherio** [comment]
"quick line" 👍

**Comment by catherio** [comment]
"“How many people get near you? (within 10ft or less)
“How long is each of these people typically near you?” [this ordering solves the problem of whether you should model being at a grocery store as 50 people who spend 30 minutes in the same building as you vs you stand near 20 different people for 3 minutes each while shopping]"

I'm concerned about this, very specifically because I think people think of how long they spend grocery shopping total, and might have trouble separating this out?? Not sure how to address this.

**Comment by catherio** [comment]
"I believe this order and phrasing of questioning helps disambiguate a lot of the questions that many users have had about how to answer the questions." -> awesome, I agree

**Comment by mattbell** [comment]
> Hi can I be assigned to this? I would love to help you on this!

Heya!  I'd love the help.  I have not done any work on the frontend and have not done web frontend programming in a while, so if you are familiar and can hit the ground running I'd be overjoyed to have you take it on.

**Comment by mattbell** [comment]
> “Right now if you go straight to microcovid” -> sentence fragment?

Oops, meant to say "Right now if you go straight to microcovid.org you don't know you're looking at a calculator for activities, so I wanted to make that clear."

**Comment by mattbell** [comment]
> "which assumes the other people are random residents of your city." needs to be "unless stated otherwise" because one of them is co-isolating partner

Fixed in description!

**Comment by mattbell** [comment]
> “Put purple rounded rect “step 1” at the top above “location and prevalence” paragraph.” => I don’t understand what you mean

Hopefully this explains it?  
<img width="640" alt="Screen Shot 2020-10-04 at 11 37 15 PM" src="https://user-images.githubusercontent.com/496023/95047320-b537df00-069a-11eb-879c-52c33a685564.png">

**Comment by mattbell** [comment]
> "Are you trying to model your risk of living with a household member or intimate partner?"
> 
> The "or" that isn't explaining the two options is throwing me a bit for a loop; would prefer this as "Are you trying to model your risk of living with a household member or intimate partner? or someone else?" -> "Housemate or intimate partner" // "Someone else"

Good point.  Another option would be to remove the next question entirely by asking:
"What type of activity or relationship is this?"
> One-time activity (default)
> Ongoing relationship with intimate partner
> Ongoing interaction with housemate

What do you think of that?

**Comment by mattbell** [comment]
> "we should provide information on how they could reduce their risk" -> strong in favor 👍

Great, I'll write up a short paragraph that we could use.

**Comment by mattbell** [comment]
> "“How many people get near you? (within 10ft or less)
> “How long is each of these people typically near you?” [this ordering solves the problem of whether you should model being at a grocery store as 50 people who spend 30 minutes in the same building as you vs you stand near 20 different people for 3 minutes each while shopping]"
> 
> I'm concerned about this, very specifically because I think people think of how long they spend grocery shopping total, and might have trouble separating this out?? Not sure how to address this.

Oh interesting -- I was hoping it would clarify that.  One way to address this is to separate seated from moving activities.  For seated activities (eg restaurants), we can keep the wording the same.  For moving activities (eg shopping) we could add some extra info where we ask people to estimate how many people were within 10ft of them at any given time and how long the total activity was.  Epistemically I'm not sure if this is valid as I'd rather have one 30 minute interaction than 30 one minute interactions.  We could also word it carefully to say "think of times when you were near someone for more than a few seconds.  How long were you usually near them?  How many people did you get near to in this way"

**Comment by mattbell** [comment]
> These all sound great to me overall.
> 
> I think I'll have an easier time giving feedback once I see a mock-up or an early draft of it.
> 
> Happy to help pitch in on some of these changes once you've got the basic framework set up.

Cool.  I'm going to do some mock-ups unless someone else wants to take over from here.

**Comment by blanchardjeremy** [comment]
> Cool. I'm going to do some mock-ups unless someone else wants to take over from here.

I think mockups would be best given how in-depth this conversation is. If you get us a detailed mockup or spec list of what we're aiming for, that should help.

I'm pretty new to React (also haven't done front-end programming in years). So I can help implement some of the basics. But it might take someone with more skill than I to get the whole thing complete.

**Comment by blanchardjeremy** [comment]
Also, I remember someone suggesting that location data be its own row above step 2 & 3.  Now that we're making it a much "lighter" section, I wonder if we could do that instead?

**Comment by blanchardjeremy** [comment]
> Hopefully this explains it?

In this mockup, are you also suggesting moving the "reset form" button and the disclaimer down below?

**Comment by blanchardjeremy** [comment]
I have a branch going for this upgrade: https://github.com/microcovid/microcovid/tree/calculator-usability-upgrade

**Comment by blanchardjeremy** [comment]
![image](https://user-images.githubusercontent.com/32290/95110019-425a5280-06f2-11eb-9e2a-af7ef6dd4adf.png)

@mattbell how's this looking so far?

**Comment by blanchardjeremy** [comment]
I've moved this over to pull request #299 so we can keep the commits and code-related comments in one place. We can use this issue to determine what the specs are.

**Comment by mattbell** [comment]
> ![image](https://user-images.githubusercontent.com/32290/95110019-425a5280-06f2-11eb-9e2a-af7ef6dd4adf.png)
> 
> @mattbell how's step 1 looking so far?

Looks great!

**Comment by mattbell** [comment]
> > Hopefully this explains it?
> 
> In this mockup, are you also suggesting moving the "reset form" button and the disclaimer down below?

Yes

**Comment by blanchardjeremy** [comment]
Sharing @mattbell's  mockup here for consistency: 

https://figma.com/file/OequnB2LlYsi4PX9BUfocE/Calculator-mock-up?node-id=1%3A2
