### ISSUE TITLE
Changing calculator results for easier comprehension

### ISSUE THREAD

**Issue by mattbell** [microcovid/microcovid#302]
<img width="629" alt="Screen Shot 2020-10-05 at 9 13 39 PM" src="https://user-images.githubusercontent.com/496023/95158250-f9d18200-074f-11eb-98f0-87cc1e54c60f.png">

- Add a line below the "# of microcovids" line that describes its relationship to the weekly risk budget.  
- Fold in the "low/medium/high/dangerously high" risk assessment into this line, and change the color of the whole line based on the risk
- Have this part also float on the bottom of the page as the microcovids number currently does.
- (1% would be default but would update to 0.1% if selected)
- Decrease the font size on mobile to maybe half of the current size so the results lines don't take up 1/3 of the screen.

**Comment by catherio** [comment]
"Fold in the "low/medium/high/dangerously high" risk assessment into this line, and change the color of the whole line based on the risk" -> wanting @dominic input on this!

**Comment by dominic** [comment]
This seems to be outdated based on others' design updates.
