### ISSUE TITLE
Create a visual scale for our risk levels

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#312]
We've created a low/med/high/very high/dangerously high scale. Right now, a user just sees their current level. But they don't know how many total levels there are on the scale. I wonder if we could adopt a "thermometer" approach like COVIDactnow does.

![image](https://user-images.githubusercontent.com/32290/95349929-73fb2700-0874-11eb-8b78-7d4ac6d91f24.png)

Thoughts?

**Comment by cameronmarlow** [comment]
It would be nice if this was available as an image for twitter and fb shares

**Comment by mattbell** [comment]
I love the idea of being able to share out some image that documents the risk for a specific activity in a specific location.

The thermometer is visually nice but I also like the compactness of the current "results" bar, and would want to find a way to still deliver the results in 1-2 lines.  Right now I don't share the concern that the "very low -> dangerously high" scale doesn't give users a sense of the range of labels.  I think people would assume it goes from "very low" to "very high" by default, and we give them a numerical answer as well, so I'm less worried about misinterpretation.

**Comment by oxytocinlove** [comment]
We appear to have this now, is this still relevant @blanchardjeremy ?

**Comment by blanchardjeremy** [comment]
Let's call it good. If folks wanna re open the Share Image aspect as its own issue, that's fine.
