### ISSUE TITLE
Spreadsheet risk calculation seems backwards

### ISSUE THREAD

**Issue by durka** [microcovid/microcovid#327]
So I've added a column for myself to the PERSON_RISK_FACTS spreadsheet:
![image](https://user-images.githubusercontent.com/47007/95640573-56dc7900-0a6b-11eb-925a-737858ade035.png)
(side note: it would be real nice if the main site displayed cases in the week before last, as that's where I'm copying the numbers from)

Also in case it's relevant, I changed some of the person type labels to make it easier for me to use the dropdown: 
![image](https://user-images.githubusercontent.com/47007/95640595-71aeed80-0a6b-11eb-919c-10ce89efe899.png)

Then I've entered some activities: 
![image](https://user-images.githubusercontent.com/47007/95640621-9c994180-0a6b-11eb-8bfe-c31666a70537.png)

I don't trust these results for a simple reason: if I *increase* the number of local cases on the PERSON_RISK_FACTS sheet, the risk for each activity goes down. How is that possible?

**Comment by blanchardjeremy** [comment]
@durka hi there. Great questions. Please see the latest version of the spreadsheet. It has a whole new place for you to add locations. And it is a big fix that addresses the behavior you're seeing.

**Comment by durka** [comment]
Great thank you! Now, when I pretend there's more cases this week, the risk goes up! It's still not super easy to fill in the location info... I guessed 0% for case increase because the website says "cases are stable or decreasing". Though, adjusting that percentage doesn't seem to do much. Is there a better place to find that number?

**Comment by blanchardjeremy** [comment]
Yes. If there are more cases this week than last week, that means we predict that the cases are going to continue to be on the rise. 

Yes, if you enter 0% for the "increase from last week" then the risk should be the same. If you enter 20%, then you should see the risk go up by about 20%.

I'm not 100% clear on your question/request. Can you help me understand if there's something that still isn't working, or something you'd like to see changed?

**Comment by durka** [comment]
Interestingly, if I put in a negative percentage for the change in cases from last week to this week, the activity risks go down. But any nonnegative percentage (from 0 to 1000000) produces the same results.

**Comment by blanchardjeremy** [comment]
Can you send me a screenshot?

Are you using the latest version of [the spreadsheet](https://docs.google.com/spreadsheets/d/1DYIJgjG3H5rwt52NT2TX_m429snmIU-jGw1a8ZODwGQ/edit#gid=1278800867)?

Here's what I see:

![image](https://user-images.githubusercontent.com/32290/95758768-b69a7600-0c5d-11eb-889b-5c5018d46719.png)

![image](https://user-images.githubusercontent.com/32290/95758795-be5a1a80-0c5d-11eb-909b-fc49461b593f.png)


It goes from 0.24% to 0.29% which is the appropriate behavior. 

Are you seeing something different?

**Comment by durka** [comment]
Yes... and I think I see why. I created a third row in that Location tab.

Check out the formula in I3-I4...
![image](https://user-images.githubusercontent.com/47007/95762377-9f6a8100-0c7b-11eb-9021-a04c764bd8e5.png)

...vs the one in I5 and below...
![image](https://user-images.githubusercontent.com/47007/95762440-b610d800-0c7b-11eb-9e40-6df6fe4d53f1.png)

So, SF and Oakland appear to ignore negative percentages, while newly added cities will ignore positive percentages! Both of those seem weird to me, since cases can be either increasing or decreasing?

**Comment by blanchardjeremy** [comment]
Ah ha! Yes. That is a bug. I've corrected it in the template spreadsheet. You can correct it on yours by copy-pasting the formula in `I3` down to all the rows below!

Good catch. Thank you!
