### ISSUE TITLE
Spreadsheet: Update masks to match calculator

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#330]
We know @catherio is working on a masks overhaul. In the meantime, let's have the mask info in the spreadsheet match the current thinking in the app.

**Comment by blanchardjeremy** [comment]
Done:

Cotton masks are a new addition.

What was called "basic mask" is now "surgical mask or mask w/ filter insert"

![image](https://user-images.githubusercontent.com/32290/95688937-7f2abb80-0bc2-11eb-805b-b54d94bc9bc6.png)

**Comment by mattbell** [comment]
Is there a place where I can learn how we get an 0.01 multiplier for a fit
tested N95 + goggles?

**Comment by blanchardjeremy** [comment]
@mattbell that'd be a question for the crew that originally set the variables. Not sure who that is. @catherio ? @oremanj ?

**Comment by mattbell** [comment]
We've got a discussion on the topic going on Slack!
