### ISSUE TITLE
Risk upper bound is too low?

### ISSUE THREAD

**Issue by NickHeiner** [microcovid/microcovid#331]
I created [a scenario](https://www.microcovid.org/?distance=intimate&duration=1200&interaction=oneTime&personCount=100&riskProfile=hasCovid&setting=indoor&theirMask=none&topLocation=US_30&voice=loud&yourMask=none) that was about as risky as I could make it: an indoor orgy of 100 singing COVID patients in Montana.

However, the results page says that the risk of this is `>10%`:

![image](https://user-images.githubusercontent.com/829827/95684688-40880780-0ba8-11eb-818e-0542ffe5022f.png)

While broadly, the "dangerously high" messaging feels correct, I feel like the actual likelihood of getting COVID is much higher than 10%. Showing a number that low for such a risky activity could actually make people more comfortable with that activity. ("Oh, that's much safer than I thought it was.")

**Comment by beshaya** [comment]
Yeah, numerically, we should swap out of the linear approximation around 10% and use 1 - (1 - PERSON_RISK * ACTIVITY_RISK) ^ N.

In the case of 100 person orgy, this is >99%.

**Comment by NickHeiner** [comment]
# OH NO NOW I NEED TO CANCEL MY PLANS
