### ISSUE TITLE
Clear the "saved scenario" when any values have changed

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#337]
![image](https://user-images.githubusercontent.com/32290/96082308-d86b4700-0e6f-11eb-9a10-c3e02200030c.png)
![image](https://user-images.githubusercontent.com/32290/96082318-de612800-0e6f-11eb-8cc6-354c4c20f1a9.png)

It could confuse the user to still see "15-minute car ride" after we've changed it to "household member"

**Comment by mattbell** [comment]
Agreed.  Would love to see this fixed.  Should it go to "Custom scenario" as soon as you change a value?

**Comment by jy2wong** [comment]
isn't possible to change interaction type after you've selected a preset now.
