### ISSUE TITLE
Write functional tests

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#339]
We need to make a base set of functional tests for actual calculator interactions. Including:

- Normal calculator use
- Edge cases

@mattbell is going to write up a doc with some basic testing approaches we want to keep in mind.

**Comment by mattbell** [comment]
https://docs.google.com/document/d/1DCNAHy-4ZpZo1cw1GufhYVdNX1X7VC_hCZPOc4jFFgo/edit

**Comment by blanchardjeremy** [comment]
Hey, @mattbell I'm going to re-open this. Functional tests are something I'd love for us to write in the code. So we'd use your list to help us come up with automated tests that run every time we change the code. :)

**Comment by mattbell** [comment]
NP!

**Comment by dominic** [comment]
I'd vote to close this because it's just too big. Issues for specific tests would be good (like https://github.com/microcovid/microcovid/issues/446). Requiring new components to be tested would also be a good mandate. 

However, I'm not sure what the "done" criteria are for this right now.

**Comment by blanchardjeremy** [comment]
deal.
