### ISSUE TITLE
Overpromising risk reduction with bandanas and buffs

### ISSUE THREAD

**Issue by ddfisher** [microcovid/microcovid#340]
Bandanas and buffs are grouped with cotton masks and currently give a 1/4 risk reduction in the "Their Mask" dropdown.  From my reading this does not correspond with what the white paper says, nor with the source the white paper cites.  From the white paper:
> Bandanas, buffs, or other single-layer coverings provide significantly less protection than we estimate here (see Research Sources), so for simplicity we treat them as "no mask", even though we do believe they provide some benefit.

I think [Fischer et al](https://advances.sciencemag.org/content/6/36/eabd3083) is the only source used for this, which shows a very wide range in droplet count reduction for bandanas, averaging to about 50%.  Buffs do not provide a significant reduction, and on average appear to be actively harmful (from my naive understanding of the chart). Based on this, my read is that buffs should provide no risk reduction in the calculator, and bandanas could plausibly provide either 1/2 or none, depending on how cautious we want to be about the large variation in effect.

**Comment by jy2wong** [comment]
Obsolete with Feb 2021 mask update, which does set bandanas to 1/2.
