### ISSUE TITLE
Numbers in calculator no longer rounded

### ISSUE THREAD

**Issue by ddfisher** [microcovid/microcovid#341]
The numbers in the calculator are no longer rounded to hide floating point errors.  This makes them somewhat confusing/harder to parse.
![image](https://user-images.githubusercontent.com/245905/96349708-38c3d980-1066-11eb-9c4b-3dc0e9af40f1.png)

**Comment by blanchardjeremy** [comment]
@ddfisher can you link to the scenario you used to generate this?

**Comment by blanchardjeremy** [comment]
Oh I found one. This scenario: https://www.microcovid.org/?distance=sixFt&duration=10&interaction=oneTime&personCount=5&riskProfile=livingAlone&setting=indoor&subLocation=US_06001&theirMask=filtered&topLocation=US_06&voice=normal&yourMask=filtered

![image](https://user-images.githubusercontent.com/32290/96350602-6f502300-106b-11eb-9518-b7fa72afb571.png)

**Comment by dandv** [comment]
[Another one](https://www.microcovid.org/?distance=intimate&duration=600&interaction=oneTime&personCount=1&riskProfile=frontline&setting=indoor&subLocation=US_12011&theirMask=none&topLocation=US_12&voice=normal&yourMask=none)

> This is a roughly ~7,000-in-a-million (0.7000000000000001%) chance of getting COVID from this activity with these people.

**Comment by blanchardjeremy** [comment]
Fixed with #395
