### ISSUE TITLE
Add ability to log your last 10 days of activities and share by link

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#383]
I think there are a few other issues open on this topic.  

Use case: I want my friend to tell me his score for the last 10 days so I know the cost of seeing him. 

It doesn't make sense to have him use the spreadsheet. 

And this approach is possibly easier than me having to enter all data. (although that's how I currently solve it.)

It's require a lot of design work to come to with a UI/UX that's easy to use. 

Possible approach: 

- create an exandable section below the main calculator called "activity log"
- allow you to click "add to log" for the current scenario above. 
- offer delete/edit buttons for each activity
- must include a way to set the date of the activity. 
- automatically remove the activities over 10 days old
- display your 0-7 day budget total (risk to you) and 2-9 day budget total (risk to others)
- display your totals as a percentage of your weekly budget
- include a note that you must include entries for housemates
- possibly allow activies to not have a date and always count against your score (because you do them every week)

**Comment by beshaya** [comment]
I think our decision was "improve the spreadsheet / messaging so people use the spreadsheet." Ok to close?

**Comment by blanchardjeremy** [comment]
Yeah I'll close this. I'll open a different issue that is about how to properly directly users to the spreadsheet when they want to solve this problem.

**Comment by blanchardjeremy** [comment]
I created #484 as an issue for that.
