### ISSUE TITLE
Add warning when people number over X 

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#385]
Remind them to only count the people near them 

Approved by @catherio  on slack.

**Comment by blanchardjeremy** [comment]
@mattbell suggested something like:

> NOTE: This number reflects how many people are within 15ft of you at any given time.  It’s unlikely this number exceeds 100

We could/should replace the existing message encouraging people to host smaller gatherings.

**Comment by beshaya** [comment]
We already have this:
![image](https://user-images.githubusercontent.com/5877421/97614408-225b3d80-19d7-11eb-8161-d01b8b5c7125.png)

**Comment by blanchardjeremy** [comment]
@beshaya  yep. We're suggesting changing it from being focused on "this gathering is too big" to "you must be misunderstanding this field. You're only supposed to count the people within 15 feet of you."
