### ISSUE TITLE
Underestimating benefit provided by non-surgical masks

### ISSUE THREAD

**Issue by hurricanescout** [microcovid/microcovid#405]
Until recently the model assumed at least some risk reduction to the wearer of a non surgical mask. Now the model (both spreadsheet and web form) assumes that the risk to an individual is identical if they are unmasked as if they wore a cotton mask. This is inconsistent with medical guidelines, and it is concerning that such a significant assumption was changed without clear updates to users. It is also concerning that the model would suggest to an individual that their risk if the same if they are unmasked as it would be if they wore at minimum a cotton mask, bandana or gaiter. Can you please clarify?

**Comment by beshaya** [comment]
Hi @hurricanescout apologies for the confusion. The literature is quite clear that cloth masks are much more effective at source control than personal protection.

I dug through the papers we have, and the best study we've found on personal protection is Jimenez et al, who suggest that a cloth mask is perhaps a multiplier of 2/3: https://docs.google.com/spreadsheets/d/16K1OQkLD4BjgBdO8ePj6ytf-RpPMlJ6aXFg3PrIQBbQ/edit#gid=519189277&range=C189:J189

I'll bring this to our epistemics the team and see if they agree to add it back.

**Comment by jy2wong** [comment]
I think this is obsolete by the Feb 2021 mask update, which separates thin or loose masks (bandanas, gaiters) from thick and snug cloth masks, which says that thin or loose masks protect others but not you, and that thick and snug cloth masks protect you and others (but not as much as a surgical mask).
