### ISSUE TITLE
Give better user feedback when predefined scenario is selected without any location data

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#407]
![image](https://user-images.githubusercontent.com/32290/97665756-77c83680-1a39-11eb-8544-f5a1431eef1d.png)

If you select a predefined scenario, nothing happens until you select your location. But there's no feedback to the user to indicate to that. It just leaves you wondering "wait, is it broken? why didn't it load a scenario?"

**Comment by oxytocinlove** [comment]
@blanchardjeremy This appears to no longer be relevant, can I close it?

**Comment by jy2wong** [comment]
Yeah, I think we can close this
