### ISSUE TITLE
Differentiate font sizes for risk budget selector

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#409]
![image](https://user-images.githubusercontent.com/32290/97719918-dff03a00-1a84-11eb-8204-c052530188e0.png)

All of these are the same size. We should make them different sizes so some information stands out a bit more. Probably the help text under the label should be smaller.

**Comment by oxytocinlove** [comment]
@blanchardjeremy This appears to have been fixed at some point, is it alright if I close this? 
<img width="781" alt="Screen Shot 2021-08-15 at 2 33 39 AM" src="https://user-images.githubusercontent.com/4383494/129469515-b5bb3b39-61cd-4c8b-9319-ad7f5aa94ccd.png">

**Comment by blanchardjeremy** [comment]
Yeah I fixed it a long time ago I think a d forgot to close this.
