### ISSUE TITLE
Spreadsheet: "Person with COVID" still gets adjusted by location

### ISSUE THREAD

**Issue by daniel-ziegler** [microcovid/microcovid#429]
In the example scenarios & activity log, the person risk for "Person with COVID" is wrong when you select a location that's not your default location.

**Comment by blanchardjeremy** [comment]
@daniel-ziegler Good catch. I had fixed this on my house's copy of the spreadsheet and forgot to move it over. Just published with this note in the changelog:

> 2020-10-31: Fix big where known COVID case would scale based on the location you choose. (The change is the "person risk each" column formula. You can copy that formula over to your sheet if you want to migrate your sheet to this version.)
