### ISSUE TITLE
Move alerts to site-wide display location

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#439]
Right now, you have to drop <AutoAlert> in anytime you use it.

I think it'd be great to have floating notification that show up at the bottom of the page anytime an alert is used anywhere on the site. Right now it's just "copy to clipboard" notifications.

**Comment by jy2wong** [comment]
Jeremy, is this still relevant?

**Comment by blanchardjeremy** [comment]
Nah.
