### ISSUE TITLE
Add test cases for prevalence calculation

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#446]
Cases: 1Pop: 1000% increase: 0% positive: 1 | Reported prevalence: 0.20%Adjusted prevalence: 1.20%
Cases: 1Pop: 1000% increase: 0% positive: 99 | Reported prevalence: 0.20%Adjusted prevalence: 2.00%
Cases: 1Pop: 1000% increase: 50% positive: 1 | Reported prevalence: 0.20%Adjusted prevalence: 1.80%
Cases: 10Pop: 1000% increase: 50% positive: 1 | Reported prevalence: 1.10%Adjusted prevalence: 9.90%
Cases: 10Pop: 100% increase: 50% positive: 1 | Reported prevalence: 11.00%Adjusted prevalence: 99.00%

**Comment by jy2wong** [comment]
I think we cover this in `src/data/__tests__/calculate.test.ts` now.
