### ISSUE TITLE
Display the Person Risk for selected risk profile again?

### ISSUE THREAD

**Issue by speezepearson** [microcovid/microcovid#476]
Pre-UI-change, when I selected a risk profile (e.g. "In a closed pod of 4 people") from the dropdown, it would show the Person Risk below. I found this really useful, since it gave me the information I needed to compute slightly unusual scenarios (typically involving chains of people) that the calculator isn't built for. It looks to me like that line got removed in the makeover (specifically, in 9fb25b2838d251095d05b3d1b3b231bdc1c9befe, I believe).

Edit: upon inspection, it looks like this info was _deliberately_ removed, probably for decluttering reasons. But perhaps the information could get surfaced somewhere more out-of-the-way? I'll likely open a PR in the next couple weeks, unless I hear that you actively don't want this.

**Comment by blanchardjeremy** [comment]
Hi @speezepearson ! Thanks for asking.  It's still available actually. Simply click on the "learn how we calculated this" header below the thermometer.

**Comment by blanchardjeremy** [comment]
Let us know if you have any suggestions for how we might make that more obvious.

**Comment by beshaya** [comment]
@blanchardjeremy this isn't the first request I've seen for this. What do you think of displaying the person's risk profile in the calculator again?

It seems like it would be in line with showing multipliers in the dropdowns - making it easy to compare risks of various lifestyles is useful for educating users + building intuition.

**Comment by blanchardjeremy** [comment]
Hmmm. Yeah I'm open to it. Maybe we do it small in the text right below the drop-down? If more explanation is needed, it can go in a popover.

**Comment by jy2wong** [comment]
Risk profile does list person risk now.
