### ISSUE TITLE
Create a way to keep translation files up to date

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#487]
We need a way to know when the source text changes that the other translation files need to be changed as well.

For reference...

_Originally posted by @gyp in https://github.com/microcovid/microcovid/pull/479#issuecomment-723568034_

@blanchardjeremy Truth be told, I never thought that far ahead. I only ever did this kind of localization in enterprise environments, so I don't really have anything battle-tested and ready-to-use for a small open-source project like this.

I see a number of options:

1. Configure a GitHub Action that automatically opens an issue for all currently supported languages on any change in src/locales/en.json, assuming that that is the original source, and assigning it to the maintainer responsible for that language. [This ready-to-use Action](https://github.com/JasonEtco/create-an-issue) seems like a good way to do that.
2. Integrate with a professional localization SaaS and make use of its features. [Crowdin](https://crowdin.com/pricing#crowdin-pricing-key-features) seems to be the one that has the best free option for a small project like this and they supposedly offer the enterprise features for OS projects if asked, but you might know and like others.
3. Self-host [Weblate](https://weblate.org/) or something similar and integrate with that. To be honest, it seems to be an overkill for a project of this size, but they have Docker-based images, so spinning it up and maintaining it should not be that problematic or expensive.

Let me know which one you prefer and I can start digging into it. My suggestion would be (1) for the time being, but (2) has the added benefit of making it much easier for non-tech contributors to participate.

**Comment by blanchardjeremy** [comment]
Another option we have is i18n-ally: https://github.com/antfu/i18n-ally/wiki/Review-&-Collaboration-System

I'm not 100% sure that option will actually notify us that the base string changed or not. And it requires everyone to use VS Code, which may not be what others want.

**Comment by blanchardjeremy** [comment]
Reading up on how Mozilla solves this: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Changing_existing_strings

> If you are changing a string such that its meaning has changed, you must update the entity or property name for the string to match the new meaning. If your changes are relevant only for English — for example, to correct a typographical error or to make letter case consistent — then there is generally no need to update the entity name.
> 
> Changing the string ID will invalidate the existing translation, the new string will be reported as missing in all tools, and localizers will have to retranslate it. Given the diversity of tools used by localization teams, this is the only reliable method to ensure that localizers update existing localizations.

That's an interesting approach: change the key anytime the meaning has changed. That way, no matter what tool someone is using, they will get a notice about a missing key, and they can re-translate it.

I wonder about the solutions you listed above, @gyp, that might be more elegant.

**Comment by blanchardjeremy** [comment]
I'd be interested to see if one of these web app services has a free plan for open source projects. 

This is one option that is free for open source projects: https://lokalise.com/features/collaborative-translation

**Comment by blanchardjeremy** [comment]
Okay after reviewing the tools out there, Crowdin seems like a great option. Free for open source projects, seems feature-rich. Thanks for finding it, @gyp.

**Comment by beshaya** [comment]
@blanchardjeremy is this done?

**Comment by blanchardjeremy** [comment]
Oh good call. Yep. Closing!
