### ISSUE TITLE
Fix country name for South Korea

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#495]
In our country dropdown it shows up as `Korea, South`

Which leads to it being parsed improperly in the CSV index

![image](https://user-images.githubusercontent.com/32290/98508377-3e02e700-2214-11eb-9a2b-fccba1e5f1ba.png)

Seems like we should just be calling it "South Korea" right? The comma seems odd to me.

**Comment by blanchardjeremy** [comment]
@oremanj could you take care of this one?

**Comment by jy2wong** [comment]
https://github.com/microcovid/microcovid/pull/727 Is this ok?
