### ISSUE TITLE
Provide metric units in addition to imperical ones everywhere

### ISSUE THREAD

**Issue by xuiqzy** [microCOVID/microCOVID#496]
I searched open and closed issues, but could not find a similar issue (expect translation, but the units of measurement are also relevant for the English site).

Currently I see them missing below the "People: How many people are usually near you during this activity?" box where it says "Within 15 feet" and in the drop-down for the distances for the normal socializing distance ("~3 feet apart").
Also in the help text (question mark) for "About 'Number of People'", there are only "x ft spacing" texts.

It would be great to have metric units (centimeter, meter, etc) there in order to reach a broader audience.

**Comment by blanchardjeremy** [comment]
Oh good request. We actually implemented this with #286 ... But it appears we had a regression at some point. 

I wonder if we could automatically detect locale and offer only the relevant metric to the viewer. 

Or we could just offer both to start so we don't delay the implementation.  

We should also write a test for this so it doesn't regress again.
