### ISSUE TITLE
Make Spreadsheet Easier To Grok

### ISSUE THREAD

**Issue by bbqturtle** [microcovid/microcovid#499]
Hello!

A few requests in comments for feedback on what makes the spreadsheet difficult to use. I'm a power excel/sheets user, and I too find it a bit more difficult to use than it needs to be.

I know feedback can be problem centered or solution centered, so I have provided both below.

**Problem centered feedback:**
It's still a little confusing to me how to make a copy - if that could be simplified even further, that would be best. Also, do the case numbers update in copies?
I don't know where to start! The intro? The log? No, it's the location. Wait, I can't just type my location in the log? Why are my only choices in california?
Okay, I got my locations - but there's these three "example" entries here... Okay, I deleted the rows. But now, the calculated cells aren't working!
It tells me my total microcovids - but what does that mean to my budget?

**Solution centered feedback:**
1: Force prompt the "Make a copy" dialogue following this guide or similar: https://support.google.com/docs/thread/5761657?hl=en
2: Consider adding a **direct copy** of the microcovid calculator, laid out in a similar style (IE, Selections all showing on one screen, not in one row, across the entire sheet. Only can input one scenario at a time. At the bottom, after the results, have a prompt for the rest of the spreadsheet "want to log your info over time, use this tab!" (Reason - this will ground people that they understand what's going on after coming from the calculator itself).
3: The sheets should be in the order of inputs, with user inputs made clear. IE, Sheet one: "User inputs" - ask locations and Risk tolerance. Sheet two: "calculator". Sheet 3: "Activity Log w/ Calculator" (remove/hide other tabs) Sheet 4: Customize Variables.  Sheet 5: "About this spreadsheet"
4: For the activity log, just put "Example activity" and only have one row for examples, that _aren't_ used for the total of the activity log. Put a note above the far right columns that says (Calculated cells - do not change).
5: Hide reference sheets - risk variables, activity variables, etc.
6: Either above the activity log or in the prompts, add a user input to choose your budget. Show your current budget, your total budget, and a running falloff of used budget based on the dates in the log.
7. Perhaps add a consolidated "Variables to change" sheet - showing the variables, and changes possible.  (Combining personal risk and activity risk variables).
8. Color code the things that happened in the past as red if it happened over 7-10 days prior. exclude from budget calculation. This would make the log a "rolling log" that you could keep inputting into.

Hope this helps!

**Comment by blanchardjeremy** [comment]
This is a ton of great feedback. Thanks for writing it up! 

Some of this is already in the works but much of it isn't yet. It'll take me a bit to get around to each of these, but I think most of them are great ideas that are obvious wins. 

We'll probably want to separate out each of the ideas we want to implement into separate issues. I can do that once we land on a list.

**Comment by blanchardjeremy** [comment]
@bbqturtle I've got a big pull request underway with "version 2" of the spreadsheet: #626 

I'm going to link this issue with that pull request as I think it may handle most of the issues you've brought up. If you want to suggest specific additional changes, I encourage you to! It'd be best if those were in new, separate issues. 👍

**Comment by blanchardjeremy** [comment]
Fixed with version 2.0 of the risk tracker being released today.
