### ISSUE TITLE
Displays "~.010 microcovids each time" instead of "~.10" sometimes

### ISSUE THREAD

**Issue by hmrm** [microcovid/microcovid#505]
I'm guessing you've got some logic with the number of decimals to display and it doesn't account for rounding up, but I can't find it in the codebase.

**Comment by blanchardjeremy** [comment]
@hmrm could you help us duplicate it by looking to a scenario where that shows up?

**Comment by hmrm** [comment]
Currently https://www.microcovid.org/?distance=normal&duration=12&interaction=oneTime&personCount=1&riskProfile=nonFrontline&setting=outdoor&subLocation=US_53073&theirMask=basic&topLocation=US_53&voice=normal&yourMask=filtered displays the issue. Note that at 13 minutes the issue does not manifest

**Comment by beshaya** [comment]
@hmrm Thanks so much for reporting this! Fix is in review.
