### ISSUE TITLE
Offer "percentage of people wearing masks" option for larger gatherings

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#543]
Inspired by https://mycovidrisk.app and other calculators:

![image](https://user-images.githubusercontent.com/32290/100154817-125e3e80-2e5b-11eb-92b6-2de89d5e500d.png)

It might be useful to offer people the option to select what % of people are wearing masks if the number of people is > 4 or something.

**Comment by oxytocinlove** [comment]
Duplicated by #518

**Comment by blanchardjeremy** [comment]
Closing in favor of the other
