### ISSUE TITLE
Add support for "recent negative test"

### ISSUE THREAD

**Issue by jsrozner** [microcovid/microcovid#566]
Seeing someone who has had a recent negative test means that they have a much lower level of having covid. Something like:

P(false negative test) * (prevalence rate in that class of person) + Prob(contracted since test)

Where P(contracted since test) can be estimated by scaling down the annual risk of that person

**Comment by IWalkInLA** [comment]
The way my household addressed negative tests has been to discount that person's uCV at the time of the test by the false negative rate for a given test, based upon the type of test and the  days one has quarantined prior to the test being taken. 

[Instant Tests have a false negative rate of 15% for the day of the test](https://www.the-scientist.com/news-opinion/false-negatives-in-quick-covid-19-test-near-15-percent-study-67451) , applied to only the day of the test (in my household). 

[It is more complicated for the PCR tests. ](https://www.acc.org/latest-in-cardiology/journal-scans/2020/05/18/13/42/variation-in-false-negative-rate-of-reverse#:~:text=Based%20on%20this%20analysis%2C%20the,COVID%2D19%20will%20test%20negative.) The formula would be (Person's uCV at the time of the test) * (false negative rate based on number of days quarantined prior to test) + (uCV post the test).

Based on the number of days quarantined before the test was taken
- 1 day quarantine: False negative of 100%
- 4 day quarantine: False negative of 68%
- 5 day quarantine: False negative of 38%
- 8 day quarantine: False negative of 20%


(There are more statistics going through day 21, but they are irrelevant when calculating uCV based on days 2-9).

My household has been utilizing testing in three ways. 
- When someone exceeds our weekly individual quarantine threshold. They must be masked/avoid common spaces until they receive a negative PCR test taken on day 8 from when the majority of the activity occurred)
- When someone has had a known contact with a Covid positive person while they were infectious (They must be masked/avoid common spaces until they receive a negative PCR test taken on day 8 post contact, then they may continue the duration of their quarantine within the house unmasked.)
- When trying to make a riskier behavior safer, such as a new partner or wanting to visit family indoors.  That's where the formula comes in handy, but honestly, most of us have been quarantining before  testing through the activity takes place, as we have been wanting to limit our overall risk for these activities.

**Comment by beshaya** [comment]
Hi @jsrozner, have you seen our recent blog post on this topic? https://www.microcovid.org/blog/negativetests. Someone who gets a negative test back with a 2 day turnaround time is only 25% less likely to have COVID. That's about 1/4 as effective as wearing a cloth mask or running a HEPA filter.

The way @IWalkInLA's house uses tests sounds pretty solid - testing in combination with quarantining (or jus quarantining) significantly reduces risk.

**Comment by beshaya** [comment]
Closing this since our policy is to only include multipliers with magnitude of 2x or more.
