### ISSUE TITLE
US Positive Test Rates not syncing

### ISSUE THREAD

**Issue by IWalkInLA** [microcovid/microcovid#573]
In the [Calculator](https://www.microcovid.org/?distance=sixFt&duration=20&interaction=oneTime&personCount=5&riskProfile=average&setting=indoor&subLocation=US_06037&theirMask=basic&topLocation=US_06&voice=silent&yourMask=filtered), the US Positive Test Rates do not appear to be syncing properly from [Covid Act Now](https://covidactnow.org/us/ca/county/los_angeles_county?s=1436400) , as all the positive test rates on the microcovid calculator in California are listed as 3.3% and have been so for weeks, where currently Los Angeles is13.6% and San Francisco is 2.5%.  

Looking at the automated spreadsheet  location data, positive test rate do not appear to be an included factor and it matches the calculation of estimated prevalence rate in the calculator (5.57% for Los Angeles).

**Comment by blanchardjeremy** [comment]
@IWalkInLA Thanks for drawing this to our attention. Super helpful!

We noticed that we're using an older version of their API.

@oremanj is going to take a look at it soon and see about pulling in detailed county-level info.

**Comment by IWalkInLA** [comment]
Awesome!

**Comment by beshaya** [comment]
It's not just positive test data - all our CovidActNow data (which is the entire USA) isn't getting updates.

**Comment by oremanj** [comment]
We don't rely on covidactnow for anything other than positive test rates. We get cases from JHU. I don't see any evidence that we're failing to update case rates -- if you do, could you clarify?

**Comment by beshaya** [comment]
Ah, you seem to be right. That's a relief.
