### ISSUE TITLE
Change distances to be "6+ feet"

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#583]
> I have gotten the feedback multiple times from folks that when they see ">6 feet" as an option (on the spreadsheet or the website) they think that if they are about 6 feet, they aren't allowed to use that category. They think they need to be like 7 feet or more. I wonder if we changed it to "6+ feet" instead if that would be clearer for users. What do you think? (I've got this on my checklist of things to consider before launching the new spreadsheet)

**Comment by IWalkInLA** [comment]
I think "6+ feet" is a little easier for the public to understand;  think of someone that has been out of school for a while and is working in an non-technical field, relational operators might be something they have to actively recall.

**Comment by blanchardjeremy** [comment]
@IWalkInLA I'd love your input on the pull request: #585 

Thanks!
