### ISSUE TITLE
Erroneous Test Positivity Rate

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#588]
All regions of CA on the Calculator show 3.3% tests coming back positive. This does not match covidactnow:

![image](https://user-images.githubusercontent.com/5877421/102682603-a633d980-417f-11eb-9de1-a74fa3177622.png)

![image](https://user-images.githubusercontent.com/5877421/102682608-b51a8c00-417f-11eb-8646-015b60f593b6.png)

This is getting imported into spreadsheets as well. The error is fairly significant; 15% test positivity rate raises the underreporting factor by 1.4 compared to 3%

**Comment by IWalkInLA** [comment]
It's wrong for the entire US, per my post with #573 .

**Comment by beshaya** [comment]
@IWalkInLA yup, I see that now. These are, incredibly, entirely separate bugs.

I'm fixing them both.
