### ISSUE TITLE
It is hard to see how to enter specific prevalence data once you have selected a location already

### ISSUE THREAD

**Issue by david-mears** [microcovid/microcovid#60]
On the calculator, the initial state allows you to enter your own prevalence data, e.g. if you know about your local area and want to use that more accurate data.

However, if you select a location, it is very difficult to see how to then revert your decision, and input your own data. Originally, when making this issue, I believed it was impossible to revert your decision. I had been going to complain that because the form selection is persisted between page reloads, you cannot get around this by reloading the page.

However, I have since found that clicking on 'Select location or enter data' in the first of the two location drop-downs allows me to enter my own data.

It's not just me who has found it difficult to find the way to revert the decision. I shared the site with my partner (while telling her not to share it on further) yesterday, and she commented on this (unsolicited):

> it's a shame microcovids doesn't let you have more granularity than 'England'. It would be good if i could enter cases in Hackney or London  + population, because i'm guessing the risk that the calculator outputs will be 'diluted' by all the less-risky parts of england

> i get that they can't have access themselves to data for everywhere in the world, but it looks like i ought to be able to adjust the pop and case numbers myself, but I can't.

I suggest adding a button saying 'Fill in own data' which has the same effect as clicking 'Select location or enter data'. I most likely will not have time to make this button myself before launch.

**Comment by beshaya** [comment]
Good point, David. We should add a button to clear the location data, but we honestly might not get to that for a while. If you wanted to send a PR for that over, we'd be happy to take it.

In the meanwhile, here are two workarounds:
* hit "reset"
* set the location to "Select location or enter data..."
