### ISSUE TITLE
Update model to include new strain infectiousness estimates

### ISSUE THREAD

**Issue by orborde** [microcovid/microcovid#605]
A new strain with substantially higher infectiousness seems to have emerged. [[1]](https://thezvi.wordpress.com/2020/12/24/covid-12-24-were-fed-its-over/) [[2]](https://putanumonit.com/2020/12/26/seeing-the-new-covid-variant-smoke/)

It would be great to include the risk of infection posed by this new strain in the model.

Since we may not have good numbers on the relative prevalence of different strains for a while, perhaps there could be a switch in the UI for whether to assume the new strain vs. the original? I know it's a total hack to include extra tuning knobs like this, but, speaking as a power user, such a switch would definitely meet my needs.

**Comment by blanchardjeremy** [comment]
Thanks for raising this. I've brought this to the attention of the team so we can discuss how we want to approach it.

**Comment by blanchardjeremy** [comment]
Closing this in favor of #617
