### ISSUE TITLE
Show "no cuddling bonus" for all environment types

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#607]
When close/kissing is selected, our current logic doesn't give any bonuses for any environment type (airplane, HEPA filter, train, etc). This notice shows when "outdoor" is selected:

![image](https://user-images.githubusercontent.com/32290/103235913-22ed5300-48f8-11eb-829e-3a03dcba53df.png)
Link: https://www.microcovid.org/?distance=close&duration=15&interaction=oneTime&personCount=1&riskProfile=average&setting=outdoor&subLocation=US_06075&theirMask=none&topLocation=US_06&voice=normal&yourMask=none

But It's not shown for any of the other environment types.

![image](https://user-images.githubusercontent.com/32290/103235947-36002300-48f8-11eb-8e23-7f9b6910cbd1.png)
Link: https://www.microcovid.org/?distance=close&duration=15&interaction=oneTime&personCount=1&riskProfile=average&setting=plane&subLocation=US_06075&theirMask=none&topLocation=US_06&voice=normal&yourMask=none

We should show it for all the

Also, it needs to be shown in the "calculation explanation" section below, I think.

**Comment by beshaya** [comment]
Handled by #644
