### ISSUE TITLE
Add support for Romanian counties

### ISSUE THREAD

**Issue by ruxandra-valcu** [microcovid/microcovid#616]
The infection rates in Romanian counties tend to vary a lot, so it would be very useful to us if you could make a per-county view. We are providing daily new cases per county data as a JSON api at https://covid19.geo-spatial.org/external/charts_vasile/assets/json/cazuri_zile_long.json - 4 fields, Data is data in YYYY-MM-DD format, Judet is county, Cazuri total is total cases and Cazuri noi is new cases. 

Unfortunately per-county testing data isn't available, but I've noticed that for e.g. Russia you're using the country test rate as a proxy, so if you could do that here as well, it should be as good as it gets given public info.

Thank you very much for working on this, and let me know if there's anything we can help with!

**Comment by jy2wong** [comment]
Hi Ruxandra,

I filed this recently for data from the ECDC. I didn't see Romania unfortunately. Taking a look at the JSON file you linked to, I think we would need more information to incorporate it into the calculator.

The data that would make it easiest to support Romanian counties is:
* date
* county name
* daily 7-day prevalence (number of new cases in the last 7 days divided by total population)

Note that the ECDC dataset divides number of new cases in the last 14 days per 100k inhabitants. This is also acceptable (though we would prefer "number of new cases in the last 7 days per 100k inhabitants").

https://github.com/microcovid/microcovid/issues/711

**Comment by ruxandra-valcu** [comment]
Hello! 
I've updated the JSON to include daily 7-day and 14-day (in case you need it) prevalence per 100k
{
        "Data": "2020-04-02",  //date
        "Judet": "Alba", //county
        "Populatie": 323778, //population
        "Cazuri total": 9, //total number of cases
        "Cazuri noi": 0, // daily cases
        "Cazuri noi 7 zile": 0, //new cases in the last 7 days
        "Cazuri noi 14 zile": 0, //new cases in the last 14 days
        "Incidenta 7 zile/100k": 0, //incidence per 100k inhabitants in the last 7 days
        "Incidenta 14 zile/100k": 0 //incidence per 100k inhabitants in the last 14 days
    }

Thank you!

**Comment by jy2wong** [comment]
Thanks for the quick update! Turns out I didn't need the 7/14 days data, but I *did* need the population data you included in that update as well.

I've done a quick check, but can you test this out too?
https://deploy-preview-715--microcov.netlify.app/

**Comment by ruxandra-valcu** [comment]
Thank you, looks good - does this mean we can remove the 7/14 days data from the json (new cases in the last X days + incidence, or just incidence)? It's feeding off a manually updated spreadsheet so I'd rather keep it as simple as possible. 
Forgot to mention, but the source of this data is the geo-spatial.org community - https://covid19.geo-spatial.org/despre would be a good credit link. We'll let you know if we ever manage to get per-county testing data (the government doesn't currently release it, unfortunately).

**Comment by jy2wong** [comment]
> Thank you, looks good - does this mean we can remove the 7/14 days data from the json (new cases in the last X days + incidence, or just incidence)? It's feeding off a manually updated spreadsheet so I'd rather keep it as simple as possible.
> Forgot to mention, but the source of this data is the geo-spatial.org community - https://covid19.geo-spatial.org/despre would be a good credit link. We'll let you know if we ever manage to get per-county testing data (the government doesn't currently release it, unfortunately).

Yes, you can safely remove

"Cazuri noi 7 zile": 0, //new cases in the last 7 days
"Cazuri noi 14 zile": 0, //new cases in the last 14 days
"Incidenta 7 zile/100k": 0, //incidence per 100k inhabitants in the last 7 days
"Incidenta 14 zile/100k": 0 //incidence per 100k inhabitants in the last 14 days

**Comment by blanchardjeremy** [comment]
Shout out to both of you for making this happen! Thanks!!

**Comment by ruxandra-valcu** [comment]
Thank you as well!
Btw, sorry to bug, but the Region field no longer shows up when selecting Romania (either in the preview linked in this thread or on the main site). It used to show up yesterday, so looks like there may be a bug somewhere?

**Comment by jy2wong** [comment]
Oh! I'm sorry, I took the prevalence update out of the changes here to separate the "look for this new data" part from the "use this new data for the calculator" part, but forgot to do the second part. It should now be available!

https://github.com/microcovid/microcovid/pull/726
