### ISSUE TITLE
Research Intake: Effects of new variant

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#617]
https://www.medrxiv.org/content/10.1101/2020.12.24.20248822v1.full.pdf

**Comment by beshaya** [comment]
> Our estimates suggest that control measures of a similar stringency to the
national lockdown implemented in England in November 2020 are unlikely to reduce the
effective reproduction number Rt
 to less than 1,
 
 (for reference, Nov lockdown allows is similar to spring lockdown, but exempts education https://www.bbc.com/news/uk-54763956)

Unlikely to be due to regional differences in people's behavior
> we did not find evidence of differences in social interactions between regions of high and low VOC 202012/01 prevalence, as measured by Google mobility

note that this study considers shorter generation time as shorter time to infectiousness AND shorter time to recovery; I think this leaves out the case of shorter time to infectious w/o changing time to recovery.
> we considered four alternative hypotheses for why the new variant might be
spreading more efficiently: increased infectiousness; immune escape; increased susceptibility
among children; and shorter generation time.

The best model was increased contacts infected.
> The fitted model based upon increased transmissibility, which reproduces observed
epidemiological dynamics and increases in relative prevalence of VOC 202012/01 (Figs. 3, S3),
suggests no clear evidence of a difference in odds of hospitalization or relative risk of death, but
finds strong evidence of higher relative transmissibility (Fig. 2A), estimated at 56% higher than
preexisting variants (95% CrI across three regions: 50-74%).

The best model also predicts nearly 100% of infections will be the new variant by mid January:
![image](https://user-images.githubusercontent.com/5877421/103468118-b1a00c80-4d0a-11eb-9ece-192835c68250.png)

Using this model, they predict that doing a full lockdown + vaccinating 200k people per week is necessary to bring deaths in 2021 to the same numbers as 2020.
![image](https://user-images.githubusercontent.com/5877421/103468234-c16c2080-4d0b-11eb-8b04-eea96aef8282.png)

The increased prevalence of VOC 202012/01 is not well explained by differences in reporting:
> Mathematically, if variant 1 has growth rate r1 and variant 2 has growth rate r2, the relative frequency over time is exp(r2 * t) / (exp(r1 * t) + exp(r2 * t)). However, if variant 1 has probability x of being reported and variant 2 has probability y, and both have
growth rate r, the relative frequency over time is y exp(r*t) / (x exp(r*t) + y exp(r*t)), which is constant.

Aside, a possible reason for hospitalization/fatality rates not going up is that the variants includes a mutation that was found to reduce the severity of the infection (https://en.wikipedia.org/wiki/Variant_of_Concern_202012/01):
> Genetic sequencing of VOC-202012/01 has shown a Q27stop mutation which "truncates the ORF8 protein or renders it inactive".[12] An earlier study of SARS-CoV-2 variants deleted of the ORF8 gene noted that they "have been associated to milder symptoms and better disease outcome".[40] 

# My takeaways / recommendation for microCOVID
* The increased prevalence of VOC 202012/01 is best modeled by a 56% increase in # of contacts infected. This can be implemented in microCOVID by multiplying all activity risks (including caps) by 1.5.
* The projection of growth (2 months from introduction to nearly universal prevalence) suggests that attempting to model the % of cases that are cause by older variants will rapidly become obsolete, so I don't recommend doing the work to include this in the model (we also don't know how much community spread of the variant we already have in CA, except that the variant has been identified in California and is believed to be community spread https://www.sfchronicle.com/health/article/New-highly-contagious-coronavirus-strain-arrives-15837064.php).
* There may be more nuanced changes to make in the future, especially to the spreadsheet, if this turns out to affect the asymptomatic transmission rate, presymptomatic transmission time (which would reduce the effectiveness of symptom free and will report symptoms).
* There is no reason to adjust the yearly allowance based on this data, since VOC 202012/01 does not appear to increase the severity of infection.
* The increase in housemate/partner transmission may be cancelled out by our existing multipliers (0.3 and 0.48) being overestimates based on https://github.com/microcovid/microcovid/issues/606 which suggests household/partner multipliers of 0.2 and 0.3 respectively.

**Comment by beshaya** [comment]
Above I mention that it is possible that the housemate and partner caps may not increase by the full 56%. It's worth noting that the household transmission rates may be _more_ than 56% higher for VOC 202012/01. Until housemate studies are repeated with the new this variant, we really don't know what the household transmission rate is 😬.

**Comment by blanchardjeremy** [comment]
@beshaya My two cents: I'm not skilled in epi stuff, but it seems wise to me to not consider bringing our household/partners numbers down as suggested in #606 given how infectious the new strain is. I'd rather err on the side of caution until we have some data to demonstrate the household transmission rate. But as always, I'll defer to you and others on the team in this domain since it's not my area of expertise.

**Comment by mattbell** [comment]
I read through this paper as well as the high level technical policy summary at https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/948152/Technical_Briefing_VOC202012-2_Briefing_2_FINAL.pdf

I agree with Ben's proposal that we do an immediate increase in all microcovid numbers, including caps, by 56%.  
Acting early on the exponential curve for the new variant buys us time.  Some people on epi twitter were estimating that most of the US cases could be the new variant by the end of March, and if we can push that later by a month or two, that means we can vaccinate a lot more people.  

I also think this deserves a blog post laying out why people should take note of the new variant and its impact on our behavior.

**Comment by catherio** [comment]
addressed in https://github.com/microcovid/microcovid/commit/56d275ea45818c5e9df075be37549679e1c9a988

will move the housemate number discussion over to https://github.com/microcovid/microcovid/issues/617
