### ISSUE TITLE
When choosing combination of kissing and loud speaking the risk is multiplied

### ISSUE THREAD

**Issue by kubantjan** [microcovid/microcovid#620]
When I at the same time select kissing and loud speaking those two scores get multiplied and I get extreme score.

I guess I should get this extreme score also if I only select kissing, because no matter how loud I speak the transmission is very likely

Or am I wrong? It certainly seems weird that kissing with hushed voices would mean so much less risk then kissing with shouting.

![Screenshot from 2021-01-05 22-08-08](https://user-images.githubusercontent.com/24394374/103699162-d2828f00-4fa2-11eb-8282-0a2a89176b46.png)

**Comment by blanchardjeremy** [comment]
This is a good thing to notice. If it's kissing, it seems like we should just ignore the volume field altogether.

**Comment by jy2wong** [comment]
Jeremy, can I counterpropose taking the worse of the volume and kissing multipliers? I think kissing + loud talking should be treated as loud talking and that kissing + no talking should be treated as kissing.
