### ISSUE TITLE
Grocery shopping scenarios are way too cautious

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#649]
I think modeling a trip to the grocery store as being near 10 people for an hour is way too cautious. Am I understanding it right that this is saying you're 6-10 feet from an average of 10 people at a time for a total of an hour? You might spend an hour in the store, but how much time are you within 15 feet of another human? I would say in an average store on an average day I'm within 15 feet of another human for maybe about 10 minutes cumulatively, and in those 10 minutes I'm rarely that close to more than one or maybe two humans at a time. It seems to me that modeling a grocery trip as 10 or 15 minutes 6 ft away from 2 or 3 people would be far more accurate and still erring on the side of caution. Just my (hopefully appropriately humble) opinion. Please correct me if I'm misunderstanding how this works.

**Comment by blanchardjeremy** [comment]
It all depends on the grocery store. In the grocery store we go to in Berkely, CA, it's VERY full most of the time, so this is an accurate modeling. 

We added two grocery scenarios to the calculator (and spreadsheet) recently to help represent these options. One is with 5 people and one is with 10 people. 

This is how we calculate 10 people 6 feet away:
![image](https://user-images.githubusercontent.com/32290/104669690-751bcb80-568f-11eb-963c-ea248f0c7bcd.png)

Did you see the second grocery option on the predefined scenarios (with 5 people 6 ft away on average)?

**Comment by linesarefuzzy** [comment]
Interesting. I did see the "few other shoppers" option, but I think it's still a large overestimate for an average grocery trip in the places I've been shopping (small to large cities around the Northeast and Mid-Atlantic). Maybe the 10-person one should be called "crowded store." I would change the "average # of shoppers" preset to maybe 3 people 6 ft away for 15 minutes. If I'm the only one who feels this way, I'm happy to defer to your team. I do appreciate the ease of adjusting the numbers after selecting a preset on the calculator, and the visibility of the message encouraging users to do so! Perhaps something should be added to the spreadsheet documentation about how to edit the presets there as well.

**Comment by beshaya** [comment]
I agree with @linesarefuzzy - 10 people is too many for an "average" case. FWIW, Josh usually records 5 nearby people at 6 feet for his Berkeley Bowl shopping trips.

Average should probably be 5, few shoppers 3, crowded 10.

**Comment by blanchardjeremy** [comment]
I'm behind @beshaya's proposal of 10/5/3.

**Comment by blanchardjeremy** [comment]
Ive changed it in the spreadsheet to match this approach.
