### ISSUE TITLE
Add kissing to spreadsheet

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#651]
There's a kissing option on the calculator that has some special rules—the outdoor bonus doesn't apply, and there's a minimum activity risk. That's great! But there's no kissing option on the spreadsheet. Just "close," which doesn't have any special rules about fluid exchange.

**Comment by linesarefuzzy** [comment]
I went ahead and added this on my own copy of the spreadsheet. It's pretty simple. Here's what I did: 

1. In `'INTERNAL_ACTIVITY'!E23:F23`, enter `💋 Kissing` and `2`
2. Add a named range called `ACTIVITY_TITLE_KISSING` pointing to `'INTERNAL_ACTIVITY'!E23`
3. In `'Pod Activity Log'!V3`, change the formula to:
```
=IF(
 OR(
  L3="",
  AND(
   L3=ACTIVITY_TITLE_ONE_TIME,
   M3="", N3=""
  )
 ), "",
MIN(
 IF(L3<>ACTIVITY_TITLE_ONE_TIME, 1E+99,
 IF(R3=ACTIVITY_TITLE_CUDDLING,
    INTERNAL_ACTIVITY!$B$4,
    INTERNAL_ACTIVITY!$B$3
 )),
 VLOOKUP(L3, ACTIVITY_RISK_TABLE_INTERACTION, 2, FALSE)
*IF(
 L3<>ACTIVITY_TITLE_ONE_TIME, 1,
 IF(R3=ACTIVITY_TITLE_KISSING,
    MAX(1, (M3+N3/60)),
    (M3+N3/60)
 )
*IF(OR(O3="", R3=ACTIVITY_TITLE_KISSING), 1,
    VLOOKUP(
      IF(AND(R3=ACTIVITY_TITLE_CUDDLING,
             O3=ACTIVITY_TITLE_OUTDOOR),
         ACTIVITY_TITLE_ALMOST_OUTDOOR,
         O3),
ACTIVITY_RISK_TABLE_ENVIRONMENT, 2, FALSE))
*IF(S3="", 1,
    VLOOKUP(S3, ACTIVITY_RISK_TABLE_VOICE, 2, FALSE))
*IF(P3="", 1, 
    VLOOKUP(P3, ACTIVITY_RISK_TABLE_MASK, 2, FALSE))
*IF(Q3="", 1,
    VLOOKUP(Q3, ACTIVITY_RISK_TABLE_MASK, 3, FALSE))
*IF(R3="", 1,
    VLOOKUP(R3, ACTIVITY_RISK_TABLE_DISTANCES, 2, FALSE))
)))
```
4. Copy that formula down to the bottom of column V

**Comment by blanchardjeremy** [comment]
Oh yay! Thank you so much for doing this.

Correct, there are no pull requests. But I will implement it before launching the new version. 🙏

**Comment by linesarefuzzy** [comment]
I forgot a step: 

5. Also copy that formula to column V of the Custom People sheet.

**Comment by blanchardjeremy** [comment]
Implemented! 🙌
