### ISSUE TITLE
Incorrect column headers on Custom People sheet

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#652]
The headings are in the same order as in the Pod Activity Log sheet, but the values are shifted:

![image](https://user-images.githubusercontent.com/1829213/104854807-d5507e80-58d6-11eb-9b34-f390cc620227.png)

**Comment by blanchardjeremy** [comment]
Really good catch. Thanks! I'm on it!

**Comment by blanchardjeremy** [comment]
Now fixed in the latest spreadsheet v2  beta
