### ISSUE TITLE
Revisit "Symptom Free" multiplier

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#664]
The public spreadsheet currently provides 0.5x person risk to people who do not have symptoms. Where does this come from? Does it need to be updated? Should it apply to housemates?

**Comment by beshaya** [comment]
@oremanj provided context that this is based on a bayesian update on the knowledge that a person is not symptomatic.

**Comment by beshaya** [comment]
@jy2wong and I dug into this and wrote out math that suggests a multiplier of 0.52 to 0.63:

https://docs.google.com/document/d/1MKl4jYheEPJ6tJZMm4bZS1MoOnQS7tgBBdsOE3gf5lk/edit

**Comment by beshaya** [comment]
Also suggested a decay function for symptom-free risk rather than a 10 day window.

**Comment by blanchardjeremy** [comment]
This will be resolved by #677

**Comment by catherio** [comment]
This can't be closed yet until it's documented in the white paper

**Comment by catherio** [comment]
Can someone explain what's up with P(Infections - lognorm asymp) vs. P(Infectious)? It's not in the [whiteboard](https://docs.google.com/document/d/1MKl4jYheEPJ6tJZMm4bZS1MoOnQS7tgBBdsOE3gf5lk/edit#)

**Comment by catherio** [comment]
is this still accurate or is it obviated by the fancy decay function? 

![image](https://user-images.githubusercontent.com/245037/106436953-93245280-6429-11eb-90b5-cac0988a33a5.png)

**Comment by catherio** [comment]
in the Whiteboard writeup, want to make sure I understand “It is inappropriate to use it to compute Risk to Self from housemates.” => doesn’t this mean it should not be applicable in one’s Risk Tracker row for  non-one-off partner/housemate interactions, too? (cc @blanchardjeremy )

**Comment by catherio** [comment]
Not sure how we wanna kanban this back-and-forth, but I shifted it back as the ball's not in my court right now

**Comment by catherio** [comment]
Note to self whitepaper draft is here: https://paper.dropbox.com/doc/Infectious-Period-Reworked--BEIUbq7OUP5lFKWDoXTRsAwBAg-34ubQbDINkSgcCup3UxVX

**Comment by beshaya** [comment]
@catherio it looks to me like this is in a "LGTM % nits state", which you might want to represent by moving this to the "Approved" (which is intentionally not labelled "Done")

**Comment by catherio** [comment]
yes! sry! ty for the ping! defer to you on all further updates here
