### ISSUE TITLE
Mask Overhaul

### ISSUE THREAD

**Issue by beshaya** [microcovid/microcovid#666]
https://docs.google.com/document/d/18_cQiCZFwT3RsXQayrpsYy4QZ39ir2_RRHTFwDEl4yM/edit

**Comment by catherio** [comment]
👍  to these numbers as final

I need to write these up for research sources and make a PR for calculator

**Comment by catherio** [comment]
closed by https://github.com/microcovid/microcovid/pull/688 !!
