### ISSUE TITLE
Decrease friction for preset scenario exploration

### ISSUE THREAD

**Issue by jy2wong** [microcovid/microcovid#674]
The typeahead for activity presets lets people search by typing (great!) but also requires people to clear the search term before being able to look around at other presets (not great).

**Comment by beshaya** [comment]
@jy2wong can this be closed?

**Comment by jy2wong** [comment]
The original issue is fixed, but the cache miss scenario could use some smoothing. Would you be interested in figuring out how to allow the enter key to "work" in cases where the "no scenario found; build your own" message pops up, but without interfering with the existing stuff that makes the enter key select a scenario if it's the only possibility left?
