### ISSUE TITLE
Masks link on the front page alert doesn't go to the anchor

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#709]
For some reason, when I click "White Paper" it doesn't jump me down to the masks section. It only works if I open the link in a new tab.

![image](https://user-images.githubusercontent.com/32290/106402296-b0333400-63dd-11eb-9a04-7d320aa17d9e.png)

**Comment by oxytocinlove** [comment]
@blanchardjeremy IIUC this is now irrelevant because that alert is no longer present?

**Comment by blanchardjeremy** [comment]
Yep!
