### ISSUE TITLE
Replace N95 supplier with poor reputation in masks post

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#717]
apparently one of our sources for N95s in the mask post has a reputation as "a scalper website". we don't want to link to sites with a poor reputation.

another twitter commenter suggests "grainger and msc direct" have a better reputation.

we should remove the site with a poor reputation (still waiting to find out which it is, or maybe we can figure it out ourselves?) and replace it

**Comment by catherio** [comment]
"wellbefore is the one i have issues with."

listed as more reputable: "Grainger, MSC, McMaster, Digikey, etc - /when they're in stock/."

okay: "that respokare site wants $10/ea [...] but it appears they're actually manufacturing their own"

we don't need to take a moral position on profiteering here, we just need to provide our readers with all the information, and to show some sensitivity to that the reselling question is a live issue here.

**Comment by catherio** [comment]
user cites https://castlegrade.com/ as being especially good

**Comment by blanchardjeremy** [comment]
Tagging @mattbell -- is this something you wanna be point on? Or should we find another point person?

**Comment by mattbell** [comment]
I'm testing the new suppliers before putting them on.  

Grainger masks arrived today and are legit (but valved).  I put in an order from MSC direct as well.  Unless it’s urgent I’m going to wait till those arrive and are found to be legit before updating the site.  Basically I don’t want to give these people $thousands in business before I try the product myself.

Unless y'all think it's urgent I'm going to wait until I check these new masks out and then I'll make the change.

**Comment by blanchardjeremy** [comment]
Sounds fine to me. Doesn't feel urgent. Thanks for testing! That's some high quality service!

**Comment by mattbell** [comment]
Lol, I now have $250 in masks but the suppliers have both been vetted. :-)

**Comment by jy2wong** [comment]
Can this be closed now that https://github.com/microcovid/microcovid/pull/737 is in?

**Comment by blanchardjeremy** [comment]
I say yes.
