### ISSUE TITLE
Remove healthcare worker from Risk Tracker

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#720]
See #718

**Comment by catherio** [comment]
and the white paper Intermediate Method, yeah?

**Comment by blanchardjeremy** [comment]
The Intermediate Method was already removed in #718 

![image](https://user-images.githubusercontent.com/32290/106838244-c1d04200-6650-11eb-9f6d-e8ede694609c.png)

**Comment by blanchardjeremy** [comment]
I removed this with the most recent update.
