### ISSUE TITLE
Person Risk Page links to removed intermediate method

### ISSUE THREAD

**Issue by springfielddatarecovery** [microcovid/microcovid#746]
Page: https://www.microcovid.org/paper/6-person-risk
Broken link is in this sentence, IIRC the intermediate method has been removed entirely "The Intermediate Method adds adjustments for whether the person is or isn’t an essential worker."

PS Sorry to make so many issues in a row instead of batching them together, I didn't think I'd come across more than one

**Comment by blanchardjeremy** [comment]
Thanks for submitting this. Good catch!
