### ISSUE TITLE
"20 microCOVIDs (or 0.00002%)" -- percent is 100x too small

### ISSUE THREAD

**Issue by BillZito** [microcovid/microcovid#771]
On the home page under "What is a microcovid," I'm pretty sure the percent for 20 ucovids is 100x too small (should be 0.002% instead of 0.00002%, because the percent sign accounts for 2 zeroes). Thanks for all of your great work :).

**Comment by blanchardjeremy** [comment]
Oh that's a really good call. I think you're right. Maybe @beshaya or @jy2wong has a moment to fix this?

**Comment by jy2wong** [comment]
Whoops! Thanks for pointing it out!

**Comment by blanchardjeremy** [comment]
@gyp Perhaps you can manually update this in all the active translations? So we don't have to wait for the translators to do it?

**Comment by gyp** [comment]
> @gyp Perhaps you can manually update this in all the active translations? So we don't have to wait for the translators to do it?

Done. Most translations are lagging so much behind that they didn't even have this.
