### ISSUE TITLE
In Q&A "fit test" has wrong link (and I don't know the right one)

### ISSUE THREAD

**Issue by hmrm** [microcovid/microcovid#783]
In this paragraph:

> But remember, these masks are only effective if you get a tight seal around your face! Just “wearing an N95” doesn’t protect you all the way. We have seen a friend of ours “wear an N95” that was much too big for their face, leaving a big gap under their chin. Other friends have worn an N95 over a beard, but facial hair definitely prevents a good seal. One study shows that even a pair of tiny points of leakage a couple of millimeters in diameter dramatically increases the number of aerosol particles that can pass through a high quality mask. Please do a fit test and watch some online training in order to effectively use your N95.

The link from "fit test" appears to incorrectly be set to the same target as the link from "One study".

**Comment by beshaya** [comment]
Thanks for the catch. Fix in progress.
