### ISSUE TITLE
Long-term health risks to otherwise young, healthy people

### ISSUE THREAD

**Issue by NickHeiner** [microcovid/microcovid#786]
The key question for my risk budget is what the long-term health risks are for a 30-something person like myself who is in otherwise good health.

These two notes in the whitepaper are apparently contradictory (emphasis mine):

> Additionally, we have seen [data](https://pubs.rsna.org/doi/full/10.1148/ryct.2020200110) suggesting that asymptomatic COVID-19 could result in lung damage in <ins>**half of cases**</ins>.

> We think as many as 1 in 10 COVID cases could potentially lead to long-term negative health consequences for the infected person; we don't think the ratio is likely to be higher than that, due to sources like the app-based [COVID Symptom Study](https://covid.joinzoe.com/post/covid-long-term) that found <ins>**one in ten cases**</ins> weren't fully recovered after 3 weeks. 

I thought the "glass lung" effect was permanent. Does it recover over three weeks? 

Separately, the COVID Symptom Study writes:

> Experts have recently warned that COVID-19 may cause lasting damage to other internal organs, including the lungs, liver, brain, and kidney. This may explain why some people continue to experience symptoms long after the virus has been cleared from the body.

Is it possible that this lasting damage is under-reported? Like, if your heart is damaged, then your long-term risk of stroke increases, but there are no daily symptoms, so this self-reporting app wouldn't detect it. 

I don't know what this means for the recommendation you make to people. I'm wondering if stating "90% chance you'll be fine after 3 weeks" is painting too rosy a picture and there's more risk that needs to be communicated.

**Comment by beshaya** [comment]
> I thought the "glass lung" effect was permanent. Does it recover over three weeks?

No one is saying it recovers in 3 weeks, the paper says its _not_ recovered after 3 weeks. It might eventually recover. Definitely a place where there should be more detailed research by now.  We'd be happy to update this if you found a study that has a solid methodology (I did a quick literature skim a few months ago and didn't find anything useful).

>I'm wondering if stating "90% chance you'll be fine after 3 weeks" is painting too rosy a picture and there's more risk that needs to be communicated.

Personally, I consider 1-in-10 chance of permanent lung damage a pretty big risk. Basically a round of Russian Roulette, and I don't think anyone would call russian roulette "safe." Especially when compared to the death rate of 30-somethings, which is more like 1-in-1000.

**Comment by henryaj** [comment]
My intuition is actually the opposite here – people not being recovered after three weeks isn't that concerning. COVID comfortably lasts two weeks; 'three weeks' seems far too early to conclude that someone has long-term negative health effects (which the 1% risk per year default seems to rely on).

**Comment by beshaya** [comment]
https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/bulletins/prevalenceofongoingsymptomsfollowingcoronaviruscovid19infectionintheuk/1april2021

> Among a sample of over 20,000 study participants who tested positive for COVID-19 between 26 April 2020 and 6 March 2021, 13.7% continued to experience symptoms for at least 12 weeks. This was eight times higher than in a control group of participants who are unlikely to have had COVID-19, suggesting that the prevalence of ongoing symptoms following coronavirus infection is higher than in the general population.

**Comment by beshaya** [comment]
Would be great if you could open a quick PR for that section. A lot of this
data is just dropping now and we're working on a bigger, more cohesive
update that may take a little while longer.
