### ISSUE TITLE
Risk Tracker: Activity Log sheet can't properly lookup vaccine info for unalphabetized Pod members

### ISSUE THREAD

**Issue by evansiroky** [microcovid/microcovid#806]
In v2.2 of the risk tracker in the `📋 Activity Log` sheet in columns `G`, `H` and `I` there are `HLOOKUP` functions that do not have `false` as the 4th argument. This implies that the header row of the lookup range contains sorted keys. However, this function looks for headers in a range that a user can manually input and therefore it cannot be guaranteed that the keys will be sorted [which results in incorrect values](https://support.google.com/docs/answer/3093375?hl=en). I fixed this in my sheet by adding the `false` value as the 4th argument in every `HLOOKUP` function in columns `G`, `H` and `I`.

**Comment by blanchardjeremy** [comment]
Hi @evansiroky ! Thank you so much for drawing this to attention! I just put in a quick fix so no one else encounters this bug. I'll publish a proper changelog update soon!
