### ISSUE TITLE
Add activity for when you've had a negative test beforehand

### ISSUE THREAD

**Issue by Nathanpmyoung** [microcovid/microcovid#807]
It would be good to have an option to do an activity where you or the others have had a negative test beforehand.

**Comment by beshaya** [comment]
https://www.microcovid.org/blog/negativetests

The effect of a perfectly timed test is really small, so much that it doesn't feel worthwhile to me to add the ux for it. I suppose there's some value in showing that the effect is small, but it is also hard to communicate how sensitive this is to timing.

Incidentally, I had a friend ask me about rapid tests today - I dug up the data on the rapid test sold at CVS:
> Compared with real-time RT-PCR testing, the BinaxNOW antigen test had a sensitivity of 64.2% for specimens from symptomatic persons and 35.8% for specimens from asymptomatic persons

35.8% specific roughly reduces risk by 35.8% on the day it is taken.

**Comment by beshaya** [comment]
That's a popular theory, but I've never seen evidence for it. Would be
willing to take a look if you found research suggesting one way or another.

We have seen research that shows that, upon onset, people seem to go from
not contagious at all to maximally contagious in the span of 12-24 hours
before symptoms show up, so even if this were the case, the test wouldn't
tell you much about their contagiousness a few hours later.

One of the microCOVID team members likes to buy anitgen tests and
self-administer them right before events. I don't put much stock in it, but
it makes some people feel better, which is perhaps a worthwhile goal.

I did a bit of a dive for a friend recently:
https://www.cdc.gov/mmwr/volumes/70/wr/mm7003e3.htm#:~:text=Compared%20with%20real%2Dtime%20RT,in%20specimens%20from%20both%20groups
.
"Compared with real-time RT-PCR testing, the BinaxNOW antigen test had a
sensitivity of 64.2% for specimens from symptomatic persons and 35.8% for
specimens from asymptomatic persons, with near 100% specificity in
specimens from both groups."

So for people not showing symptoms, the test gave false negatives 65% of
the time.
