### ISSUE TITLE
C125 Pod Overview; 8 instead of 7

### ISSUE THREAD

**Issue by kellybhoward** [microcovid/microcovid#822]
Hi there! Our pod noticed that C125 on the Pod Overview tab has the formula =7-0+1 (which obviously is 8) for the # of days in budget range. We are wondering why this formula exists in this way and why it is not 7 for 7 days in the week?
Thanks so much for checking it out!
<img width="518" alt="Screen Shot 2021-04-04 at 11 46 04 AM" src="https://user-images.githubusercontent.com/11801384/113518470-64b31880-953b-11eb-8087-473b51712439.png">

**Comment by blanchardjeremy** [comment]
Thanks for the bug report. 

Fixed with version 2.2.5

See changelog: https://docs.google.com/document/d/1iwTFoCS8lOIWWm-ZzcMZ_mPHgA8tHVVA3yhKY23gDu8/edit#heading=h.1t0cizoyzqui
