### ISSUE TITLE
Contradiction in Vaccine Q&A section

### ISSUE THREAD

**Issue by justinhaaheim** [microcovid/microcovid#859]
The summary of the "How should we think about people who have been vaccinated" section says "Additionally, each microCOVID may be 2-4x less likely to land a vaccinated individual in a hospital." ([src](https://github.com/microcovid/microcovid/blob/c6ea542cd401c83e3b71ab28a554464dd3333937/src/posts/paper/13-q-and-a.ts#L186)) 

But the section [here](https://www.microcovid.org/paper/13-q-and-a#2-if-a-vaccinated-individual-contracts-covid-how-much-less-or-more-likely-is-this-to-result-in-negative-consequences-increased-budget) seems to contradict that:

> Therefore we do not think that mRNA vaccines reduce the chance of hospitalization or death beyond the reduction in contracting COVID in the first place. It is possible that the traditional vaccines (AstraZenica, Johnson&Johnson) are somewhat more protective againt severe COVID than mild COVID, but we have not seen compelling data for this.

Also there's a typo above: protective **againt** severe

--

So grateful to the crew maintaining and updating the microcovid site. Thank you!

**Comment by blanchardjeremy** [comment]
@beshaya I haven't been tracking our PRs. Is this already addressed in one of the PRs?

**Comment by beshaya** [comment]
@justinhaaheim I see how this is confusing. To explain what was going on: at the time of writing, there was considerable numeric uncertainty around this number and the prevailing expert opinion was that vaccines should be better at preventing hospitalizations than mild cases. 2-4x was meant to acknowledge that this was within the CI's of available data, but 1/4x was also in the CI at the time of writing.

In the last month, much data with much more precision re: severe outcomes w/ vaccination has come out; I have a PR in flight that clarifies this.

**Comment by blanchardjeremy** [comment]
Hopefully we'll get #836 merged pretty soon!
