### ISSUE TITLE
Risk Tracker: Update true infections model to match calculator

### ISSUE THREAD

**Issue by blanchardjeremy** [microcovid/microcovid#862]
See #861

**Comment by beshaya** [comment]
What's this ticket for? #861 updated both the prevalence and calculator...

**Comment by blanchardjeremy** [comment]
Sorry. I meant to type "Risk Tracker" in the title

**Comment by beshaya** [comment]
That's handled by the update prevalence script, right? I updated that part
as well.

**Comment by blanchardjeremy** [comment]
There is a section at the bottom of the locations sheet that lets you manually add location data. So this formula lives there as well and needs to be kept up to date. :)
