### ISSUE TITLE
Adjust vaccine effectiveness numbers to account for B.1.617.2 (Delta)?

### ISSUE THREAD

**Issue by orborde** [microcovid/microcovid#869]
https://www.medrxiv.org/content/10.1101/2021.05.22.21257658v1

> Effectiveness was notably lower after 1 dose of vaccine with B.1.617.2 cases 33.5% (95%CI: 20.6 to 44.3) compared to B.1.1.7 cases 51.1% (95%CI: 47.3 to 54.7) with similar results for both vaccines. With BNT162b2 2 dose effectiveness reduced from 93.4% (95%CI: 90.4 to 95.5) with B.1.1.7 to 87.9% (95%CI: 78.2 to 93.2) with B.1.617.2. With ChAdOx1 2 dose effectiveness reduced from 66.1% (95% CI: 54.0 to 75.0) with B.1.1.7 to 59.8% (95%CI: 28.9 to 77.3) with B.1.617.2. Sequenced cases detected after 1 or 2 doses of vaccination had a higher odds of infection with B.1.617.2 compared to unvaccinated cases (OR 1.40; 95%CI: 1.13-1.75).

For e.g. BNT162b2 (Pfizer), a reduction from 93.4% to 87.9% yields a (100-87.9)/(100-92.4) = ~1.6x increase in microcovids accumulated.

As of this writing, https://nextstrain.org/ncov/global shows 21A Delta at 14% of collected samples.

**Comment by beshaya** [comment]
Thanks for bringing this to our attention. Is this additive with increased infectiousness of the variant?

I'm somewhat concerned about the wide CI's with B.1.617.2, since there's quite a bit of overlap.

**Comment by orborde** [comment]
> Is this additive with increased infectiousness of the variant?

I don't know. I've been treating  the answer as "no" in my own calculations (i.e. that rough 1.6x multiplier).

**Comment by acconrad** [comment]
They're now saying it is only [66% effective](https://www.ft.com/content/0b3da41e-6390-4f4b-866c-da5c6aec7f5e)

**Comment by joshjacobson** [comment]
Zvi [says](https://www.lesswrong.com/posts/KfW3iGSttvfLY74tt/covid-7-15-rates-of-change#UK_Data):

> Our lower bound should presumably be that Delta is 50% more infectious than Alpha, but that vaccine effectiveness is mostly unchanged. 
> 
> Under Israeli conditions, it seems mostly safe to say that Delta is at most twice as infectious as Alpha, but that about twice is possible. This is the scariest data set. 
> 
> Under UK conditions, it seems mostly safe to say that Delta is at most 75% more infectious than Alpha, and it would be difficult to get to a doubling.
> 
> Under American conditions, it seems mostly safe to say that Delta is going to be less than twice as infectious, given everything we know – the math starts to fold in on itself if we get above 75% or so, in the sense that things need to look much worse than they do. I’d put a soft bound around 75%.

Whereas per @orborde 's comment above in combination with the UK data @acconrad cites (adjusting for typos in each), (100-64)/(100-93.4) = ~5.45x increase in microcovids.

1. What adjustment seems to be the right one to use based on limited data for now?
2. And until microcovid is updated, shouldn't there be a large bold red disclaimer that it has not been updated for the delta variant?

**Comment by beshaya** [comment]
@acconrad Do you have a link to the actual study? That looks like a pop sci paper behind a paywall.

@joshjacobson Could you include primary research sources for those claims?

**Comment by orborde** [comment]
> @acconrad Do you have a link to the actual study? That looks like a pop sci paper behind a paywall.

When this story broke, I looked around for the original study or supporting data. The closest I could find was the [Israeli Ministry of Health announcement](https://www.gov.il/he/departments/news/05072021-03).

**Comment by beshaya** [comment]
@orborde Yeah, I've seen that too. Here's the thing - that doesn't appear to control for exposure at all. It's simply the relative rate of infection among vaccinated and unvaccinated individuals. Combining the UK data which directly compares Alpha to Delta shows 88% vaccine efficacy. If we assume that vaccinated individuals are exposed to 3x more virus (roughly speaking, seeing 30x more people indoors and undistanced), then the data sets agree. 
https://www.medrxiv.org/content/10.1101/2021.05.22.21257658v1
https://khub.net/web/phe-national/public-library/-/document_library/v2WsRK3ZlEig/view_file/479607329?_com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_v2WsRK3ZlEig_redirect=https%3A%2F%2Fkhub.net%3A443%2Fweb%2Fphe-national%2Fpublic-library%2F-%2Fdocument_library%2Fv2WsRK3ZlEig%2Fview%2F479607266

Additionally, studies on antibody binding affinity suggests that binding affinity to Delta spike proteins are decreased but still robust:
https://www.nejm.org/doi/10.1056/NEJMc2107799

None of the nationwide Israel data controls for behavior changes post vaccination. This is very different from, say, phase III studies, where individuals were randomized and blinded. Now vaccinated people are not only unblinded, they are actively encouraged to spend time indoors + unmasked outdoors with strangers. The data coming out is still useful for efficacy vs hospitalization, but not so useful for overall vaccine efficacy.

This does suggest that our multiplier for "random vaccinated person" may be too generous and we should assume that vaccinated individuals are doing more risky behavior.

**Comment by acconrad** [comment]
@beshaya so is your point here that the 88% efficacy data is more reliable than the 66% efficacy data? Genuinely asking because I appreciate your thoroughness and would be useful for me in the future if I'm presenting data to change something.

**Comment by beshaya** [comment]
My point is that both data are probably reliable and accurate, but they aren't testing the same question.

The UK research addresses "how effective is 2 doses of BNT162b2 at preventing infection from the delta variant, controlling for behavior of vaccinated vs unvaccinated individuals" and the answer is 88%.

The Israel research appears to address "how effective is 2 doses of BNT162b2 plus the behavioral patterns of vaccinated people at preventing infection from any variant of COVID" and the answer is 66%.

For the purposes of microCOVID vaccine multipliers, we care about the former. For the question of "should I behave as if there wasn't a pandemic after getting vaccinated" you may care about the latter.
