### ISSUE TITLE
Work with the OneMedical security team to get the site classified as not malware

### ISSUE THREAD

**Issue by catherio** [microcovid/microcovid#87]
![image](https://user-images.githubusercontent.com/245037/91599295-e8a88080-e91a-11ea-8941-1e60f8f907a0.png)

**Comment by catherio** [comment]
is this done? I heard it's fine now?

**Comment by oremanj** [comment]
We haven't heard back from One Medical. Maybe they made an exception for us, or maybe the changes I made meant they didn't have to.

**Comment by pde** [comment]
According to some investigation by @hliss, the issue is that you're on OpenDNS's spam RBL. I think I have a contact over there if you're still stuck after investigating.

**Comment by hliss** [comment]
Thanks @pde for the link to this issue! Can confirm that SAP's network cites Cisco Umbrella as the reason for the site block, and I'm redirected to a page on malware.opendns.com.

**Comment by pde** [comment]
https://support.opendns.com/hc/en-us/articles/227987347-Why-is-this-Domain-Blocked-or-not-Blocked-

@dominic If you've email[ed] support@opendns.com and not heard back in ~a day, let me know!

**Comment by catherio** [comment]
![image](https://user-images.githubusercontent.com/245037/91778847-a8f6c880-eba8-11ea-9948-f2a03e18add8.png)

**Comment by catherio** [comment]
![image](https://user-images.githubusercontent.com/245037/91778889-ca57b480-eba8-11ea-9410-f60ae439292e.png)

**Comment by oremanj** [comment]
Is the user reporting this issue behind a corporate firewall/proxy/something? The most likely cause (IMO) is that it's getting blocked by said firewall for the reasons discussed upthread, and the "this was blocked" page isn't getting shown because the firewall doesn't have our SSL certificate so it can't validly claim to be microcovid.org.

**Comment by dominic** [comment]
According to https://community.opendns.com/domaintagging/search/?q=www.microcovid.org, we're not tagged as anything in their system, so it'll be hard to request an unblock. Hm.

**Comment by pde** [comment]
Probably this person has a MITM firewall or a false DNS response or some other kind of network shenanigans. Next step I investigating would be to get them to send you the certificate chain they're seeing. In chrome, on the cert warning page, click on "not secure" next to the URL bar, then "certificate", then "details", then "export".

> ![image](https://user-images.githubusercontent.com/245037/91778889-ca57b480-eba8-11ea-9410-f60ae439292e.png)

**Comment by pde** [comment]
It's possible that OpenDNS has already unblocked the domain, but @hliss can you check to see if the problem seems resolved?

**Comment by hliss** [comment]
Issue is resolved for me! FWIW, when I looked earlier today (midday Pacific time) there were no tags on opendns then either.

**Comment by jy2wong** [comment]
Looks resolved?
