### ISSUE TITLE
New prevalences have extra array fields which the spreadsheet is not prepared for

### ISSUE THREAD

**Issue by carlyrobison** [microcovid/microcovid#871]
This is causing divide by 0 errors and everything is breaking.

Spreadsheet error message: "Array result was not expanded because it would overwrite data in C[cell number]."

This error was resolved by adding rows in the INTERNAL_LOCATIONS sheet, but I haven't yet figured out how to make it load right in the Locations sheet.

**Comment by beshaya** [comment]
Sorry for that, thanks for the quick bug report. Should be fixed now.

**Comment by carlyrobison** [comment]
Confirmed, fixed on my end. Thanks for the quick response!
