### ISSUE TITLE
Update 5-activity-risk and research sources to explain higher transmission rates

### ISSUE THREAD

**Issue by joshjob42** [microcovid/microcovid#885]
I apologize if this is explained somewhere but I couldn't find any discussion of it anywhere. The white paper, [here](https://www.microcovid.org/paper/5-activity-risk) and in the linked [resources](https://www.microcovid.org/paper/14-research-sources#modifiers-to-activity-risk-masked-outdoors-distanced) seems to pretty clearly say that risk is! ~6%/hr for standard (3ft) indoor unmasked interactions with a person who has COVID, from which basically everything else is based.

However both in the basic model and the risk tracker this is modeled as 9%, which increases every estimate 50%. Is this simply being conservative, is the white paper and resources out of date in some manner, or is it simply a typo?

**Comment by blanchardjeremy** [comment]
Ah good question. 9% is accurate. It used to be 6%. Then the B117 variant hit the world and it's 50% more contagious. So we upped it to 9%.

**Comment by jy2wong** [comment]
This is documented here: https://www.microcovid.org/blog/b117

Point taken that this info could be easier to find.

**Comment by blanchardjeremy** [comment]
I'm re-opening. Should we change it in the whitepaper? https://www.microcovid.org/paper/5-activity-risk

**Comment by jy2wong** [comment]
addressed in the delta update #911
