### ISSUE TITLE
Sudden change in numbers?

### ISSUE THREAD

**Issue by Hixie** [microcovid/microcovid#894]
California, Santa Clara: from what I can tell according to the public dashboards, seems to be doing ok. Until recently, microcovid.org had been tracking the average person as having a risk of around 200 or 300μC. Today it says 2000μC.

Florida, Miami-Dade: I can't find their public dashboard, but until recently microcovid.org was reporting the average person as having a risk in the high hundreds to low thousands. As of today it says the average person's risk is 0.9μC.

I'm skeptical of these sudden changes; can you confirm whether they are intentional or not?

**Comment by blanchardjeremy** [comment]
Hmmmm. Thanks for reporting this. We're just beginning to look into what caused it. But it seems like it might be some issues with how the counties are reporting data. We pull from JHU data.

We'll keep looking into it.

**Comment by Hixie** [comment]
I looked into the CSSEGISandData data for Santa Clara specifically and may have found the issue. This is what the raw data of new cases per day looks like (taking the data from https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv and charting the differences between each row):
![chart (2)](https://user-images.githubusercontent.com/551196/124666353-c8aeeb00-de62-11eb-9477-36e8672d843b.png)

Look in particular at the very end where for some reason the number of confirmed cases _dropped_, causing what looks like first a huge drop in numbers and then a huge increase in numbers. Could it be that the model is seeing that giant rise as a sign of a sudden surge in covid cases in Santa Clara?

**Comment by blanchardjeremy** [comment]
I think that #896 is designed to address this, but I'll let @beshaya confirm.

**Comment by beshaya** [comment]
Yep, #896 will fix this in the next prevalence update.

**Comment by blanchardjeremy** [comment]
#898 is the prevalence update in question

**Comment by blanchardjeremy** [comment]
I can confirm santa clara is working. But it was working before #896 when I did a prevalence update earlier today.

**Comment by Hixie** [comment]
y'all rock, thanks!
