### ISSUE TITLE
Old links to prepared scenarios broken

### ISSUE THREAD

**Issue by Hixie** [microcovid/microcovid#900]
I have a spreadsheet with many links to microcovid.org models for quickly updating the sheet by opening each link and copying out the new numbers.

Unfortunately, the recent changes to the UI broke all these links. Is there any way we can maintain backwards compatibility for old links? or if there's a way to easily migrate the links, that would work too.

For example:
https://www.microcovid.org/?distance=normal&duration=600&interaction=oneTime&personCount=80&riskProfile=average&setting=indoor&subLocation=US_12086&theirMask=none&topLocation=US_12&voice=loud&yourMask=none&yourVaccineDoses=2&yourVaccineType=pfizer

https://www.microcovid.org/?distance=normal&duration=1040&interaction=oneTime&personCount=20&riskProfile=average&setting=indoor&subLocation=US_06085&theirMask=thin&topLocation=US_06&voice=normal&yourMask=thin&yourVaccineDoses=2

(Actually the links still seem to give numbers, they just don't show the selections in the UI anymore?)

**Comment by Hixie** [comment]
Looks like adding `&scenarioName=custom` is what is needed.

**Comment by jy2wong** [comment]
Yeah, it's currently set to not show anything if scenarioName is "". I think I can fix this by replacing an absent query parameter with "custom" instead of "". Thanks for the report!

**Comment by jy2wong** [comment]
@Hixie can you try out #902 over at https://deploy-preview-902--microcov.netlify.app/ ?

**Comment by Hixie** [comment]
Looks good!
