### ISSUE TITLE
Philadelphia numbers seem unlikely

### ISSUE THREAD

**Issue by Hixie** [microcovid/microcovid#901]
An average person in [Santa Clara, CA](https://www.microcovid.org/?duration=60&interaction=oneTime&personCount=1&riskProfile=average&scenarioName=custom&subLocation=US_06085&theirMask=none&topLocation=US_06&yourMask=none&yourVaccineDoses=2) gets assigned a baseline risk level of 300μC. Santa Clara has [about 20-100 cases daily](https://www.google.com/search?q=santa+clara+covid+numbers&oq=santa+clara+covid+numbers&aqs=chrome.0.0i20i263j0i20i263i457j0l3j69i60l3.2972j0j7&sourceid=chrome&ie=UTF-8).

An average person in [Philadelphia, PA](https://www.microcovid.org/?duration=60&interaction=oneTime&personCount=1&riskProfile=average&scenarioName=custom&subLocation=US_42101&theirMask=none&topLocation=US_42&yourMask=none&yourVaccineDoses=2) gets assigned a baseline risk level of 1μC. Philadelphia has [about 20-100 cases daily](https://www.google.com/search?q=philadelphia+covid+numbers&oq=phi&aqs=chrome.0.69i59l2j69i57j6j69i60l4.1055j0j7&sourceid=chrome&ie=UTF-8).

(The populations are in the same order of magnitude.)

**Comment by blanchardjeremy** [comment]
Yeah our system is showing 0 cases this week and last week in Philadelphia. We'll look into it. Thanks.

**Comment by blanchardjeremy** [comment]
Looks like it's been resolved. Not sure what the cause was. But feel free to re-open if it pops up again.
