### ISSUE TITLE
Risk profile for vaccinated random people in spreadsheet

### ISSUE THREAD

**Issue by anyatche** [microcovid/microcovid#906]
The "Their vaccine: Are they fully vaccinated?" options when selecting "average person in your area" in the calculator have been really useful. I'm now wondering if it would be possible to add "Average person in your area (vaccinated)" and "Average person in your area (not vaccinated)" generic risk profiles to the spreadsheet as well, to track interactions with ~random people with a known vaccine status over time; I haven't been able to find a way to do this so far.

**Comment by blanchardjeremy** [comment]
Thanks for asking. 

It's definitely not in the spreadsheet yet.  It's a fairly large revision to the spreadsheet so we haven't gotten around to it yet. 

Not ready to make any promises of when it will exist just yet. But it helpful to know that there's a desire for it. 

In the meantime, you can copy paste the number from the "average vaccinated person" in your area from the website. You'll just need to update it every week or so.

**Comment by springfielddatarecovery** [comment]
Just wanted to add that I think this feature would be super useful as well. Thank you for all your work on this wonderful tool!

**Comment by durka** [comment]
Are there any plans for this? If not could you elaborate on where to "paste the number"?

There's an option for "their vaccine" on the website but I am very very lost when trying to add "average vaccinated person" profile using the "custom people" sheet. I can't get my numbers to match how the website is applying the "their vaccine" checkbox.

**Comment by durka** [comment]
For context, my workplace has a vaccine mandate, and the whole point of advocating for that is to make it safer to go there than if it was full of "average local residents". But I have no idea if my coworkers are in pods etc. So this is a pretty necessary feature.

**Comment by blanchardjeremy** [comment]
I've begun working on this in #974

**Comment by blanchardjeremy** [comment]
It's live now with Risk Tracker v2.2.6

You can see the changelog details here to implement it in your own spreadsheet: https://docs.google.com/document/d/1iwTFoCS8lOIWWm-ZzcMZ_mPHgA8tHVVA3yhKY23gDu8/edit#heading=h.xr1t7lx85miw
