### ISSUE TITLE
Large discrepancies in reported cases between spreadsheet and data source 

### ISSUE THREAD

**Issue by blakej11** [microcovid/microcovid#913]
I can't help but notice that the uCov numbers for Alameda County (CA) are extremely high right now. And while I should probably be pretty cautious, given that the model hasn't been updated for the Delta variant yet, it still seems like things are out of whack.

I looked at the "cases in past week" numbers in my spreadsheet (which has a "Date Last Updated" = Jul-24-2021, and "Is Import Broken" = FALSE), and compared them to the underlying data sources: [July 17th](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-17-2021.csv) and [July 24th](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-24-2021.csv) data from JHU CSSE.

52 of the 58 counties matched exactly, but six of the 58 had disagreements:

||uCov|JHU CSSE|delta|
|-|-|-|-|
|Alameda|4879|1973|2906|
|Contra Costa|1464|1685|-221|
|Kings|167|179|-12|
|Los Angeles|13900|15533|-1633|
|Marin|166|176|-10|
|San Francisco|952|976|-24|

So it looks like Alameda County's rate is being overreported by almost 250%.

**Comment by blanchardjeremy** [comment]
Thanks for reporting this. We'll look into it.

**Comment by jy2wong** [comment]
Data source issue. On July 22 the confirmed case count unexpectedly jumps ~4k higher, then "goes down" by 3.5k on July 23.

> Alameda: daily cumulative cases: [91028, 91197, 91546, 91743, 91937, 92091, 92372, 92580, 92584, 92973, 93361, **97459**, 93953, 94345]

To reliably repro, I set `now = datetime(2021, 7, 25, 12, 0, 0, 0) - timedelta(days=1)` in `calc_effective_date()`.

```
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-24-2021.csv... read 3988 objects
Alameda: line is JHUDailyReport(FIPS=6001, Admin2='Alameda', Province_State='California', Country_Region='US', Lat=37.64629437, Long_=-121.8929271, Combined_Key='Alameda, California, US', Confirmed=94345, Deaths=1272, Recovered=0, Active=0)
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-23-2021.csv... read 3988 objects
Alameda: line is JHUDailyReport(FIPS=6001, Admin2='Alameda', Province_State='California', Country_Region='US', Lat=37.64629437, Long_=-121.8929271, Combined_Key='Alameda, California, US', Confirmed=93953, Deaths=1272, Recovered=0, Active=0)
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-22-2021.csv... read 3988 objects
Alameda: line is JHUDailyReport(FIPS=6001, Admin2='Alameda', Province_State='California', Country_Region='US', Lat=37.64629437, Long_=-121.8929271, Combined_Key='Alameda, California, US', Confirmed=97459, Deaths=1322, Recovered=0, Active=0)
Fetching https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-21-2021.csv... read 3988 objects
Alameda: line is JHUDailyReport(FIPS=6001, Admin2='Alameda', Province_State='California', Country_Region='US', Lat=37.64629437, Long_=-121.8929271, Combined_Key='Alameda, California, US', Confirmed=93361, Deaths=1272, Recovered=0, Active=0)
```

This is in the same area of code as https://github.com/microcovid/microcovid/pull/896. (also note that the 6 days discrepancy will be addressed in https://github.com/microcovid/microcovid/pull/904 but I'm not touching it for now).

**Comment by beshaya** [comment]
Thanks for the sleuthing. Maybe we need to throw an elliptical filter on the data?

**Comment by jy2wong** [comment]
I checked all 6 counties that Blake mentioned against the above PR and they're an exact match for the JHU CSSE data.
