### ISSUE TITLE
Show 2 sigfigs in the Calculator?

### ISSUE THREAD

**Issue by neelnanda-io** [microCOVID/microCOVID#916]
There's a bug in the calculator where, as I increase the activity duration, the calculated risk gets stuck at a constant value for a while and then abruptly doubles.

Eg, for anything between [180 minutes](https://www.microcovid.org/?distance=normal&duration=180&interaction=oneTime&personCount=6&riskBudget=30000&riskProfile=average&scenarioName=custom&setting=outdoor&subLocation=United_Kingdom_England&theirMask=none&topLocation=United_Kingdom&voice=normal&yourMask=none&yourVaccineDoses=2) and [280 minutes](https://www.microcovid.org/?distance=normal&duration=280&interaction=oneTime&personCount=6&riskBudget=30000&riskProfile=average&scenarioName=custom&setting=outdoor&subLocation=United_Kingdom_England&theirMask=none&topLocation=United_Kingdom&voice=normal&yourMask=none&yourVaccineType=moderna) it calculates 1000uC and for [281](https://www.microcovid.org/?distance=normal&duration=281&interaction=oneTime&personCount=6&riskBudget=30000&riskProfile=average&scenarioName=custom&setting=outdoor&subLocation=United_Kingdom_England&theirMask=none&topLocation=United_Kingdom&voice=normal&yourMask=none&yourVaccineType=moderna) it calculates 2000uC

I've replicated this in multiple other settings, eg [164 vs 165 minutes](https://www.microcovid.org/?distance=normal&duration=164&interaction=oneTime&personCount=6&riskBudget=30000&riskProfile=average&scenarioName=custom&setting=outdoor&subLocation=United_Kingdom_England&theirMask=none&topLocation=United_Kingdom&voice=normal&yourMask=none&yourVaccineDoses=2&yourVaccineType=moderna). I've skimmed the calculate code, and can't easily see the bug.

**Comment by neelnanda-io** [comment]
Actually, maybe the problem is just that it's rounding to 1 sig fig? I think this is pretty unhelpful though, the second sig fig really matters when you're near 100!

**Comment by blanchardjeremy** [comment]
You're correct, it is because we're rounding to one sig fig. That's the amount of confidence we have in the model we've developed.

If you want the exact microCOVID number with no rounding, I suggest using the [Risk Tracker](https://www.microcovid.org/tracker).

**Comment by beshaya** [comment]
Hm, maybe we should just show 2 sigfigs. It's kind of wrong, but also this appears to confuse a lot of people.

**Comment by beshaya** [comment]
> Actually, maybe the problem is just that it's rounding to 1 sig fig? I think this is pretty unhelpful though, the second sig fig really matters when you're near 100!

Yes and no. We're saying that, when it says "100" it's "somewhere between 30 and 300", so the difference between 100 and 150 shouldn't really matter to you. But... that conveys the that there are these jump discontinuities, which is also wrong.

**Comment by blanchardjeremy** [comment]
I can see a case to show 2 sig figs just for a clearer user experience. But I'm not the sig-fig expert on the team. ;)
