### ISSUE TITLE
"Their Vaccine" section missing from some scenarios, including with "Living/staying with others"

### ISSUE THREAD

**Issue by dwalsh3** [microcovid/microcovid#917]
"Their Vaccine" section missing from some scenarios, including with "Living/staying with others"

![image](https://user-images.githubusercontent.com/2986469/127418273-ef350591-de8c-4fd4-98bf-34537286780c.png)

**Comment by blanchardjeremy** [comment]
Can you copy the link to the exact configuration where you aren't seeing "their vaccine" show up? That would help us reproduce it. 

I'm able to see "their vaccine" in this scenario: https://www.microcovid.org/?interaction=repeated&personCount=1&riskProfile=average&scenarioName=custom&subLocation=US_06001&topLocation=US_06&yourVaccineDoses=2

Thanks!

**Comment by dwalsh3** [comment]
Nevermind, I can't reproduce the problem. Likely user error :)

**Comment by blanchardjeremy** [comment]
;) 

No worries!
