### ISSUE TITLE
Add "their vaccine" option, similar to "your mask / their mask"

### ISSUE THREAD

**Issue by puremachinery** [microcovid/microcovid#946]
When estimating a scenario for spending time with others, the current site allows selecting whether the other person is wearing a mask but not whether they've been vaccinated. Thus someone who's had 2x Moderna shots might be a further 0.17x adjustment to microcovids in a given interaction due to their lowered risk of catching it in their interactions.

**Comment by dhouck** [comment]
This already is an option sometimes (I saw it for the pre-built plane flight scenario) but it doesnʼt show up in custom scenarios.

**Comment by jy2wong** [comment]
@dhouck give it a try now!

**Comment by dhouck** [comment]
Thanks!

Unfortunately I was overestimating how much them having the vaccine helped, so Iʼm probably not able to do the thing I was on the fence about.  Fortunately, I know that now.
