### ISSUE TITLE
Add St Louis City (it is its own county)

### ISSUE THREAD

**Issue by matriarco** [microcovid/microcovid#949]
I live in St Louis City in Missouri, which is its own county, but the only option given is St Louis County, which is actually a different place with very different numbers and different policies around covid. It would be helpful to have St Louis City as its own option to be able to make more informed decisions.

**Comment by blanchardjeremy** [comment]
Can you link to a website that shows the number of cases in your county? I don't see it listed anywhere from a quick Google search. But maybe that's because of its odd name.

**Comment by blanchardjeremy** [comment]
Hmmm. It appears to me that we have both already. 

![7E4B794E-A648-4563-88D1-9E05DD066236](https://user-images.githubusercontent.com/32290/129094148-7d0b1cce-c983-42ca-bd6f-1f0ed02be700.png)


Is the issue that the data doesn't match what you expect? Or that you didn't see that this option exists?

**Comment by matriarco** [comment]
Hmm. For some reason they don't both show up on the dropdown menu. I do see them both when I search, though. I should have tried that. Sorry! Only St. Louis (which is the county) shows up on the menu. 

![image](https://user-images.githubusercontent.com/31931637/129109815-cf336a2e-93a8-4713-98ed-9bb198cb7f49.png)
