### ISSUE TITLE
"indoors with air filter" option doesn't use industry standards; missing time element

### ISSUE THREAD

**Issue by darthbonnet** [microCOVID/microCOVID#968]
[Issue brought up in email, dated June 2021, posted here at request of info@microcovid.org]

First, thanks for your contribution of the MicroCovid Tracker. I’ve used it (and loved it) for many months now.

I have a question about the Risk Tracker's version, v2.5, and the option within "Environment / Ventilation” dropdown, “indoors with a HEPA filter (flow rate of 5x room size).”

**Where is the element of time? Standard references to air flow involve a time element, such as "Air Changes Per Hour”** or the number of air changes in an hour that your air filter can perform given your square footage. New hospital construction typically aims for 12 air changes per hour. Source: Associated BodyWork and Massage Professionals’ monthly magazine, “How To Improve Treatment Room Air Quality: From Covid Protections to CO2 Concerns” by Julie Tudor. 

Caveat: Not all air in a room moves efficiently through an air filtration system, unless it’s forced air with vents spaced around the room to avoid slow moving spots. 

The way it’s written, I’ve got no way of knowing if I meet your criteria. 

Why this is important to me: I’m attempting to assess the risk for dropping my face mask mandate in my massage studio, to match new June 15 state guidelines. If I meet this HEPA filter standard, given all the safeguards I have in place, then it’s absolutely safe for me to allow clients to remove their face masks. If I don’t meet this criteria of “flow rate of 5x room size” then it’s absolutely NOT safe for me to allow clients to remove their face masks.

Obviously, I understand that these are ballpark estimates, and it’s only one part of my decision, but the micro covid tool has been so useful to me in the past - I’d love to be able to use it as one of my data points.

Thanks,
—A

**Comment by beshaya** [comment]
Oh good catch, that should read "flow rate of 5x room size _per hour_"

**Comment by beshaya** [comment]
By the way, we have a handy calculator for finding the necessary CFM given the dimensions of a room at https://www.microcovid.org/blog/hepafilters
